<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Building Models for Interpretation | Stat 255: Statistics for Data Science Notes</title>
  <meta name="description" content="Chapter 6 Building Models for Interpretation | Stat 255: Statistics for Data Science Notes" />
  <meta name="generator" content="bookdown 0.31 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Building Models for Interpretation | Stat 255: Statistics for Data Science Notes" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Building Models for Interpretation | Stat 255: Statistics for Data Science Notes" />
  
  
  

<meta name="author" content="Andrew Sage - Lawrence University" />


<meta name="date" content="2023-10-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="normal-error-regression-model.html"/>
<link rel="next" href="predictive-modeling.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STAT 255 Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html"><i class="fa fa-check"></i><b>1</b> Exploratory Data Analysis</a>
<ul>
<li class="chapter" data-level="1.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#getting-started-in-r"><i class="fa fa-check"></i><b>1.1</b> Getting Started in R</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#previewing-the-data"><i class="fa fa-check"></i><b>1.1.1</b> Previewing the Data</a></li>
<li class="chapter" data-level="1.1.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#modifying-the-data"><i class="fa fa-check"></i><b>1.1.2</b> Modifying the Data</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#data-visualization"><i class="fa fa-check"></i><b>1.2</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#histogram"><i class="fa fa-check"></i><b>1.2.1</b> Histogram</a></li>
<li class="chapter" data-level="1.2.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#density-plot"><i class="fa fa-check"></i><b>1.2.2</b> Density Plot</a></li>
<li class="chapter" data-level="1.2.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#boxplot"><i class="fa fa-check"></i><b>1.2.3</b> Boxplot</a></li>
<li class="chapter" data-level="1.2.4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#violin-plot"><i class="fa fa-check"></i><b>1.2.4</b> Violin Plot</a></li>
<li class="chapter" data-level="1.2.5" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#scatterplot"><i class="fa fa-check"></i><b>1.2.5</b> Scatterplot</a></li>
<li class="chapter" data-level="1.2.6" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#bar-graph"><i class="fa fa-check"></i><b>1.2.6</b> Bar Graph</a></li>
<li class="chapter" data-level="1.2.7" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#stacked-and-side-by-side-bar-graphs"><i class="fa fa-check"></i><b>1.2.7</b> Stacked and Side-by-Side Bar Graphs</a></li>
<li class="chapter" data-level="1.2.8" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#correlation-plot"><i class="fa fa-check"></i><b>1.2.8</b> Correlation Plot</a></li>
<li class="chapter" data-level="1.2.9" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#scatterplot-matrix"><i class="fa fa-check"></i><b>1.2.9</b> Scatterplot Matrix</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#summary-tables"><i class="fa fa-check"></i><b>1.3</b> Summary Tables</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#calculating-summary-statistics"><i class="fa fa-check"></i><b>1.3.1</b> Calculating Summary Statistics</a></li>
<li class="chapter" data-level="1.3.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#grouped-summaries"><i class="fa fa-check"></i><b>1.3.2</b> Grouped Summaries</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html"><i class="fa fa-check"></i><b>2</b> Introduction to Statistical Models</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#fitting-models-to-data"><i class="fa fa-check"></i><b>2.1</b> Fitting Models to Data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#terminology"><i class="fa fa-check"></i><b>2.1.1</b> Terminology</a></li>
<li class="chapter" data-level="2.1.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-with-quantitative-explanatory-variable"><i class="fa fa-check"></i><b>2.1.2</b> Model with Quantitative Explanatory Variable</a></li>
<li class="chapter" data-level="2.1.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-with-categorical-variable"><i class="fa fa-check"></i><b>2.1.3</b> Model with Categorical Variable</a></li>
<li class="chapter" data-level="2.1.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-with-multiple-explanatory-variables"><i class="fa fa-check"></i><b>2.1.4</b> Model with Multiple Explanatory Variables</a></li>
<li class="chapter" data-level="2.1.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-with-no-explanatory-variable"><i class="fa fa-check"></i><b>2.1.5</b> Model with No Explanatory Variable</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#variability-explained-by-a-model"><i class="fa fa-check"></i><b>2.2</b> Variability Explained by a Model</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#quantifying-variability"><i class="fa fa-check"></i><b>2.2.1</b> Quantifying Variability</a></li>
<li class="chapter" data-level="2.2.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#total-variability"><i class="fa fa-check"></i><b>2.2.2</b> Total Variability</a></li>
<li class="chapter" data-level="2.2.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#residuals"><i class="fa fa-check"></i><b>2.2.3</b> Residuals</a></li>
<li class="chapter" data-level="2.2.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#variability-explained-by-sq.-ft.-model"><i class="fa fa-check"></i><b>2.2.4</b> Variability Explained by Sq. Ft. Model</a></li>
<li class="chapter" data-level="2.2.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#linear-correlation-coefficient"><i class="fa fa-check"></i><b>2.2.5</b> Linear Correlation Coefficient</a></li>
<li class="chapter" data-level="2.2.6" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#variability-explained-by-waterfront-model"><i class="fa fa-check"></i><b>2.2.6</b> Variability Explained by Waterfront Model</a></li>
<li class="chapter" data-level="2.2.7" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#variability-explained-by-multiple-regression-model"><i class="fa fa-check"></i><b>2.2.7</b> Variability Explained by Multiple Regression Model</a></li>
<li class="chapter" data-level="2.2.8" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#summary-sst-ssr-ssm-r2"><i class="fa fa-check"></i><b>2.2.8</b> Summary: SST, SSR, SSM, <span class="math inline">\(R^2\)</span></a></li>
<li class="chapter" data-level="2.2.9" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#r2-visually"><i class="fa fa-check"></i><b>2.2.9</b> <span class="math inline">\(R^2\)</span> Visually</a></li>
<li class="chapter" data-level="2.2.10" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-comparison-summary"><i class="fa fa-check"></i><b>2.2.10</b> Model Comparison Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#models-with-interaction"><i class="fa fa-check"></i><b>2.3</b> Models with Interaction</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#definition-of-interaction"><i class="fa fa-check"></i><b>2.3.1</b> Definition of Interaction</a></li>
<li class="chapter" data-level="2.3.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#interaction-term"><i class="fa fa-check"></i><b>2.3.2</b> Interaction Term</a></li>
<li class="chapter" data-level="2.3.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#interaction-models-in-r"><i class="fa fa-check"></i><b>2.3.3</b> Interaction Models in R</a></li>
<li class="chapter" data-level="2.3.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#r2-for-interaction-model"><i class="fa fa-check"></i><b>2.3.4</b> <span class="math inline">\(R^2\)</span> for Interaction Model</a></li>
<li class="chapter" data-level="2.3.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#considerations-for-using-interactions"><i class="fa fa-check"></i><b>2.3.5</b> Considerations for Using Interactions</a></li>
<li class="chapter" data-level="2.3.6" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#interaction-vs-correlation"><i class="fa fa-check"></i><b>2.3.6</b> Interaction vs Correlation</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#least-squares-estimation-lse"><i class="fa fa-check"></i><b>2.4</b> Least Squares Estimation (LSE)</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#estimating-regression-coefficients"><i class="fa fa-check"></i><b>2.4.1</b> Estimating Regression Coefficients</a></li>
<li class="chapter" data-level="2.4.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#mathematics-of-lse-for-slr"><i class="fa fa-check"></i><b>2.4.2</b> Mathematics of LSE for SLR</a></li>
<li class="chapter" data-level="2.4.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#lse-for-categorical-variable"><i class="fa fa-check"></i><b>2.4.3</b> LSE for Categorical Variable</a></li>
<li class="chapter" data-level="2.4.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#lse-more-generally"><i class="fa fa-check"></i><b>2.4.4</b> LSE More Generally</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#analysis-of-variance"><i class="fa fa-check"></i><b>2.5</b> ANalysis Of VAriance</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#submodels"><i class="fa fa-check"></i><b>2.5.1</b> Submodels</a></li>
<li class="chapter" data-level="2.5.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#f-statistics"><i class="fa fa-check"></i><b>2.5.2</b> F-Statistics</a></li>
<li class="chapter" data-level="2.5.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#comparing-3-or-more-categories"><i class="fa fa-check"></i><b>2.5.3</b> Comparing 3 or More Categories</a></li>
<li class="chapter" data-level="2.5.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#f-statistic-illustration"><i class="fa fa-check"></i><b>2.5.4</b> F-Statistic Illustration</a></li>
<li class="chapter" data-level="2.5.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#alternative-f-statistic-formula"><i class="fa fa-check"></i><b>2.5.5</b> Alternative F-Statistic Formula</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html"><i class="fa fa-check"></i><b>3</b> Hypothesis Testing via Permutation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#test-for-difference-in-means"><i class="fa fa-check"></i><b>3.1</b> Test for Difference in Means</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#mercury-levels-in-florida-lakes"><i class="fa fa-check"></i><b>3.1.1</b> Mercury Levels in Florida Lakes</a></li>
<li class="chapter" data-level="3.1.2" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#model-for-mercury-level"><i class="fa fa-check"></i><b>3.1.2</b> Model for Mercury Level</a></li>
<li class="chapter" data-level="3.1.3" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#hypotheses-and-key-question"><i class="fa fa-check"></i><b>3.1.3</b> Hypotheses and Key Question</a></li>
<li class="chapter" data-level="3.1.4" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#permutation-test-for-difference-in-means"><i class="fa fa-check"></i><b>3.1.4</b> Permutation Test for Difference in Means</a></li>
<li class="chapter" data-level="3.1.5" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#five-permutations-in-r"><i class="fa fa-check"></i><b>3.1.5</b> Five Permutations in R</a></li>
<li class="chapter" data-level="3.1.6" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#r-code-for-permutation-test"><i class="fa fa-check"></i><b>3.1.6</b> R Code for Permutation Test</a></li>
<li class="chapter" data-level="3.1.7" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#p-values"><i class="fa fa-check"></i><b>3.1.7</b> p-values</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#general-permutation-tests"><i class="fa fa-check"></i><b>3.2</b> General Permutation Tests</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#other-test-statistics"><i class="fa fa-check"></i><b>3.2.1</b> Other Test Statistics</a></li>
<li class="chapter" data-level="3.2.2" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#general-permutation-test-procedure"><i class="fa fa-check"></i><b>3.2.2</b> General Permutation Test Procedure</a></li>
<li class="chapter" data-level="3.2.3" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#difference-in-standard-deviation"><i class="fa fa-check"></i><b>3.2.3</b> Difference in Standard Deviation</a></li>
<li class="chapter" data-level="3.2.4" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#permutation-test-for-slope"><i class="fa fa-check"></i><b>3.2.4</b> Permutation Test for Slope</a></li>
<li class="chapter" data-level="3.2.5" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#f-statistic"><i class="fa fa-check"></i><b>3.2.5</b> F-Statistic</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#responsible-hypothesis-testing"><i class="fa fa-check"></i><b>3.3</b> Responsible Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html"><i class="fa fa-check"></i><b>4</b> Bootstrap Interval Estimation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#sampling-distributions"><i class="fa fa-check"></i><b>4.1</b> Sampling Distributions</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#sampling-from-a-population"><i class="fa fa-check"></i><b>4.1.1</b> Sampling From a Population</a></li>
<li class="chapter" data-level="4.1.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#confidence-intervals"><i class="fa fa-check"></i><b>4.1.2</b> Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrapping"><i class="fa fa-check"></i><b>4.2</b> Bootstrapping</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#mercury-levels-in-florida-lakes-1"><i class="fa fa-check"></i><b>4.2.1</b> Mercury Levels in Florida Lakes</a></li>
<li class="chapter" data-level="4.2.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-sampling"><i class="fa fa-check"></i><b>4.2.2</b> Bootstrap Sampling</a></li>
<li class="chapter" data-level="4.2.3" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-samples-of-lakes"><i class="fa fa-check"></i><b>4.2.3</b> Bootstrap Samples of Lakes</a></li>
<li class="chapter" data-level="4.2.4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-distribution"><i class="fa fa-check"></i><b>4.2.4</b> Bootstrap Distribution</a></li>
<li class="chapter" data-level="4.2.5" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-se-confidence-interval"><i class="fa fa-check"></i><b>4.2.5</b> Bootstrap SE Confidence Interval</a></li>
<li class="chapter" data-level="4.2.6" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-distribution-vs-sampling-distribution"><i class="fa fa-check"></i><b>4.2.6</b> Bootstrap Distribution vs Sampling Distribution</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-confidence-interval-example"><i class="fa fa-check"></i><b>4.3</b> Bootstrap Confidence Interval Example</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrapping-other-statistics"><i class="fa fa-check"></i><b>4.3.1</b> Bootstrapping Other Statistics</a></li>
<li class="chapter" data-level="4.3.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-mean"><i class="fa fa-check"></i><b>4.3.2</b> CI for Mean</a></li>
<li class="chapter" data-level="4.3.3" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-standard-deviation"><i class="fa fa-check"></i><b>4.3.3</b> CI for Standard Deviation</a></li>
<li class="chapter" data-level="4.3.4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-median"><i class="fa fa-check"></i><b>4.3.4</b> CI for Median</a></li>
<li class="chapter" data-level="4.3.5" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-difference-in-means"><i class="fa fa-check"></i><b>4.3.5</b> CI for Difference in Means</a></li>
<li class="chapter" data-level="4.3.6" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-regression-slope"><i class="fa fa-check"></i><b>4.3.6</b> CI for Regression Slope</a></li>
<li class="chapter" data-level="4.3.7" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-regression-response"><i class="fa fa-check"></i><b>4.3.7</b> CI for Regression Response</a></li>
<li class="chapter" data-level="4.3.8" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#more-cis-in-regression"><i class="fa fa-check"></i><b>4.3.8</b> More CI’s in Regression</a></li>
<li class="chapter" data-level="4.3.9" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrapping-cautions"><i class="fa fa-check"></i><b>4.3.9</b> Bootstrapping Cautions</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#estimating-standard-error"><i class="fa fa-check"></i><b>4.4</b> Estimating Standard Error</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#standard-error-vs-standard-deviation"><i class="fa fa-check"></i><b>4.4.1</b> Standard Error vs Standard Deviation</a></li>
<li class="chapter" data-level="4.4.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#sample-size-and-standard-error"><i class="fa fa-check"></i><b>4.4.2</b> Sample Size and Standard Error</a></li>
<li class="chapter" data-level="4.4.3" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#standard-error-formulas"><i class="fa fa-check"></i><b>4.4.3</b> Standard Error Formulas</a></li>
<li class="chapter" data-level="4.4.4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#one-sample-mean-example"><i class="fa fa-check"></i><b>4.4.4</b> One-Sample Mean Example</a></li>
<li class="chapter" data-level="4.4.5" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#difference-in-means-example"><i class="fa fa-check"></i><b>4.4.5</b> Difference in Means Example</a></li>
<li class="chapter" data-level="4.4.6" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#regression-example"><i class="fa fa-check"></i><b>4.4.6</b> Regression Example</a></li>
<li class="chapter" data-level="4.4.7" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#theory-based-confidence-intervals"><i class="fa fa-check"></i><b>4.4.7</b> Theory-Based Confidence Intervals</a></li>
<li class="chapter" data-level="4.4.8" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-method-comparison"><i class="fa fa-check"></i><b>4.4.8</b> CI Method Comparison</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html"><i class="fa fa-check"></i><b>5</b> Normal Error Regression Model</a>
<ul>
<li class="chapter" data-level="5.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#the-normal-error-regression-model"><i class="fa fa-check"></i><b>5.1</b> The Normal Error Regression Model</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#example-ice-cream-dispenser"><i class="fa fa-check"></i><b>5.1.1</b> Example: Ice Cream dispenser</a></li>
<li class="chapter" data-level="5.1.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#signal-and-noise"><i class="fa fa-check"></i><b>5.1.2</b> Signal and Noise</a></li>
<li class="chapter" data-level="5.1.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#normal-distribution"><i class="fa fa-check"></i><b>5.1.3</b> Normal Distribution</a></li>
<li class="chapter" data-level="5.1.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#signal-and-noise-in-icecream-example"><i class="fa fa-check"></i><b>5.1.4</b> Signal and Noise in Icecream Example</a></li>
<li class="chapter" data-level="5.1.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#normal-error-regression-model-1"><i class="fa fa-check"></i><b>5.1.5</b> Normal Error Regression Model</a></li>
<li class="chapter" data-level="5.1.6" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#examples-of-normal-error-regression-model"><i class="fa fa-check"></i><b>5.1.6</b> Examples of Normal Error Regression Model</a></li>
<li class="chapter" data-level="5.1.7" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#implications-of-normal-error-regression-model"><i class="fa fa-check"></i><b>5.1.7</b> Implications of Normal Error Regression Model</a></li>
<li class="chapter" data-level="5.1.8" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#philosophical-question"><i class="fa fa-check"></i><b>5.1.8</b> Philosophical Question</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#inference-in-normal-error-regression-model"><i class="fa fa-check"></i><b>5.2</b> Inference in Normal Error Regression Model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#lm-summary-output"><i class="fa fa-check"></i><b>5.2.1</b> <code>lm</code> <code>summary</code> Output</a></li>
<li class="chapter" data-level="5.2.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#t-distribution"><i class="fa fa-check"></i><b>5.2.2</b> t-distribution</a></li>
<li class="chapter" data-level="5.2.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#difference-in-means-example-1"><i class="fa fa-check"></i><b>5.2.3</b> Difference in Means Example</a></li>
<li class="chapter" data-level="5.2.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#simple-linear-regression-example"><i class="fa fa-check"></i><b>5.2.4</b> Simple Linear Regression Example</a></li>
<li class="chapter" data-level="5.2.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#multiple-regression-example"><i class="fa fa-check"></i><b>5.2.5</b> Multiple Regression Example</a></li>
<li class="chapter" data-level="5.2.6" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#mr-with-interaction-example"><i class="fa fa-check"></i><b>5.2.6</b> MR with Interaction Example</a></li>
<li class="chapter" data-level="5.2.7" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#limitations"><i class="fa fa-check"></i><b>5.2.7</b> Limitations</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#f-distributions"><i class="fa fa-check"></i><b>5.3</b> F-Distributions</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#f-distribution"><i class="fa fa-check"></i><b>5.3.1</b> F-Distribution</a></li>
<li class="chapter" data-level="5.3.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#house-condition-example"><i class="fa fa-check"></i><b>5.3.2</b> House Condition Example</a></li>
<li class="chapter" data-level="5.3.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#interaction-example"><i class="fa fa-check"></i><b>5.3.3</b> Interaction Example</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#regression-model-assumptions"><i class="fa fa-check"></i><b>5.4</b> Regression Model Assumptions</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#regression-assumptions"><i class="fa fa-check"></i><b>5.4.1</b> Regression Assumptions</a></li>
<li class="chapter" data-level="5.4.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#checking-model-assumptions"><i class="fa fa-check"></i><b>5.4.2</b> Checking Model Assumptions</a></li>
<li class="chapter" data-level="5.4.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#summary-of-checks-for-model-assumptions"><i class="fa fa-check"></i><b>5.4.3</b> Summary of Checks for Model Assumptions</a></li>
<li class="chapter" data-level="5.4.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#example-n-v-s-lakes"><i class="fa fa-check"></i><b>5.4.4</b> Example: N v S Lakes</a></li>
<li class="chapter" data-level="5.4.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#example-ph-model"><i class="fa fa-check"></i><b>5.4.5</b> Example: pH Model</a></li>
<li class="chapter" data-level="5.4.6" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#example-house-prices"><i class="fa fa-check"></i><b>5.4.6</b> Example: House Prices</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#intervals-for-expected-response"><i class="fa fa-check"></i><b>5.5</b> Intervals for Expected Response</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#parameter-values-and-expected-responses"><i class="fa fa-check"></i><b>5.5.1</b> Parameter Values and Expected Responses</a></li>
<li class="chapter" data-level="5.5.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#estimation-and-prediction"><i class="fa fa-check"></i><b>5.5.2</b> Estimation and Prediction</a></li>
<li class="chapter" data-level="5.5.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#estimation-and-prediction-in-slr"><i class="fa fa-check"></i><b>5.5.3</b> Estimation and Prediction in SLR</a></li>
<li class="chapter" data-level="5.5.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#intervals-in-r"><i class="fa fa-check"></i><b>5.5.4</b> Intervals in R</a></li>
<li class="chapter" data-level="5.5.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#slr-calculations-optional"><i class="fa fa-check"></i><b>5.5.5</b> SLR Calculations (Optional)</a></li>
<li class="chapter" data-level="5.5.6" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#car-price-and-acceleration-time"><i class="fa fa-check"></i><b>5.5.6</b> Car Price and Acceleration Time</a></li>
<li class="chapter" data-level="5.5.7" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#florida-lakes-est.-and-pred."><i class="fa fa-check"></i><b>5.5.7</b> Florida Lakes Est. and Pred.</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#transformations"><i class="fa fa-check"></i><b>5.6</b> Transformations</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#cars-assumptions-check"><i class="fa fa-check"></i><b>5.6.1</b> Cars Assumptions Check</a></li>
<li class="chapter" data-level="5.6.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#log-transformation"><i class="fa fa-check"></i><b>5.6.2</b> Log Transformation</a></li>
<li class="chapter" data-level="5.6.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#log-transform-for-car-prices"><i class="fa fa-check"></i><b>5.6.3</b> Log Transform for Car Prices</a></li>
<li class="chapter" data-level="5.6.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#interpretations-in-log-model"><i class="fa fa-check"></i><b>5.6.4</b> Interpretations in Log Model</a></li>
<li class="chapter" data-level="5.6.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#log-model-predictions"><i class="fa fa-check"></i><b>5.6.5</b> Log Model Predictions</a></li>
<li class="chapter" data-level="5.6.6" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#log-model-interpretations"><i class="fa fa-check"></i><b>5.6.6</b> Log Model Interpretations</a></li>
<li class="chapter" data-level="5.6.7" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#log-model-ci-for-beta_0-beta_1"><i class="fa fa-check"></i><b>5.6.7</b> Log Model CI for <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span></a></li>
<li class="chapter" data-level="5.6.8" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#log-model-ci-for-expected-response"><i class="fa fa-check"></i><b>5.6.8</b> Log Model CI for Expected Response</a></li>
<li class="chapter" data-level="5.6.9" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#log-model-prediction-interval"><i class="fa fa-check"></i><b>5.6.9</b> Log Model Prediction Interval</a></li>
<li class="chapter" data-level="5.6.10" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#confidence-interval-comparison"><i class="fa fa-check"></i><b>5.6.10</b> Confidence Interval Comparison</a></li>
<li class="chapter" data-level="5.6.11" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#prediction-interval-comparison"><i class="fa fa-check"></i><b>5.6.11</b> Prediction Interval Comparison</a></li>
<li class="chapter" data-level="5.6.12" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#log-model-visualization"><i class="fa fa-check"></i><b>5.6.12</b> Log Model Visualization</a></li>
<li class="chapter" data-level="5.6.13" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#comments-on-transformations"><i class="fa fa-check"></i><b>5.6.13</b> Comments on Transformations</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#case-studies"><i class="fa fa-check"></i><b>5.7</b> Case Studies</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#flights-from-ny-to-chi"><i class="fa fa-check"></i><b>5.7.1</b> Flights from NY to CHI</a></li>
<li class="chapter" data-level="5.7.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#smoking-during-pregnancy"><i class="fa fa-check"></i><b>5.7.2</b> Smoking During Pregnancy</a></li>
<li class="chapter" data-level="5.7.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#smoking-during-pregnancy-cont"><i class="fa fa-check"></i><b>5.7.3</b> Smoking During Pregnancy (cont)</a></li>
<li class="chapter" data-level="5.7.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#exam-scores"><i class="fa fa-check"></i><b>5.7.4</b> Exam Scores</a></li>
<li class="chapter" data-level="5.7.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#simulating-the-regression-effect"><i class="fa fa-check"></i><b>5.7.5</b> Simulating the Regression Effect</a></li>
<li class="chapter" data-level="5.7.6" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#nfl-wins"><i class="fa fa-check"></i><b>5.7.6</b> NFL Wins</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#impact-of-model-assumption-violations"><i class="fa fa-check"></i><b>5.8</b> Impact of Model Assumption Violations</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html"><i class="fa fa-check"></i><b>6</b> Building Models for Interpretation</a>
<ul>
<li class="chapter" data-level="6.1" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#model-building"><i class="fa fa-check"></i><b>6.1</b> Model Building</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#overview"><i class="fa fa-check"></i><b>6.1.1</b> Overview</a></li>
<li class="chapter" data-level="6.1.2" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#modeling-for-interpretation"><i class="fa fa-check"></i><b>6.1.2</b> Modeling for Interpretation</a></li>
<li class="chapter" data-level="6.1.3" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#sat-scores-dataset"><i class="fa fa-check"></i><b>6.1.3</b> SAT Scores Dataset</a></li>
<li class="chapter" data-level="6.1.4" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#developing-a-research-question"><i class="fa fa-check"></i><b>6.1.4</b> Developing a Research Question</a></li>
<li class="chapter" data-level="6.1.5" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#teacher-salary-and-sat-score"><i class="fa fa-check"></i><b>6.1.5</b> Teacher Salary and SAT score</a></li>
<li class="chapter" data-level="6.1.6" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#a-further-investigation"><i class="fa fa-check"></i><b>6.1.6</b> A Further Investigation</a></li>
<li class="chapter" data-level="6.1.7" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#add-student-to-teacher-ratio"><i class="fa fa-check"></i><b>6.1.7</b> Add Student-to-Teacher Ratio</a></li>
<li class="chapter" data-level="6.1.8" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#multicollinearity"><i class="fa fa-check"></i><b>6.1.8</b> Multicollinearity</a></li>
<li class="chapter" data-level="6.1.9" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#residual-plots-for-sat-3-variable-model"><i class="fa fa-check"></i><b>6.1.9</b> Residual Plots for SAT 3-variable Model</a></li>
<li class="chapter" data-level="6.1.10" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#model-with-linear-term-on-frac"><i class="fa fa-check"></i><b>6.1.10</b> Model with Linear Term on Frac</a></li>
<li class="chapter" data-level="6.1.11" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#interpretations-for-model-with-linear-terms"><i class="fa fa-check"></i><b>6.1.11</b> Interpretations for Model with Linear Terms</a></li>
<li class="chapter" data-level="6.1.12" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#model-with-quadratic-term-on-frac"><i class="fa fa-check"></i><b>6.1.12</b> Model with Quadratic Term on Frac</a></li>
<li class="chapter" data-level="6.1.13" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#interpretations-for-model-with-quadratic-terms"><i class="fa fa-check"></i><b>6.1.13</b> Interpretations for Model with Quadratic Terms</a></li>
<li class="chapter" data-level="6.1.14" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#plot-of-sat-and-frac"><i class="fa fa-check"></i><b>6.1.14</b> Plot of SAT and Frac</a></li>
<li class="chapter" data-level="6.1.15" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#sat-model-summary"><i class="fa fa-check"></i><b>6.1.15</b> SAT Model Summary</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#modeling-car-price"><i class="fa fa-check"></i><b>6.2</b> Modeling Car Price</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#model-for-price-of-2015-cars"><i class="fa fa-check"></i><b>6.2.1</b> Model for Price of 2015 Cars</a></li>
<li class="chapter" data-level="6.2.2" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#categorical-variables"><i class="fa fa-check"></i><b>6.2.2</b> Categorical Variables</a></li>
<li class="chapter" data-level="6.2.3" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#correlation-matrix"><i class="fa fa-check"></i><b>6.2.3</b> Correlation Matrix</a></li>
<li class="chapter" data-level="6.2.4" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#model-using-acceleration-time"><i class="fa fa-check"></i><b>6.2.4</b> Model Using Acceleration Time</a></li>
<li class="chapter" data-level="6.2.5" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#model-using-quarter-mile-time"><i class="fa fa-check"></i><b>6.2.5</b> Model Using Quarter Mile Time</a></li>
<li class="chapter" data-level="6.2.6" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#model-using-quarter-mile-time-and-acc.-time"><i class="fa fa-check"></i><b>6.2.6</b> Model Using Quarter Mile Time and Acc. Time</a></li>
<li class="chapter" data-level="6.2.7" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#problems-with-multicollinearity-in-modeling"><i class="fa fa-check"></i><b>6.2.7</b> Problems with Multicollinearity in Modeling</a></li>
<li class="chapter" data-level="6.2.8" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#impact-on-prediction"><i class="fa fa-check"></i><b>6.2.8</b> Impact on Prediction</a></li>
<li class="chapter" data-level="6.2.9" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#adding-weight-to-model"><i class="fa fa-check"></i><b>6.2.9</b> Adding Weight to Model</a></li>
<li class="chapter" data-level="6.2.10" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#add-interaction-term"><i class="fa fa-check"></i><b>6.2.10</b> Add Interaction Term?</a></li>
<li class="chapter" data-level="6.2.11" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#add-hwy-mpg"><i class="fa fa-check"></i><b>6.2.11</b> Add HWY MPG?</a></li>
<li class="chapter" data-level="6.2.12" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#categorical-variables-to-consider"><i class="fa fa-check"></i><b>6.2.12</b> Categorical Variables to Consider</a></li>
<li class="chapter" data-level="6.2.13" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#model-with-qtrmile-weight-and-drive"><i class="fa fa-check"></i><b>6.2.13</b> Model with QtrMile, Weight, and Drive</a></li>
<li class="chapter" data-level="6.2.14" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#add-size"><i class="fa fa-check"></i><b>6.2.14</b> Add Size</a></li>
<li class="chapter" data-level="6.2.15" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#check-of-model-assumptions"><i class="fa fa-check"></i><b>6.2.15</b> Check of Model Assumptions</a></li>
<li class="chapter" data-level="6.2.16" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#residual-by-predictor-plots"><i class="fa fa-check"></i><b>6.2.16</b> Residual by Predictor Plots</a></li>
<li class="chapter" data-level="6.2.17" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#coefficients-and-exponentiation"><i class="fa fa-check"></i><b>6.2.17</b> Coefficients and Exponentiation</a></li>
<li class="chapter" data-level="6.2.18" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#interpretation-of-coefficients"><i class="fa fa-check"></i><b>6.2.18</b> Interpretation of Coefficients</a></li>
<li class="chapter" data-level="6.2.19" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#adjusted-r2-aic-bic"><i class="fa fa-check"></i><b>6.2.19</b> Adjusted <span class="math inline">\(R^2\)</span>, AIC, BIC</a></li>
<li class="chapter" data-level="6.2.20" data-path="building-models-for-interpretation.html"><a href="building-models-for-interpretation.html#model-building-summary"><i class="fa fa-check"></i><b>6.2.20</b> Model Building Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="predictive-modeling.html"><a href="predictive-modeling.html"><i class="fa fa-check"></i><b>7</b> Predictive Modeling</a></li>
<li class="chapter" data-level="8" data-path="classification-and-logistic-regression.html"><a href="classification-and-logistic-regression.html"><i class="fa fa-check"></i><b>8</b> Classification and Logistic Regression</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Stat 255: Statistics for Data Science Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="building-models-for-interpretation" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Chapter 6</span> Building Models for Interpretation<a href="building-models-for-interpretation.html#building-models-for-interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>Learning Outcomes:</strong></p>
<ol style="list-style-type: decimal">
<li>Explain the differences in the ways we construct statistical models when we are focused primarily on interpretation.<br />
</li>
<li>Describe the ways that multicollinearity influences the interpretability of regression models.<br />
</li>
<li>Recognize situations where confounding and Simpson’s paradox might influence conclusions we draw from a model, and make appropriate interpretations in these situations.<br />
</li>
<li>Evaluate the appropriateness of models using plots of residuals vs explanatory variables.<br />
</li>
<li>Recognize when it is appropriate to use polynomials or other nonlinear functions in a statistical model, and interpret corresponding estimates of regression coefficients.<br />
</li>
<li>Decide which variables to include in a statistical model, and justify your decision.</li>
</ol>
<div id="model-building" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Model Building<a href="building-models-for-interpretation.html#model-building" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="overview" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Overview<a href="building-models-for-interpretation.html#overview" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>So far, we’ve dealt with models with 2 or fewer variables. Some real questions require accounting for more than two variables. In these situations, we’ll need to develop a model that is complex enough to capture the important aspects of the mechanism we’re modeling, but also simple enough for us to be able to explain and interpret. We’ll need to decide how many variables to include in the model, and whether to use transformations, or to include interaction terms.</p>
<p>We’ll examine strategies for modeling in two different contexts. In this chapter, we’ll focus on building models for situations when we want to make interpretations and draw conclusions about relationships between variables. In Chapter 7, we focus on modeling solely for the purpose of prediction, when we are not interested in making interpretations or conclusions about relationships between variables.</p>
</div>
<div id="modeling-for-interpretation" class="section level3 hasAnchor" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> Modeling for Interpretation<a href="building-models-for-interpretation.html#modeling-for-interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When building a model for the purpose of interpretation, we are typically interested in investigating a research question pertaining to relationships between explanatory and response variables. We’ll need to think about things like:</p>
<ul>
<li>which explanatory variables should we include in the model, and how many?<br />
</li>
<li>should we include any interaction terms?<br />
</li>
<li>should we use any nonlinear terms?<br />
</li>
<li>should we use a transformation of the response variable?</li>
</ul>
<p>We’ll go through a couple example to see how we can address these questions in building a model.</p>
<p>Keep in mind, there is no single correct model, but there are common characteristics of a good model. While two statisticians might use different models for a given set of data, they will hopefully lead to reasonably similar conclusions if constructed carefully.</p>
</div>
<div id="sat-scores-dataset" class="section level3 hasAnchor" number="6.1.3">
<h3><span class="header-section-number">6.1.3</span> SAT Scores Dataset<a href="building-models-for-interpretation.html#sat-scores-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ll now look at a dataset containing education data on all 50 states. It includes the following variables.</p>
<p><code>state</code> - a factor with names of each state</p>
<p><code>expend</code> - expenditure per pupil in average daily attendance in public elementary and secondary schools, 1994-95 (in thousands of US dollars)</p>
<p><code>ratio</code> - average pupil/teacher ratio in public elementary and secondary schools, Fall 1994</p>
<p><code>salary</code> - estimated average annual salary of teachers in public elementary and secondary schools, 1994-95 (in thousands of US dollars)</p>
<p><code>frac</code> - percentage of all eligible students taking the SAT, 1994-95</p>
<p><code>sat</code> - average total SAT score, 1994-95</p>
<p><code>region</code> - region of the country</p>
<div class="sourceCode" id="cb617"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb617-1"><a href="building-models-for-interpretation.html#cb617-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaicData)</span>
<span id="cb617-2"><a href="building-models-for-interpretation.html#cb617-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(SAT)</span>
<span id="cb617-3"><a href="building-models-for-interpretation.html#cb617-3" aria-hidden="true" tabindex="-1"></a>SAT <span class="ot">&lt;-</span> SAT <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(verbal, math))</span>
<span id="cb617-4"><a href="building-models-for-interpretation.html#cb617-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Lock5Data)</span>
<span id="cb617-5"><a href="building-models-for-interpretation.html#cb617-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;USStates&quot;</span>)</span>
<span id="cb617-6"><a href="building-models-for-interpretation.html#cb617-6" aria-hidden="true" tabindex="-1"></a>SAT <span class="ot">&lt;-</span> SAT <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(USStates <span class="sc">%&gt;%</span> <span class="fu">select</span>(State, Region), <span class="at">by=</span><span class="fu">c</span>(<span class="st">&quot;state&quot;</span><span class="ot">=</span><span class="st">&quot;State&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">region =</span> Region)</span></code></pre></div>
<div class="sourceCode" id="cb618"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb618-1"><a href="building-models-for-interpretation.html#cb618-1" aria-hidden="true" tabindex="-1"></a>SAT</span></code></pre></div>
<pre><code>##             state expend ratio salary frac  sat region
## 1         Alabama  4.405  17.2 31.144    8 1029      S
## 2          Alaska  8.963  17.6 47.951   47  934      W
## 3         Arizona  4.778  19.3 32.175   27  944      W
## 4        Arkansas  4.459  17.1 28.934    6 1005      S
## 5      California  4.992  24.0 41.078   45  902      W
## 6        Colorado  5.443  18.4 34.571   29  980      W
## 7     Connecticut  8.817  14.4 50.045   81  908     NE
## 8        Delaware  7.030  16.6 39.076   68  897     NE
## 9         Florida  5.718  19.1 32.588   48  889      S
## 10        Georgia  5.193  16.3 32.291   65  854      S
## 11         Hawaii  6.078  17.9 38.518   57  889      W
## 12          Idaho  4.210  19.1 29.783   15  979      W
## 13       Illinois  6.136  17.3 39.431   13 1048     MW
## 14        Indiana  5.826  17.5 36.785   58  882     MW
## 15           Iowa  5.483  15.8 31.511    5 1099     MW
## 16         Kansas  5.817  15.1 34.652    9 1060     MW
## 17       Kentucky  5.217  17.0 32.257   11  999     MW
## 18      Louisiana  4.761  16.8 26.461    9 1021      S
## 19          Maine  6.428  13.8 31.972   68  896     NE
## 20       Maryland  7.245  17.0 40.661   64  909     NE
## 21  Massachusetts  7.287  14.8 40.795   80  907     NE
## 22       Michigan  6.994  20.1 41.895   11 1033     MW
## 23      Minnesota  6.000  17.5 35.948    9 1085     MW
## 24    Mississippi  4.080  17.5 26.818    4 1036      S
## 25       Missouri  5.383  15.5 31.189    9 1045     MW
## 26        Montana  5.692  16.3 28.785   21 1009      W
## 27       Nebraska  5.935  14.5 30.922    9 1050     MW
## 28         Nevada  5.160  18.7 34.836   30  917      W
## 29  New Hampshire  5.859  15.6 34.720   70  935     NE
## 30     New Jersey  9.774  13.8 46.087   70  898     NE
## 31     New Mexico  4.586  17.2 28.493   11 1015      W
## 32       New York  9.623  15.2 47.612   74  892     NE
## 33 North Carolina  5.077  16.2 30.793   60  865      S
## 34   North Dakota  4.775  15.3 26.327    5 1107     MW
## 35           Ohio  6.162  16.6 36.802   23  975     MW
## 36       Oklahoma  4.845  15.5 28.172    9 1027      S
## 37         Oregon  6.436  19.9 38.555   51  947      W
## 38   Pennsylvania  7.109  17.1 44.510   70  880     NE
## 39   Rhode Island  7.469  14.7 40.729   70  888     NE
## 40 South Carolina  4.797  16.4 30.279   58  844      S
## 41   South Dakota  4.775  14.4 25.994    5 1068     MW
## 42      Tennessee  4.388  18.6 32.477   12 1040      S
## 43          Texas  5.222  15.7 31.223   47  893      S
## 44           Utah  3.656  24.3 29.082    4 1076      W
## 45        Vermont  6.750  13.8 35.406   68  901     NE
## 46       Virginia  5.327  14.6 33.987   65  896      S
## 47     Washington  5.906  20.2 36.151   48  937      W
## 48  West Virginia  6.107  14.8 31.944   17  932      S
## 49      Wisconsin  6.930  15.9 37.746    9 1073     MW
## 50        Wyoming  6.160  14.9 31.285   10 1001      W</code></pre>
<p>Note that the dataset is quite old (from 1994-95), so the financial information may be out of date. Nevertheless, it is useful for exploring relationships between SAT scores and other variables.</p>
</div>
<div id="developing-a-research-question" class="section level3 hasAnchor" number="6.1.4">
<h3><span class="header-section-number">6.1.4</span> Developing a Research Question<a href="building-models-for-interpretation.html#developing-a-research-question" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A good statistical research question should be one that has practical implications that people would care about. It should be complex enough to be worth investigating. If the answer is obvious, then there would be no need to use statistics, or scientific reasoning in general.</p>
<p>For the SAT score dataset, we’ll focus on the question:</p>
<p><strong>Do students in states that prioritize education spending achieve better SAT scores?</strong></p>
<p>While this may seem like a straightforward question, we’ll see that answering it properly requires careful thought and analysis.</p>
</div>
<div id="teacher-salary-and-sat-score" class="section level3 hasAnchor" number="6.1.5">
<h3><span class="header-section-number">6.1.5</span> Teacher Salary and SAT score<a href="building-models-for-interpretation.html#teacher-salary-and-sat-score" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One way to measure a state’s investment in education is in how much it pays its teachers. The plot displays average SAT score against average teacher salary for all 50 US states.</p>
<div class="sourceCode" id="cb620"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb620-1"><a href="building-models-for-interpretation.html#cb620-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>SAT, <span class="fu">aes</span>(<span class="at">y=</span>sat, <span class="at">x=</span>salary)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb620-2"><a href="building-models-for-interpretation.html#cb620-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb620-3"><a href="building-models-for-interpretation.html#cb620-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Average SAT score vs Average Teacher Salary&quot;</span>) <span class="sc">+</span> </span>
<span id="cb620-4"><a href="building-models-for-interpretation.html#cb620-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Average Teacher Salary in Thousands&quot;</span>) </span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-472-1.png" width="576" /></p>
<p>Fitting a simple linear regression model to the data, we obtain the following:</p>
<div class="sourceCode" id="cb621"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb621-1"><a href="building-models-for-interpretation.html#cb621-1" aria-hidden="true" tabindex="-1"></a>SAT_M1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>SAT, sat<span class="sc">~</span>salary)</span>
<span id="cb621-2"><a href="building-models-for-interpretation.html#cb621-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SAT_M1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sat ~ salary, data = SAT)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -147.125  -45.354    4.073   42.193  125.279 
## 
## Coefficients:
##             Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept) 1158.859     57.659  20.098 &lt; 0.0000000000000002 ***
## salary        -5.540      1.632  -3.394              0.00139 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 67.89 on 48 degrees of freedom
## Multiple R-squared:  0.1935, Adjusted R-squared:  0.1767 
## F-statistic: 11.52 on 1 and 48 DF,  p-value: 0.001391</code></pre>
<p>On average, SAT score is expected to decrease by about 5.5 points for each additional one thousand dollars in average teacher salary in the state. The low p-value suggests a relationship like this is unlikely to occur by chance, though the practical importance of a 5-point decrease in SAT score (out of 1600) seems minimal. Furthermore, only 19% of the total variation in SAT score is explained by teaching salary. Nevertheless, a person looking to argue against raising teacher salaries might use the negative estimate and low p-value as a justification for their position.</p>
</div>
<div id="a-further-investigation" class="section level3 hasAnchor" number="6.1.6">
<h3><span class="header-section-number">6.1.6</span> A Further Investigation<a href="building-models-for-interpretation.html#a-further-investigation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Notice that there are large discrepancies in the <code>frac</code> variable, representing the percentage of students taking the SAT. In Connecticut, 81% of high school students took the SAT, compared to only 6% in Arkansas.</p>
<p>Let’s break the data down by the percentage of students who take the SAT. We’ll (somewhat arbitrarily), divide the states into</p>
<p>Low = 0%-22%<br />
Medium = 22-49%<br />
High = 49-81%</p>
<div class="sourceCode" id="cb623"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb623-1"><a href="building-models-for-interpretation.html#cb623-1" aria-hidden="true" tabindex="-1"></a>SAT <span class="ot">&lt;-</span> <span class="fu">mutate</span>(SAT, <span class="at">fracgrp =</span> <span class="fu">cut</span>(frac, </span>
<span id="cb623-2"><a href="building-models-for-interpretation.html#cb623-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">22</span>, <span class="dv">49</span>, <span class="dv">81</span>), </span>
<span id="cb623-3"><a href="building-models-for-interpretation.html#cb623-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;low&quot;</span>, <span class="st">&quot;medium&quot;</span>, <span class="st">&quot;high&quot;</span>)))</span></code></pre></div>
<p>Plotting SAT score against average teacher salary in each state, we see that the picture changes.</p>
<div class="sourceCode" id="cb624"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb624-1"><a href="building-models-for-interpretation.html#cb624-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>SAT, <span class="fu">aes</span>( <span class="at">y=</span>sat, <span class="at">x=</span>salary )) <span class="sc">+</span><span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="at">facets =</span> <span class="sc">~</span>fracgrp) <span class="sc">+</span></span>
<span id="cb624-2"><a href="building-models-for-interpretation.html#cb624-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Average Teacher Salary in Thousands&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-475-1.png" width="864" /></p>
<p>There appears to be a slight positive relationship between teacher salary and SAT score in each state.</p>
<p>While breaking up the data into these three groups helps us visualize, we’ll simply add the <code>frac</code> variable to the model as a quantitative variable, rather than breaking it into these arbitrary categories.</p>
<div class="sourceCode" id="cb625"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb625-1"><a href="building-models-for-interpretation.html#cb625-1" aria-hidden="true" tabindex="-1"></a>SAT_M2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>SAT, sat<span class="sc">~</span>salary<span class="sc">+</span>frac)</span>
<span id="cb625-2"><a href="building-models-for-interpretation.html#cb625-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SAT_M2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sat ~ salary + frac, data = SAT)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -78.313 -26.731   3.168  18.951  75.590 
## 
## Coefficients:
##             Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept) 987.9005    31.8775  30.991 &lt; 0.0000000000000002 ***
## salary        2.1804     1.0291   2.119               0.0394 *  
## frac         -2.7787     0.2285 -12.163   0.0000000000000004 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 33.69 on 47 degrees of freedom
## Multiple R-squared:  0.8056, Adjusted R-squared:  0.7973 
## F-statistic: 97.36 on 2 and 47 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>For each one thousand dollar increase in average teacher salary, a state’s average SAT score is expected to increase by 2.18 points, assuming percentage of students taking the test is the same.</p>
<p>For each one percent increase in percentage of students taking the SAT, a state’s average score is expected to decrease by 2.78 points, assuming average teacher salary is the same.</p>
<p>Both of these estimates are associated with low p-values. While the effect of a 2 point increase per $1,000 in average teacher salary might seem small, the ~3 point decrease for each percentage point of students taking the exam is quite meaningful. According to the model, if the percentage of students taking the SAT is 10 percentage points higher than another, and the states pay their teachers the same, then the state with more people taking the exam is expected to have an average score almost 30 points lower.</p>
<p>Adding percentage of students taking the exam increased the <span class="math inline">\(R^2\)</span> value substantially.</p>
<p>We see that the relationship between SAT score and salary appears to reverse when we account for percentage of students taking the test. States with low percentages of people taking the SAT tend to get higher scores, as the people taking the test tend to be those who are best prepared and have strong incentive for taking it, perhaps because they are trying to get into an elite college. At the same time, states that pay their teachers more tend to have higher percentages of people taking the SAT. This may be because states that prioritize education are more likely to cover the cost of students taking the test, or even to require it. It may also be that many of the states that require the SAT are coastal states, where cost of living, and thus teacher salaries, tend to be higher in general. Thus, it appears initially that teacher salaries are negatively correlated with SAT scores, but after accounting for percentage taking the test, the trend reverses. Situations where an apparent trend disappears or reverses after accounting for another variable are called <strong>Simpson’s Paradox.</strong></p>
</div>
<div id="add-student-to-teacher-ratio" class="section level3 hasAnchor" number="6.1.7">
<h3><span class="header-section-number">6.1.7</span> Add Student-to-Teacher Ratio<a href="building-models-for-interpretation.html#add-student-to-teacher-ratio" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s see what other possible explanatory variables we might want to add to the model. Keep in mind that our goal is to understand the relationship between teacher salary and SAT scores in the state, so we should only use variables that help us understand this relationship.<br />
In addition to teacher salaries, student-to-teacher ratio might be an indication of a state’s investment in education. We’ll add student-to-teacher ratio to the model and explore whether there is evidence that hiring enough teachers to keep student-to-teacher ratio low has a benefit, in terms of SAT score.</p>
<div class="sourceCode" id="cb627"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb627-1"><a href="building-models-for-interpretation.html#cb627-1" aria-hidden="true" tabindex="-1"></a>SAT_M3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>SAT, sat<span class="sc">~</span>salary<span class="sc">+</span>frac<span class="sc">+</span>ratio)</span>
<span id="cb627-2"><a href="building-models-for-interpretation.html#cb627-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SAT_M3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sat ~ salary + frac + ratio, data = SAT)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -89.244 -21.485  -0.798  17.685  68.262 
## 
## Coefficients:
##              Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept) 1057.8982    44.3287  23.865 &lt;0.0000000000000002 ***
## salary         2.5525     1.0045   2.541              0.0145 *  
## frac          -2.9134     0.2282 -12.764 &lt;0.0000000000000002 ***
## ratio         -4.6394     2.1215  -2.187              0.0339 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 32.41 on 46 degrees of freedom
## Multiple R-squared:  0.8239, Adjusted R-squared:  0.8124 
## F-statistic: 71.72 on 3 and 46 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>We see that student to teacher ratio is negatively associated with SAT score, with an expected drop of about 4.6 points in average SAT score for each additional student per teacher, assuming average teacher salary and percentage of students taking the exam are held constant. This suggests that states should try to keep student to teacher ratios low. We see teacher salary remains positively correlated with SAT score and percentage taking the test remains negatively correlated, after accounting for student to teacher ratio.</p>
</div>
<div id="multicollinearity" class="section level3 hasAnchor" number="6.1.8">
<h3><span class="header-section-number">6.1.8</span> Multicollinearity<a href="building-models-for-interpretation.html#multicollinearity" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Next, let’s add the variable <code>expend</code>, which measures the state’s expenditure per pupil.</p>
<div class="sourceCode" id="cb629"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb629-1"><a href="building-models-for-interpretation.html#cb629-1" aria-hidden="true" tabindex="-1"></a>SAT_M4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>SAT, sat<span class="sc">~</span>salary<span class="sc">+</span>frac<span class="sc">+</span>ratio<span class="sc">+</span>expend)</span>
<span id="cb629-2"><a href="building-models-for-interpretation.html#cb629-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SAT_M4)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sat ~ salary + frac + ratio + expend, data = SAT)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -90.531 -20.855  -1.746  15.979  66.571 
## 
## Coefficients:
##              Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept) 1045.9715    52.8698  19.784 &lt; 0.0000000000000002 ***
## salary         1.6379     2.3872   0.686                0.496    
## frac          -2.9045     0.2313 -12.559 0.000000000000000261 ***
## ratio         -3.6242     3.2154  -1.127                0.266    
## expend         4.4626    10.5465   0.423                0.674    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 32.7 on 45 degrees of freedom
## Multiple R-squared:  0.8246, Adjusted R-squared:  0.809 
## F-statistic: 52.88 on 4 and 45 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>It may be surprising to see that after accounting for expenditure per student, teacher salary is still positively correlated with SAT score, but that the p-value associated with teacher salary is quite large. Likewise, while student-to-teacher ratio is still negatively associated, it too has a large p-value. Also notice that <span class="math inline">\(R^2\)</span> barely increased when accounting for total expenditures.</p>
<p>This happens because expenditures are highly correlated with teacher salary. States that pay their teacher more also spend more on education per pupil. The scatterplot matrix below shows a strong correlation of 0.87 between teacher salary and expenditures.</p>
<div class="sourceCode" id="cb631"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb631-1"><a href="building-models-for-interpretation.html#cb631-1" aria-hidden="true" tabindex="-1"></a>SAT_Num <span class="ot">&lt;-</span> <span class="fu">select_if</span>(SAT, is.numeric)</span>
<span id="cb631-2"><a href="building-models-for-interpretation.html#cb631-2" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">cor</span>(SAT_Num, <span class="at">use =</span> <span class="st">&quot;pairwise.complete.obs&quot;</span>)</span>
<span id="cb631-3"><a href="building-models-for-interpretation.html#cb631-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(C,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##        expend ratio salary  frac   sat
## expend   1.00 -0.37   0.87  0.59 -0.38
## ratio   -0.37  1.00   0.00 -0.21  0.08
## salary   0.87  0.00   1.00  0.62 -0.44
## frac     0.59 -0.21   0.62  1.00 -0.89
## sat     -0.38  0.08  -0.44 -0.89  1.00</code></pre>
<div class="sourceCode" id="cb633"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb633-1"><a href="building-models-for-interpretation.html#cb633-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb633-2"><a href="building-models-for-interpretation.html#cb633-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(C)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-480-1.png" width="672" /></p>
<p>Because these variables are highly correlated, it doesn’t make sense to talk about the effect of increasing teacher salary, while holding expenditure constant, or vice-versa. Notice the standard error on the <code>salary</code> line in model <code>SAT_M4</code> (which includes expenditures) is more than twice as high as in <code>SAT_M3</code>, which did not. This happens because the model is not able to separate the effect of salary from the effect of expenditure, and thus becomes very uncertain of the effect of both, resulting in high standard errors. In addition to reducing the t-statistic, and increasing the p-value, this leads to much wider and less informative confidence intervals associated with the effect of teacher salary.</p>
<p><strong>Confidence intervals for model involving teacher salary, percentage taking the test, and student-to-teacher ratio.</strong></p>
<div class="sourceCode" id="cb634"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb634-1"><a href="building-models-for-interpretation.html#cb634-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(SAT_M3)</span></code></pre></div>
<pre><code>##                   2.5 %       97.5 %
## (Intercept) 968.6691802 1147.1271438
## salary        0.5304797    4.5744605
## frac         -3.3727807   -2.4539197
## ratio        -8.9098147   -0.3690414</code></pre>
<p><strong>Confidence intervals for model with above variables plus expenditure.</strong></p>
<div class="sourceCode" id="cb636"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb636-1"><a href="building-models-for-interpretation.html#cb636-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(SAT_M4)</span></code></pre></div>
<pre><code>##                  2.5 %      97.5 %
## (Intercept) 939.486374 1152.456698
## salary       -3.170247    6.446081
## frac         -3.370262   -2.438699
## ratio       -10.100417    2.851952
## expend      -16.779204   25.704393</code></pre>
<p>Models with highly correlated explanatory variables suffer from <strong>multicollinearity</strong>, which increases standard errors, making the effect of variables harder to discern. When we have explanatory variables that are highly correlated (usually with correlation greater than 0.8), we should pick out just one to include in the model. In this case, we’ll stick with teacher salary.</p>
</div>
<div id="residual-plots-for-sat-3-variable-model" class="section level3 hasAnchor" number="6.1.9">
<h3><span class="header-section-number">6.1.9</span> Residual Plots for SAT 3-variable Model<a href="building-models-for-interpretation.html#residual-plots-for-sat-3-variable-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s return to the model with salary, ratio, and fraction taking test. We use residual plots to assess model assumptions.</p>
<div class="sourceCode" id="cb638"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb638-1"><a href="building-models-for-interpretation.html#cb638-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(SAT_M3<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">y=</span>SAT_M3<span class="sc">$</span>residuals, <span class="at">x=</span>SAT_M3<span class="sc">$</span>fitted.values)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Residual Plot&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted Values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb638-2"><a href="building-models-for-interpretation.html#cb638-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(SAT_M3<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">x=</span>SAT_M3<span class="sc">$</span>residuals)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Histogram of Residuals&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Residual&quot;</span>)</span>
<span id="cb638-3"><a href="building-models-for-interpretation.html#cb638-3" aria-hidden="true" tabindex="-1"></a>P3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(SAT_M3<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">scale</span>(SAT_M3<span class="sc">$</span>residuals))) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Normal Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residual Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;QQ Plot&quot;</span>)</span>
<span id="cb638-4"><a href="building-models-for-interpretation.html#cb638-4" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, P3, <span class="at">ncol=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-483-1.png" width="864" /></p>
<p>There is some sign of a quadratic trend in the residual plot, creating concern about the linearity assumption.</p>
<p>We can also plot our residuals against the explanatory variables to see whether the model is properly accounting for relationships involving each variable. If we see nonlinear trends, we should consider adding a nonlinear function of that explanatory variable.</p>
<div class="sourceCode" id="cb639"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb639-1"><a href="building-models-for-interpretation.html#cb639-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(SAT_M3<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">y=</span>SAT_M3<span class="sc">$</span>residuals, <span class="at">x=</span>SAT_M3<span class="sc">$</span>model<span class="sc">$</span>salary)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Residual by Predictor Plot&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Salary&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>) </span>
<span id="cb639-2"><a href="building-models-for-interpretation.html#cb639-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(SAT_M3<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">y=</span>SAT_M3<span class="sc">$</span>residuals, <span class="at">x=</span>SAT_M3<span class="sc">$</span>model<span class="sc">$</span>frac)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Residual by Predictor Plot&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Fraction Taking Test&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb639-3"><a href="building-models-for-interpretation.html#cb639-3" aria-hidden="true" tabindex="-1"></a>P3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(SAT_M3<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">y=</span>SAT_M3<span class="sc">$</span>residuals, <span class="at">x=</span>SAT_M3<span class="sc">$</span>model<span class="sc">$</span>ratio)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Residual by Predictor Plot&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Student to Teach Ratio&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb639-4"><a href="building-models-for-interpretation.html#cb639-4" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, P3, <span class="at">ncol=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-484-1.png" width="864" /></p>
<p>There is also a quadratic trend in the plot involving the fraction variable. We might account for this by adding a quadratic term for <code>frac</code> to the model.</p>
<div class="sourceCode" id="cb640"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb640-1"><a href="building-models-for-interpretation.html#cb640-1" aria-hidden="true" tabindex="-1"></a>SAT_M5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>SAT, sat<span class="sc">~</span>salary<span class="sc">+</span>frac<span class="sc">+</span><span class="fu">I</span>(frac<span class="sc">^</span><span class="dv">2</span>)<span class="sc">+</span>ratio )</span>
<span id="cb640-2"><a href="building-models-for-interpretation.html#cb640-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SAT_M5)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sat ~ salary + frac + I(frac^2) + ratio, data = SAT)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -66.09 -15.20  -4.64  15.06  52.77 
## 
## Coefficients:
##               Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept) 1039.21242   36.28206  28.643 &lt; 0.0000000000000002 ***
## salary         1.80708    0.83150   2.173               0.0351 *  
## frac          -6.64001    0.77668  -8.549      0.0000000000555 ***
## I(frac^2)      0.05065    0.01025   4.942      0.0000111676728 ***
## ratio         -0.04058    1.96174  -0.021               0.9836    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 26.38 on 45 degrees of freedom
## Multiple R-squared:  0.8858, Adjusted R-squared:  0.8757 
## F-statistic: 87.28 on 4 and 45 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<div class="sourceCode" id="cb642"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb642-1"><a href="building-models-for-interpretation.html#cb642-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(SAT_M5<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">y=</span>SAT_M5<span class="sc">$</span>residuals, <span class="at">x=</span>SAT_M5<span class="sc">$</span>fitted.values)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Residual Plot&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted Values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb642-2"><a href="building-models-for-interpretation.html#cb642-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(SAT_M5<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">x=</span>SAT_M5<span class="sc">$</span>residuals)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Histogram of Residuals&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Residual&quot;</span>)</span>
<span id="cb642-3"><a href="building-models-for-interpretation.html#cb642-3" aria-hidden="true" tabindex="-1"></a>P3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(SAT_M5<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">scale</span>(SAT_M5<span class="sc">$</span>residuals))) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Normal Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residual Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;QQ Plot&quot;</span>)</span>
<span id="cb642-4"><a href="building-models-for-interpretation.html#cb642-4" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, P3, <span class="at">ncol=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-486-1.png" width="864" /></p>
</div>
<div id="model-with-linear-term-on-frac" class="section level3 hasAnchor" number="6.1.10">
<h3><span class="header-section-number">6.1.10</span> Model with Linear Term on Frac<a href="building-models-for-interpretation.html#model-with-linear-term-on-frac" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb643"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb643-1"><a href="building-models-for-interpretation.html#cb643-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SAT_M3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sat ~ salary + frac + ratio, data = SAT)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -89.244 -21.485  -0.798  17.685  68.262 
## 
## Coefficients:
##              Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept) 1057.8982    44.3287  23.865 &lt;0.0000000000000002 ***
## salary         2.5525     1.0045   2.541              0.0145 *  
## frac          -2.9134     0.2282 -12.764 &lt;0.0000000000000002 ***
## ratio         -4.6394     2.1215  -2.187              0.0339 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 32.41 on 46 degrees of freedom
## Multiple R-squared:  0.8239, Adjusted R-squared:  0.8124 
## F-statistic: 71.72 on 3 and 46 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
<div id="interpretations-for-model-with-linear-terms" class="section level3 hasAnchor" number="6.1.11">
<h3><span class="header-section-number">6.1.11</span> Interpretations for Model with Linear Terms<a href="building-models-for-interpretation.html#interpretations-for-model-with-linear-terms" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On average, a $1,000 dollar increase in average teacher salary is associated with a 2.5 point increase in average SAT score assuming fraction of students taking the SAT, and student to teacher ratio are held constant.</p>
<p>On average, a 1% increase in percentage of students taking the SAT is associated with a 2.9 point decrease in average SAT score assuming average teacher salary, and student to teacher ratio are held constant.</p>
<p>On average, a 1 student per teacher increase in student to teacher ratio is associated with a 4.6 point from in average SAT score, assuming average teacher salary, and percentage of students taking the SAT are held constant.</p>
</div>
<div id="model-with-quadratic-term-on-frac" class="section level3 hasAnchor" number="6.1.12">
<h3><span class="header-section-number">6.1.12</span> Model with Quadratic Term on Frac<a href="building-models-for-interpretation.html#model-with-quadratic-term-on-frac" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb645"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb645-1"><a href="building-models-for-interpretation.html#cb645-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SAT_M5)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sat ~ salary + frac + I(frac^2) + ratio, data = SAT)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -66.09 -15.20  -4.64  15.06  52.77 
## 
## Coefficients:
##               Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept) 1039.21242   36.28206  28.643 &lt; 0.0000000000000002 ***
## salary         1.80708    0.83150   2.173               0.0351 *  
## frac          -6.64001    0.77668  -8.549      0.0000000000555 ***
## I(frac^2)      0.05065    0.01025   4.942      0.0000111676728 ***
## ratio         -0.04058    1.96174  -0.021               0.9836    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 26.38 on 45 degrees of freedom
## Multiple R-squared:  0.8858, Adjusted R-squared:  0.8757 
## F-statistic: 87.28 on 4 and 45 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
<div id="interpretations-for-model-with-quadratic-terms" class="section level3 hasAnchor" number="6.1.13">
<h3><span class="header-section-number">6.1.13</span> Interpretations for Model with Quadratic Terms<a href="building-models-for-interpretation.html#interpretations-for-model-with-quadratic-terms" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On average, a $1,000 dollar increase in average teacher salary is associated with a 1.8 point increase in average SAT score assuming fraction of students taking the SAT, and student to teacher ratio are held constant.</p>
<p>On average, a 1 student per teacher increase in student to teacher ratio is associated with a 0.05 point from in average SAT score, assuming average teacher salary, and percentage of students taking the SAT are held constant.</p>
<p>We cannot give a clear interpretation of the fraction variable, since it occurs in both linear and quadratic terms. In fact, the vertex of the parabola given by <span class="math inline">\(y=-6.64x + 0.05x^2\)</span> occurs at <span class="math inline">\(x=\frac{6.64}{2(0.05)}\approx 66\)</span>. So the model estimates that SAT score decreases in a quadratic fashion with respect to fraction taking the test, until that fraction reaches 66 percent of student, then is expected to increase.</p>
</div>
<div id="plot-of-sat-and-frac" class="section level3 hasAnchor" number="6.1.14">
<h3><span class="header-section-number">6.1.14</span> Plot of SAT and Frac<a href="building-models-for-interpretation.html#plot-of-sat-and-frac" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb647"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb647-1"><a href="building-models-for-interpretation.html#cb647-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>SAT, <span class="fu">aes</span>(<span class="at">x=</span>frac, <span class="at">y=</span>sat)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">se=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-489-1.png" width="672" /></p>
<p>We do see some possible quadratic trend, but we should be really careful about extrapolation.</p>
</div>
<div id="sat-model-summary" class="section level3 hasAnchor" number="6.1.15">
<h3><span class="header-section-number">6.1.15</span> SAT Model Summary<a href="building-models-for-interpretation.html#sat-model-summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Modeling SAT scores based on teacher salary alone led to misleading results, due to Simpson’s Paradox. This is corrected by adding percentage of students taking the test to the model.</p></li>
<li><p>Modeling two highly correlated variables like average teacher salary and expenditure on education inflates the width of confidence intervals associated with both variables, preventing us from drawing meaningful conclusions about either variable. This issue is called <strong>multicollinearity</strong>.</p></li>
<li><p>Including a quadratic term on the proportion taking the test improves the model fit, and validity of model assumptions, but also makes the model harder to interpret. We need to use judgement when deciding whether or not to include quadratic or higher power terms.</p></li>
<li><p>There is no clear reason to expect an interaction between these variables, so we did not include an interaction effect in the model.</p></li>
</ul>
</div>
</div>
<div id="modeling-car-price" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Modeling Car Price<a href="building-models-for-interpretation.html#modeling-car-price" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="model-for-price-of-2015-cars" class="section level3 hasAnchor" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> Model for Price of 2015 Cars<a href="building-models-for-interpretation.html#model-for-price-of-2015-cars" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>What factors contribute to the price of a car?</p>
<p>We build a model for the price of a new 2015 car, in order to help us answer this question.</p>
<div class="sourceCode" id="cb648"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb648-1"><a href="building-models-for-interpretation.html#cb648-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Cars2015)</span>
<span id="cb648-2"><a href="building-models-for-interpretation.html#cb648-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(Cars2015)</span></code></pre></div>
<pre><code>## Rows: 110
## Columns: 20
## $ Make      &lt;fct&gt; Chevrolet, Hyundai, Kia, Mitsubishi, Nissan, Dodge, Chevrole…
## $ Model     &lt;fct&gt; Spark, Accent, Rio, Mirage, Versa Note, Dart, Cruze LS, 500L…
## $ Type      &lt;fct&gt; Hatchback, Hatchback, Sedan, Hatchback, Hatchback, Sedan, Se…
## $ LowPrice  &lt;dbl&gt; 12.270, 14.745, 13.990, 12.995, 14.180, 16.495, 16.170, 19.3…
## $ HighPrice &lt;dbl&gt; 25.560, 17.495, 18.290, 15.395, 17.960, 23.795, 25.660, 24.6…
## $ Drive     &lt;fct&gt; FWD, FWD, FWD, FWD, FWD, FWD, FWD, FWD, FWD, FWD, FWD, AWD, …
## $ CityMPG   &lt;int&gt; 30, 28, 28, 37, 31, 23, 24, 24, 28, 30, 27, 27, 25, 27, 30, …
## $ HwyMPG    &lt;int&gt; 39, 37, 36, 44, 40, 35, 36, 33, 38, 35, 33, 36, 36, 37, 39, …
## $ FuelCap   &lt;dbl&gt; 9.0, 11.4, 11.3, 9.2, 10.9, 14.2, 15.6, 13.1, 12.4, 11.1, 11…
## $ Length    &lt;int&gt; 145, 172, 172, 149, 164, 184, 181, 167, 179, 154, 156, 180, …
## $ Width     &lt;int&gt; 63, 67, 68, 66, 67, 72, 71, 70, 72, 67, 68, 69, 70, 68, 69, …
## $ Wheelbase &lt;int&gt; 94, 101, 101, 97, 102, 106, 106, 103, 104, 99, 98, 104, 104,…
## $ Height    &lt;int&gt; 61, 57, 57, 59, 61, 58, 58, 66, 58, 59, 58, 58, 57, 58, 59, …
## $ UTurn     &lt;int&gt; 34, 37, 37, 32, 37, 38, 38, 37, 39, 34, 35, 38, 37, 36, 37, …
## $ Weight    &lt;int&gt; 2345, 2550, 2575, 2085, 2470, 3260, 3140, 3330, 2990, 2385, …
## $ Acc030    &lt;dbl&gt; 4.4, 3.7, 3.5, 4.4, 4.0, 3.4, 3.7, 3.9, 3.4, 3.9, 3.9, 3.7, …
## $ Acc060    &lt;dbl&gt; 12.8, 10.3, 9.5, 12.1, 10.9, 9.3, 9.8, 9.5, 9.2, 10.8, 11.1,…
## $ QtrMile   &lt;dbl&gt; 19.4, 17.8, 17.3, 19.0, 18.2, 17.2, 17.6, 17.4, 17.1, 18.3, …
## $ PageNum   &lt;int&gt; 123, 148, 163, 188, 196, 128, 119, 131, 136, 216, 179, 205, …
## $ Size      &lt;fct&gt; Small, Small, Small, Small, Small, Small, Small, Small, Smal…</code></pre>
<div class="sourceCode" id="cb650"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb650-1"><a href="building-models-for-interpretation.html#cb650-1" aria-hidden="true" tabindex="-1"></a>Cars2015 <span class="ot">&lt;-</span> Cars2015 <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>HighPrice)</span></code></pre></div>
</div>
<div id="categorical-variables" class="section level3 hasAnchor" number="6.2.2">
<h3><span class="header-section-number">6.2.2</span> Categorical Variables<a href="building-models-for-interpretation.html#categorical-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb651"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb651-1"><a href="building-models-for-interpretation.html#cb651-1" aria-hidden="true" tabindex="-1"></a>Cars_Cat <span class="ot">&lt;-</span> <span class="fu">select_if</span>(Cars2015, is.factor)</span>
<span id="cb651-2"><a href="building-models-for-interpretation.html#cb651-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Cars_Cat)</span></code></pre></div>
<pre><code>##         Make            Model            Type    Drive          Size   
##  Chevrolet: 8   CTS        :  2   7Pass    :15   AWD:25   Large   :29  
##  Ford     : 7   2 Touring  :  1   Hatchback:11   FWD:63   Midsized:34  
##  Hyundai  : 7   200        :  1   Sedan    :46   RWD:22   Small   :47  
##  Toyoto   : 7   3 i Touring:  1   Sporty   :11                         
##  Audi     : 6   3 Series GT:  1   SUV      :18                         
##  Nissan   : 6   300        :  1   Wagon    : 9                         
##  (Other)  :69   (Other)    :103</code></pre>
</div>
<div id="correlation-matrix" class="section level3 hasAnchor" number="6.2.3">
<h3><span class="header-section-number">6.2.3</span> Correlation Matrix<a href="building-models-for-interpretation.html#correlation-matrix" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We examine the correlation matrix of quantitative variables.</p>
<div class="sourceCode" id="cb653"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb653-1"><a href="building-models-for-interpretation.html#cb653-1" aria-hidden="true" tabindex="-1"></a>Cars_Num <span class="ot">&lt;-</span> <span class="fu">select_if</span>(Cars2015, is.numeric)</span>
<span id="cb653-2"><a href="building-models-for-interpretation.html#cb653-2" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">cor</span>(Cars_Num, <span class="at">use =</span> <span class="st">&quot;pairwise.complete.obs&quot;</span>)</span>
<span id="cb653-3"><a href="building-models-for-interpretation.html#cb653-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(C,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##           LowPrice CityMPG HwyMPG FuelCap Length Width Wheelbase Height UTurn
## LowPrice      1.00   -0.65  -0.59    0.57   0.47  0.48      0.46   0.02  0.40
## CityMPG      -0.65    1.00   0.93   -0.77  -0.72 -0.78     -0.69  -0.39 -0.73
## HwyMPG       -0.59    0.93   1.00   -0.75  -0.64 -0.75     -0.64  -0.54 -0.68
## FuelCap       0.57   -0.77  -0.75    1.00   0.82  0.85      0.79   0.58  0.76
## Length        0.47   -0.72  -0.64    0.82   1.00  0.81      0.92   0.46  0.84
## Width         0.48   -0.78  -0.75    0.85   0.81  1.00      0.76   0.62  0.77
## Wheelbase     0.46   -0.69  -0.64    0.79   0.92  0.76      1.00   0.49  0.81
## Height        0.02   -0.39  -0.54    0.58   0.46  0.62      0.49   1.00  0.55
## UTurn         0.40   -0.73  -0.68    0.76   0.84  0.77      0.81   0.55  1.00
## Weight        0.55   -0.83  -0.84    0.91   0.82  0.91      0.81   0.71  0.80
## Acc030       -0.76    0.64   0.51   -0.47  -0.38 -0.41     -0.31   0.21 -0.36
## Acc060       -0.74    0.68   0.52   -0.49  -0.47 -0.46     -0.38   0.21 -0.41
## QtrMile      -0.76    0.65   0.49   -0.45  -0.42 -0.41     -0.35   0.25 -0.37
## PageNum      -0.23    0.28   0.15   -0.15  -0.23 -0.20     -0.24   0.06 -0.22
##           Weight Acc030 Acc060 QtrMile PageNum
## LowPrice    0.55  -0.76  -0.74   -0.76   -0.23
## CityMPG    -0.83   0.64   0.68    0.65    0.28
## HwyMPG     -0.84   0.51   0.52    0.49    0.15
## FuelCap     0.91  -0.47  -0.49   -0.45   -0.15
## Length      0.82  -0.38  -0.47   -0.42   -0.23
## Width       0.91  -0.41  -0.46   -0.41   -0.20
## Wheelbase   0.81  -0.31  -0.38   -0.35   -0.24
## Height      0.71   0.21   0.21    0.25    0.06
## UTurn       0.80  -0.36  -0.41   -0.37   -0.22
## Weight      1.00  -0.41  -0.43   -0.39   -0.20
## Acc030     -0.41   1.00   0.95    0.95    0.25
## Acc060     -0.43   0.95   1.00    0.99    0.26
## QtrMile    -0.39   0.95   0.99    1.00    0.26
## PageNum    -0.20   0.25   0.26    0.26    1.00</code></pre>
<div class="sourceCode" id="cb655"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb655-1"><a href="building-models-for-interpretation.html#cb655-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb655-2"><a href="building-models-for-interpretation.html#cb655-2" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">corrplot</span>(C)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-494-1.png" width="1152" /></p>
<p>We’ll examine what happens when we include two highy-correlated explanatory variables in the same model, for example:</p>
<p><code>Acc060</code> - time it takes to accelerate from 0 to 60 mph and<br />
<code>QtrMile</code> - time it takes to drive a quarter mile</p>
<div class="sourceCode" id="cb656"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb656-1"><a href="building-models-for-interpretation.html#cb656-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(Cars2015<span class="sc">$</span>Acc060, Cars2015<span class="sc">$</span>QtrMile)</span></code></pre></div>
<pre><code>## [1] 0.9916625</code></pre>
</div>
<div id="model-using-acceleration-time" class="section level3 smaller hasAnchor" number="6.2.4">
<h3><span class="header-section-number">6.2.4</span> Model Using Acceleration Time<a href="building-models-for-interpretation.html#model-using-acceleration-time" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb658"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb658-1"><a href="building-models-for-interpretation.html#cb658-1" aria-hidden="true" tabindex="-1"></a>Cars_M1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2015, <span class="fu">log</span>(LowPrice) <span class="sc">~</span> Acc060)</span>
<span id="cb658-2"><a href="building-models-for-interpretation.html#cb658-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Cars_M1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(LowPrice) ~ Acc060, data = Cars2015)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.84587 -0.19396  0.00908  0.18615  0.53350 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept)  5.13682    0.13021   39.45 &lt;0.0000000000000002 ***
## Acc060      -0.22064    0.01607  -13.73 &lt;0.0000000000000002 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.276 on 108 degrees of freedom
## Multiple R-squared:  0.6359, Adjusted R-squared:  0.6325 
## F-statistic: 188.6 on 1 and 108 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>Confidence Interval for Effect of Acceleration Time:</p>
<div class="sourceCode" id="cb660"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb660-1"><a href="building-models-for-interpretation.html#cb660-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(Cars_M1))</span></code></pre></div>
<pre><code>##                   2.5 %     97.5 %
## (Intercept) 131.4610408 220.284693
## Acc060        0.7768669   0.827959</code></pre>
<p>We are 95% confident that a 1-second increase in acceleration time is associated with an average price decrease betweeen 17% and 22.5%.</p>
</div>
<div id="model-using-quarter-mile-time" class="section level3 smaller hasAnchor" number="6.2.5">
<h3><span class="header-section-number">6.2.5</span> Model Using Quarter Mile Time<a href="building-models-for-interpretation.html#model-using-quarter-mile-time" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb662"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb662-1"><a href="building-models-for-interpretation.html#cb662-1" aria-hidden="true" tabindex="-1"></a>Cars_M2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2015, <span class="fu">log</span>(LowPrice) <span class="sc">~</span> QtrMile)</span>
<span id="cb662-2"><a href="building-models-for-interpretation.html#cb662-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Cars_M2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(LowPrice) ~ QtrMile, data = Cars2015)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.91465 -0.19501  0.02039  0.17538  0.60073 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept)   7.8559     0.3248   24.19 &lt;0.0000000000000002 ***
## QtrMile      -0.2776     0.0201  -13.81 &lt;0.0000000000000002 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.275 on 108 degrees of freedom
## Multiple R-squared:  0.6385, Adjusted R-squared:  0.6351 
## F-statistic: 190.7 on 1 and 108 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>Confidence Interval for Effect of Quarter Mile Time:</p>
<div class="sourceCode" id="cb664"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb664-1"><a href="building-models-for-interpretation.html#cb664-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(Cars_M2))</span></code></pre></div>
<pre><code>##                    2.5 %      97.5 %
## (Intercept) 1355.8297704 4913.077313
## QtrMile        0.7279941    0.788385</code></pre>
<p>We are 95% confident that a 1-second increase in quarter mile time is associated with a price decrease between 21% and 27%, on average.</p>
</div>
<div id="model-using-quarter-mile-time-and-acc.-time" class="section level3 smaller hasAnchor" number="6.2.6">
<h3><span class="header-section-number">6.2.6</span> Model Using Quarter Mile Time and Acc. Time<a href="building-models-for-interpretation.html#model-using-quarter-mile-time-and-acc.-time" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb666"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb666-1"><a href="building-models-for-interpretation.html#cb666-1" aria-hidden="true" tabindex="-1"></a>Cars_M3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2015, <span class="fu">log</span>(LowPrice) <span class="sc">~</span> QtrMile <span class="sc">+</span> Acc060)</span>
<span id="cb666-2"><a href="building-models-for-interpretation.html#cb666-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Cars_M3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(LowPrice) ~ QtrMile + Acc060, data = Cars2015)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.89124 -0.20030  0.01001  0.17576  0.57462 
## 
## Coefficients:
##             Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)  6.83974    1.54354   4.431 0.0000227 ***
## QtrMile     -0.17316    0.15640  -1.107     0.271    
## Acc060      -0.08389    0.12455  -0.673     0.502    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2757 on 107 degrees of freedom
## Multiple R-squared:   0.64,  Adjusted R-squared:  0.6332 
## F-statistic:  95.1 on 2 and 107 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p><strong>Confidence Intervals from 2-variable Model</strong></p>
<div class="sourceCode" id="cb668"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb668-1"><a href="building-models-for-interpretation.html#cb668-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(Cars_M3))</span></code></pre></div>
<pre><code>##                  2.5 %       97.5 %
## (Intercept) 43.8095999 19922.799158
## QtrMile      0.6168071     1.146686
## Acc060       0.7183525     1.177065</code></pre>
<p>It does not make sense to talk about holding QtrMile constant as Acc060 increases, or vice-versa. Trying to do so leads to nonsensical answers.</p>
<p>We are 95% confident that a 1-second increase in quarter mile time is associated with an average price change between a 38% decrease and 15% increase, assuming acceleration time is held constant.</p>
<p>We are 95% confident that a 1-second increase in acceleration time is associated with an average price change between a 28% decrease and 18% increase, assuming quarter mile time is held constant.</p>
</div>
<div id="problems-with-multicollinearity-in-modeling" class="section level3 hasAnchor" number="6.2.7">
<h3><span class="header-section-number">6.2.7</span> Problems with Multicollinearity in Modeling<a href="building-models-for-interpretation.html#problems-with-multicollinearity-in-modeling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Because these variables are so highly correlated, it the model cannot separate the effect of one from the other, and thus is uncertain about both. Notice the very large standard errors associated with both regression coefficients, which lead to very wide confidence intervals.</p>
<p>In fact, if two variables are perfectly correlated, it will be impossible to fit them both in a model, and you will get an error message.</p>
</div>
<div id="impact-on-prediction" class="section level3 smaller hasAnchor" number="6.2.8">
<h3><span class="header-section-number">6.2.8</span> Impact on Prediction<a href="building-models-for-interpretation.html#impact-on-prediction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose we want to predict the price of a car that can accelerate from 0 to 60 mph in 9.5 seconds, and completes a quarter mile in 17.3 seconds.</p>
<div class="sourceCode" id="cb670"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb670-1"><a href="building-models-for-interpretation.html#cb670-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(Cars_M1, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fl">9.5</span>, <span class="at">QtrMile=</span><span class="fl">17.3</span>)))</span></code></pre></div>
<pre><code>##        1 
## 20.92084</code></pre>
<div class="sourceCode" id="cb672"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb672-1"><a href="building-models-for-interpretation.html#cb672-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(Cars_M2, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fl">9.5</span>, <span class="at">QtrMile=</span><span class="fl">17.3</span>)))</span></code></pre></div>
<pre><code>##        1 
## 21.18223</code></pre>
<div class="sourceCode" id="cb674"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb674-1"><a href="building-models-for-interpretation.html#cb674-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(Cars_M3, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Acc060=</span><span class="fl">9.5</span>, <span class="at">QtrMile=</span><span class="fl">17.3</span>)))</span></code></pre></div>
<pre><code>##        1 
## 21.05489</code></pre>
<p>The predicted values are similar. Multicollinearity does not hurt predictions, only interpretations.</p>
</div>
<div id="adding-weight-to-model" class="section level3 hasAnchor" number="6.2.9">
<h3><span class="header-section-number">6.2.9</span> Adding Weight to Model<a href="building-models-for-interpretation.html#adding-weight-to-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb676"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb676-1"><a href="building-models-for-interpretation.html#cb676-1" aria-hidden="true" tabindex="-1"></a>Cars_M4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2015, <span class="fu">log</span>(LowPrice) <span class="sc">~</span> QtrMile <span class="sc">+</span> Weight)</span>
<span id="cb676-2"><a href="building-models-for-interpretation.html#cb676-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Cars_M4)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(LowPrice) ~ QtrMile + Weight, data = Cars2015)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.79365 -0.13931 -0.01368  0.15773  0.42234 
## 
## Coefficients:
##                Estimate  Std. Error t value             Pr(&gt;|t|)    
## (Intercept)  6.21326823  0.33491778  18.552 &lt; 0.0000000000000002 ***
## QtrMile     -0.22482146  0.01748563 -12.858 &lt; 0.0000000000000002 ***
## Weight       0.00020606  0.00002641   7.803      0.0000000000043 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2206 on 107 degrees of freedom
## Multiple R-squared:  0.7696, Adjusted R-squared:  0.7653 
## F-statistic: 178.7 on 2 and 107 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p><span class="math inline">\(R^2\)</span> went up from 0.64 to 0.76!</p>
</div>
<div id="add-interaction-term" class="section level3 hasAnchor" number="6.2.10">
<h3><span class="header-section-number">6.2.10</span> Add Interaction Term?<a href="building-models-for-interpretation.html#add-interaction-term" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb678"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb678-1"><a href="building-models-for-interpretation.html#cb678-1" aria-hidden="true" tabindex="-1"></a>Cars_M5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2015, <span class="fu">log</span>(LowPrice) <span class="sc">~</span> QtrMile <span class="sc">*</span> Weight)</span>
<span id="cb678-2"><a href="building-models-for-interpretation.html#cb678-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Cars_M5)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(LowPrice) ~ QtrMile * Weight, data = Cars2015)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.82013 -0.12076 -0.01464  0.14717  0.41928 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)     4.1114189  1.3270870   3.098  0.00249 **
## QtrMile        -0.0963226  0.0804413  -1.197  0.23381   
## Weight          0.0008110  0.0003707   2.188  0.03089 * 
## QtrMile:Weight -0.0000373  0.0000228  -1.636  0.10482   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2188 on 106 degrees of freedom
## Multiple R-squared:  0.7752, Adjusted R-squared:  0.7689 
## F-statistic: 121.9 on 3 and 106 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>p-value on interaction is not that small. <span class="math inline">\(R^2\)</span> didn’t go up much. Let’s not use it.</p>
</div>
<div id="add-hwy-mpg" class="section level3 hasAnchor" number="6.2.11">
<h3><span class="header-section-number">6.2.11</span> Add HWY MPG?<a href="building-models-for-interpretation.html#add-hwy-mpg" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb680"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb680-1"><a href="building-models-for-interpretation.html#cb680-1" aria-hidden="true" tabindex="-1"></a>Cars_M6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2015, <span class="fu">log</span>(LowPrice) <span class="sc">~</span> QtrMile <span class="sc">+</span> Weight <span class="sc">+</span> HwyMPG)</span>
<span id="cb680-2"><a href="building-models-for-interpretation.html#cb680-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Cars_M6)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(LowPrice) ~ QtrMile + Weight + HwyMPG, data = Cars2015)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.82308 -0.14513 -0.01922  0.16732  0.41390 
## 
## Coefficients:
##                Estimate  Std. Error t value             Pr(&gt;|t|)    
## (Intercept)  6.54954436  0.42196132  15.522 &lt; 0.0000000000000002 ***
## QtrMile     -0.21699008  0.01843615 -11.770 &lt; 0.0000000000000002 ***
## Weight       0.00015922  0.00004456   3.573             0.000532 ***
## HwyMPG      -0.00961141  0.00737658  -1.303             0.195410    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2198 on 106 degrees of freedom
## Multiple R-squared:  0.7732, Adjusted R-squared:  0.7668 
## F-statistic: 120.5 on 3 and 106 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>HwyMPG doesn’t make change <span class="math inline">\(R^2\)</span> much, and has a high correlation with weight. Let’s not include it.</p>
</div>
<div id="categorical-variables-to-consider" class="section level3 hasAnchor" number="6.2.12">
<h3><span class="header-section-number">6.2.12</span> Categorical Variables to Consider<a href="building-models-for-interpretation.html#categorical-variables-to-consider" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Relationship between Price, Size, and Drive</p>
<div class="sourceCode" id="cb682"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb682-1"><a href="building-models-for-interpretation.html#cb682-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Cars2015, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(LowPrice), <span class="at">y=</span>Size)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Price by Size&quot;</span>)</span>
<span id="cb682-2"><a href="building-models-for-interpretation.html#cb682-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Cars2015, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(LowPrice), <span class="at">y=</span>Drive)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Price by Drive&quot;</span>)</span>
<span id="cb682-3"><a href="building-models-for-interpretation.html#cb682-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, <span class="at">ncol=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-508-1.png" width="672" /></p>
<p>Information about size is already included, through the weight variable. Let’s add drive type to the model.</p>
</div>
<div id="model-with-qtrmile-weight-and-drive" class="section level3 hasAnchor" number="6.2.13">
<h3><span class="header-section-number">6.2.13</span> Model with QtrMile, Weight, and Drive<a href="building-models-for-interpretation.html#model-with-qtrmile-weight-and-drive" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb683"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb683-1"><a href="building-models-for-interpretation.html#cb683-1" aria-hidden="true" tabindex="-1"></a>Cars_M7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2015, <span class="fu">log</span>(LowPrice) <span class="sc">~</span> QtrMile <span class="sc">+</span> Weight <span class="sc">+</span> Drive)</span>
<span id="cb683-2"><a href="building-models-for-interpretation.html#cb683-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Cars_M7)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(LowPrice) ~ QtrMile + Weight + Drive, data = Cars2015)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.72386 -0.10882  0.01269  0.13306  0.45304 
## 
## Coefficients:
##                Estimate  Std. Error t value             Pr(&gt;|t|)    
## (Intercept)  5.81406789  0.33961789  17.119 &lt; 0.0000000000000002 ***
## QtrMile     -0.19007439  0.01959554  -9.700 0.000000000000000289 ***
## Weight       0.00020496  0.00002583   7.936 0.000000000002420675 ***
## DriveFWD    -0.22403222  0.05704513  -3.927             0.000154 ***
## DriveRWD    -0.13884399  0.06227709  -2.229             0.027913 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2077 on 105 degrees of freedom
## Multiple R-squared:  0.7995, Adjusted R-squared:  0.7919 
## F-statistic: 104.7 on 4 and 105 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
<div id="add-size" class="section level3 hasAnchor" number="6.2.14">
<h3><span class="header-section-number">6.2.14</span> Add Size<a href="building-models-for-interpretation.html#add-size" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb685"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb685-1"><a href="building-models-for-interpretation.html#cb685-1" aria-hidden="true" tabindex="-1"></a>Cars_M8 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Cars2015, <span class="fu">log</span>(LowPrice) <span class="sc">~</span> QtrMile <span class="sc">+</span> Weight <span class="sc">+</span> Drive <span class="sc">+</span> Size)</span>
<span id="cb685-2"><a href="building-models-for-interpretation.html#cb685-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Cars_M8)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(LowPrice) ~ QtrMile + Weight + Drive + Size, 
##     data = Cars2015)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.71092 -0.12126  0.01355  0.11831  0.44439 
## 
## Coefficients:
##                 Estimate  Std. Error t value             Pr(&gt;|t|)    
## (Intercept)   5.66594310  0.37169625  15.243 &lt; 0.0000000000000002 ***
## QtrMile      -0.19256547  0.02000711  -9.625 0.000000000000000505 ***
## Weight        0.00023978  0.00004101   5.847 0.000000059416930182 ***
## DriveFWD     -0.21598794  0.05780323  -3.737             0.000306 ***
## DriveRWD     -0.15259183  0.06410851  -2.380             0.019142 *  
## SizeMidsized  0.04699095  0.06271499   0.749             0.455398    
## SizeSmall     0.08875861  0.08105810   1.095             0.276071    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2085 on 103 degrees of freedom
## Multiple R-squared:  0.8018, Adjusted R-squared:  0.7903 
## F-statistic: 69.46 on 6 and 103 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>Adding size barely increased <span class="math inline">\(R^2\)</span> at all. We find no evidence of differences in price between the three sizes, after accounting for the other variables.</p>
<p>Note: Information about car size is already being taken into account through the <code>Weight</code> variable.</p>
<p>We could keep looking at other variables to add, but at this point, we have a model that gives us a good sense of the factors related to price of a car, capturing 80% of total variability in car price, and is still easy to interpret.</p>
<p>For our research purposes, this model is good enough.</p>
</div>
<div id="check-of-model-assumptions" class="section level3 hasAnchor" number="6.2.15">
<h3><span class="header-section-number">6.2.15</span> Check of Model Assumptions<a href="building-models-for-interpretation.html#check-of-model-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb687"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb687-1"><a href="building-models-for-interpretation.html#cb687-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(Cars_M7<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">y=</span>Cars_M7<span class="sc">$</span>residuals, <span class="at">x=</span>Cars_M7<span class="sc">$</span>fitted.values)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Residual Plot&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted Values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb687-2"><a href="building-models-for-interpretation.html#cb687-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(Cars_M7<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">x=</span>Cars_M7<span class="sc">$</span>residuals)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Histogram of Residuals&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Residual&quot;</span>)</span>
<span id="cb687-3"><a href="building-models-for-interpretation.html#cb687-3" aria-hidden="true" tabindex="-1"></a>P3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(Cars_M7<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">scale</span>(Cars_M7<span class="sc">$</span>residuals))) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Normal Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residual Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;QQ Plot&quot;</span>)</span>
<span id="cb687-4"><a href="building-models-for-interpretation.html#cb687-4" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, P3, <span class="at">ncol=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-511-1.png" width="864" /></p>
<p>There is slight concern about constant variance, but otherwise, the model assumptions look good.</p>
</div>
<div id="residual-by-predictor-plots" class="section level3 hasAnchor" number="6.2.16">
<h3><span class="header-section-number">6.2.16</span> Residual by Predictor Plots<a href="building-models-for-interpretation.html#residual-by-predictor-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb688"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb688-1"><a href="building-models-for-interpretation.html#cb688-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(Cars_M7<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">y=</span>Cars_M7<span class="sc">$</span>residuals, <span class="at">x=</span>Cars_M7<span class="sc">$</span>model<span class="sc">$</span>QtrMile)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Residual by Predictor Plot&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;QtrMile&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>) </span>
<span id="cb688-2"><a href="building-models-for-interpretation.html#cb688-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(Cars_M7<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">y=</span>Cars_M7<span class="sc">$</span>residuals, <span class="at">x=</span>Cars_M7<span class="sc">$</span>model<span class="sc">$</span>Weight)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Residual by Predictor Plot&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Weight&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>) </span>
<span id="cb688-3"><a href="building-models-for-interpretation.html#cb688-3" aria-hidden="true" tabindex="-1"></a>P3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">data.frame</span>(Cars_M7<span class="sc">$</span>residuals), <span class="fu">aes</span>(<span class="at">y=</span>Cars_M7<span class="sc">$</span>residuals, <span class="at">x=</span>Cars_M7<span class="sc">$</span>model<span class="sc">$</span>Drive)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Residual by Predictor Plot&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Drive&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>) </span>
<span id="cb688-4"><a href="building-models-for-interpretation.html#cb688-4" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, P3, <span class="at">ncol=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-512-1.png" width="864" /></p>
<p>These plots don’t raise any concerns.</p>
</div>
<div id="coefficients-and-exponentiation" class="section level3 hasAnchor" number="6.2.17">
<h3><span class="header-section-number">6.2.17</span> Coefficients and Exponentiation<a href="building-models-for-interpretation.html#coefficients-and-exponentiation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb689"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb689-1"><a href="building-models-for-interpretation.html#cb689-1" aria-hidden="true" tabindex="-1"></a>Cars_M7<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##   (Intercept)       QtrMile        Weight      DriveFWD      DriveRWD 
##  5.8140678915 -0.1900743859  0.0002049586 -0.2240322171 -0.1388439916</code></pre>
<div class="sourceCode" id="cb691"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb691-1"><a href="building-models-for-interpretation.html#cb691-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(Cars_M7<span class="sc">$</span>coefficients)</span></code></pre></div>
<pre><code>## (Intercept)     QtrMile      Weight    DriveFWD    DriveRWD 
## 334.9790161   0.8268976   1.0002050   0.7992894   0.8703638</code></pre>
</div>
<div id="interpretation-of-coefficients" class="section level3 hasAnchor" number="6.2.18">
<h3><span class="header-section-number">6.2.18</span> Interpretation of Coefficients<a href="building-models-for-interpretation.html#interpretation-of-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb693"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb693-1"><a href="building-models-for-interpretation.html#cb693-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(Cars_M7<span class="sc">$</span>coefficients)</span></code></pre></div>
<pre><code>## (Intercept)     QtrMile      Weight    DriveFWD    DriveRWD 
## 334.9790161   0.8268976   1.0002050   0.7992894   0.8703638</code></pre>
<p>The price of a car is expected to decrease by 17% for each additional second it takes to drive a quartermile, assuming weight, and drive type are held constant.</p>
<p>The price of a car is expected to increase by 0.02% for each additional pound, assuming quarter mile time, and drive type are held constant. Thus, a 100 lb increase is assocated with an expected 2% increase in price, assuming quarter mile time, and drive type are held constant.</p>
<p>FWD cars are expected to cost 20% less than AWD cars, assuming quarter mile time and weight are held constant.</p>
<p>RWD cars are expected to cost 13% less than AWD cars, assuming quarter mile time and weight are held constant.</p>
</div>
<div id="adjusted-r2-aic-bic" class="section level3 hasAnchor" number="6.2.19">
<h3><span class="header-section-number">6.2.19</span> Adjusted <span class="math inline">\(R^2\)</span>, AIC, BIC<a href="building-models-for-interpretation.html#adjusted-r2-aic-bic" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When additional variables are added to a model, SSR never increases, hence <span class="math inline">\(R^2\)</span> never decreases.</p>
<p>Other diagnostics have been introduced to decrease when a term is added to a model and does little to help explain variability.</p>
<p>These include:</p>
<ul>
<li>Adjusted <span class="math inline">\(R^2\)</span></li>
<li>Akaike Information Criterion (AIC)<br />
</li>
<li>Bayesian Information Criterion (BIC)</li>
</ul>
<p>These are intended to help guide us in deciding whether or not to include a variable in a model.They can decrease (or increase) when an additional variables is added if it doesn’t contain much useful information.</p>
<p>These are mostly ad-hoc approaches designed for specific situations. Although they might work well in certain contexts, none are meanth for general use. Furthermore, they can and often do disagree on the best model. I do not advise using these to choose a model, unless you have good reason to in your specific context.</p>
</div>
<div id="model-building-summary" class="section level3 hasAnchor" number="6.2.20">
<h3><span class="header-section-number">6.2.20</span> Model Building Summary<a href="building-models-for-interpretation.html#model-building-summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Consider the following when building a model for the purpose of interpreting parameters and understanding and drawing conclusions about a population or process.</p>
<ul>
<li>Model driven by research question</li>
<li>Include variables of interest<br />
</li>
<li>Include potential confounders (like in SAT example)<br />
</li>
<li>Avoid including highly correlated explanatory variables<br />
</li>
<li>Avoid messy transformations and interactions where possible<br />
</li>
<li>Use residual plots to assess appropriatness of model assumptions<br />
</li>
<li>Aim for high <span class="math inline">\(R^2\)</span> but not highest<br />
</li>
<li>Only use AIC, BIC, Adjusted <span class="math inline">\(R^2\)</span> in the other factors listed above (if you use them at all). Do not rely on these measures alone!<br />
</li>
<li>Aim for model complex enough to capture nature of data, but simple enough to give clear interpretations</li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="normal-error-regression-model.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="predictive-modeling.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Stat255-LU/Notes/edit/master/06-Model_Building.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/Stat255-LU/Notes/blob/master/06-Model_Building.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
