<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Hypothesis Testing via Permutation | Stat 255: Statistics for Data Science Notes</title>
  <meta name="description" content="Chapter 3 Hypothesis Testing via Permutation | Stat 255: Statistics for Data Science Notes" />
  <meta name="generator" content="bookdown 0.31 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Hypothesis Testing via Permutation | Stat 255: Statistics for Data Science Notes" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Hypothesis Testing via Permutation | Stat 255: Statistics for Data Science Notes" />
  
  
  

<meta name="author" content="Andrew Sage - Lawrence University" />


<meta name="date" content="2023-10-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introduction-to-statistical-models.html"/>
<link rel="next" href="bootstrap-interval-estimation.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STAT 255 Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html"><i class="fa fa-check"></i><b>1</b> Exploratory Data Analysis</a>
<ul>
<li class="chapter" data-level="1.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#getting-started-in-r"><i class="fa fa-check"></i><b>1.1</b> Getting Started in R</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#previewing-the-data"><i class="fa fa-check"></i><b>1.1.1</b> Previewing the Data</a></li>
<li class="chapter" data-level="1.1.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#modifying-the-data"><i class="fa fa-check"></i><b>1.1.2</b> Modifying the Data</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#data-visualization"><i class="fa fa-check"></i><b>1.2</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#histogram"><i class="fa fa-check"></i><b>1.2.1</b> Histogram</a></li>
<li class="chapter" data-level="1.2.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#density-plot"><i class="fa fa-check"></i><b>1.2.2</b> Density Plot</a></li>
<li class="chapter" data-level="1.2.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#boxplot"><i class="fa fa-check"></i><b>1.2.3</b> Boxplot</a></li>
<li class="chapter" data-level="1.2.4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#violin-plot"><i class="fa fa-check"></i><b>1.2.4</b> Violin Plot</a></li>
<li class="chapter" data-level="1.2.5" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#scatterplot"><i class="fa fa-check"></i><b>1.2.5</b> Scatterplot</a></li>
<li class="chapter" data-level="1.2.6" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#bar-graph"><i class="fa fa-check"></i><b>1.2.6</b> Bar Graph</a></li>
<li class="chapter" data-level="1.2.7" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#stacked-and-side-by-side-bar-graphs"><i class="fa fa-check"></i><b>1.2.7</b> Stacked and Side-by-Side Bar Graphs</a></li>
<li class="chapter" data-level="1.2.8" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#correlation-plot"><i class="fa fa-check"></i><b>1.2.8</b> Correlation Plot</a></li>
<li class="chapter" data-level="1.2.9" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#scatterplot-matrix"><i class="fa fa-check"></i><b>1.2.9</b> Scatterplot Matrix</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#summary-tables"><i class="fa fa-check"></i><b>1.3</b> Summary Tables</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#calculating-summary-statistics"><i class="fa fa-check"></i><b>1.3.1</b> Calculating Summary Statistics</a></li>
<li class="chapter" data-level="1.3.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#grouped-summaries"><i class="fa fa-check"></i><b>1.3.2</b> Grouped Summaries</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html"><i class="fa fa-check"></i><b>2</b> Introduction to Statistical Models</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#fitting-models-to-data"><i class="fa fa-check"></i><b>2.1</b> Fitting Models to Data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#terminology"><i class="fa fa-check"></i><b>2.1.1</b> Terminology</a></li>
<li class="chapter" data-level="2.1.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-with-quantitative-explanatory-variable"><i class="fa fa-check"></i><b>2.1.2</b> Model with Quantitative Explanatory Variable</a></li>
<li class="chapter" data-level="2.1.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-with-categorical-variable"><i class="fa fa-check"></i><b>2.1.3</b> Model with Categorical Variable</a></li>
<li class="chapter" data-level="2.1.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-with-multiple-explanatory-variables"><i class="fa fa-check"></i><b>2.1.4</b> Model with Multiple Explanatory Variables</a></li>
<li class="chapter" data-level="2.1.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-with-no-explanatory-variable"><i class="fa fa-check"></i><b>2.1.5</b> Model with No Explanatory Variable</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#variability-explained-by-a-model"><i class="fa fa-check"></i><b>2.2</b> Variability Explained by a Model</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#quantifying-variability"><i class="fa fa-check"></i><b>2.2.1</b> Quantifying Variability</a></li>
<li class="chapter" data-level="2.2.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#total-variability"><i class="fa fa-check"></i><b>2.2.2</b> Total Variability</a></li>
<li class="chapter" data-level="2.2.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#residuals"><i class="fa fa-check"></i><b>2.2.3</b> Residuals</a></li>
<li class="chapter" data-level="2.2.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#variability-explained-by-sq.-ft.-model"><i class="fa fa-check"></i><b>2.2.4</b> Variability Explained by Sq. Ft. Model</a></li>
<li class="chapter" data-level="2.2.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#linear-correlation-coefficient"><i class="fa fa-check"></i><b>2.2.5</b> Linear Correlation Coefficient</a></li>
<li class="chapter" data-level="2.2.6" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#variability-explained-by-waterfront-model"><i class="fa fa-check"></i><b>2.2.6</b> Variability Explained by Waterfront Model</a></li>
<li class="chapter" data-level="2.2.7" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#variability-explained-by-multiple-regression-model"><i class="fa fa-check"></i><b>2.2.7</b> Variability Explained by Multiple Regression Model</a></li>
<li class="chapter" data-level="2.2.8" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#summary-sst-ssr-ssm-r2"><i class="fa fa-check"></i><b>2.2.8</b> Summary: SST, SSR, SSM, <span class="math inline">\(R^2\)</span></a></li>
<li class="chapter" data-level="2.2.9" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#r2-visually"><i class="fa fa-check"></i><b>2.2.9</b> <span class="math inline">\(R^2\)</span> Visually</a></li>
<li class="chapter" data-level="2.2.10" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-comparison-summary"><i class="fa fa-check"></i><b>2.2.10</b> Model Comparison Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#models-with-interaction"><i class="fa fa-check"></i><b>2.3</b> Models with Interaction</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#definition-of-interaction"><i class="fa fa-check"></i><b>2.3.1</b> Definition of Interaction</a></li>
<li class="chapter" data-level="2.3.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#interaction-term"><i class="fa fa-check"></i><b>2.3.2</b> Interaction Term</a></li>
<li class="chapter" data-level="2.3.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#interaction-models-in-r"><i class="fa fa-check"></i><b>2.3.3</b> Interaction Models in R</a></li>
<li class="chapter" data-level="2.3.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#r2-for-interaction-model"><i class="fa fa-check"></i><b>2.3.4</b> <span class="math inline">\(R^2\)</span> for Interaction Model</a></li>
<li class="chapter" data-level="2.3.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#considerations-for-using-interactions"><i class="fa fa-check"></i><b>2.3.5</b> Considerations for Using Interactions</a></li>
<li class="chapter" data-level="2.3.6" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#interaction-vs-correlation"><i class="fa fa-check"></i><b>2.3.6</b> Interaction vs Correlation</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#least-squares-estimation-lse"><i class="fa fa-check"></i><b>2.4</b> Least Squares Estimation (LSE)</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#estimating-regression-coefficients"><i class="fa fa-check"></i><b>2.4.1</b> Estimating Regression Coefficients</a></li>
<li class="chapter" data-level="2.4.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#mathematics-of-lse-for-slr"><i class="fa fa-check"></i><b>2.4.2</b> Mathematics of LSE for SLR</a></li>
<li class="chapter" data-level="2.4.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#lse-for-categorical-variable"><i class="fa fa-check"></i><b>2.4.3</b> LSE for Categorical Variable</a></li>
<li class="chapter" data-level="2.4.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#lse-more-generally"><i class="fa fa-check"></i><b>2.4.4</b> LSE More Generally</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#analysis-of-variance"><i class="fa fa-check"></i><b>2.5</b> ANalysis Of VAriance</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#submodels"><i class="fa fa-check"></i><b>2.5.1</b> Submodels</a></li>
<li class="chapter" data-level="2.5.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#f-statistics"><i class="fa fa-check"></i><b>2.5.2</b> F-Statistics</a></li>
<li class="chapter" data-level="2.5.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#comparing-3-or-more-categories"><i class="fa fa-check"></i><b>2.5.3</b> Comparing 3 or More Categories</a></li>
<li class="chapter" data-level="2.5.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#f-statistic-illustration"><i class="fa fa-check"></i><b>2.5.4</b> F-Statistic Illustration</a></li>
<li class="chapter" data-level="2.5.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#alternative-f-statistic-formula"><i class="fa fa-check"></i><b>2.5.5</b> Alternative F-Statistic Formula</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html"><i class="fa fa-check"></i><b>3</b> Hypothesis Testing via Permutation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#test-for-difference-in-means"><i class="fa fa-check"></i><b>3.1</b> Test for Difference in Means</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#mercury-levels-in-florida-lakes"><i class="fa fa-check"></i><b>3.1.1</b> Mercury Levels in Florida Lakes</a></li>
<li class="chapter" data-level="3.1.2" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#model-for-mercury-level"><i class="fa fa-check"></i><b>3.1.2</b> Model for Mercury Level</a></li>
<li class="chapter" data-level="3.1.3" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#hypotheses-and-key-question"><i class="fa fa-check"></i><b>3.1.3</b> Hypotheses and Key Question</a></li>
<li class="chapter" data-level="3.1.4" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#permutation-test-for-difference-in-means"><i class="fa fa-check"></i><b>3.1.4</b> Permutation Test for Difference in Means</a></li>
<li class="chapter" data-level="3.1.5" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#five-permutations-in-r"><i class="fa fa-check"></i><b>3.1.5</b> Five Permutations in R</a></li>
<li class="chapter" data-level="3.1.6" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#r-code-for-permutation-test"><i class="fa fa-check"></i><b>3.1.6</b> R Code for Permutation Test</a></li>
<li class="chapter" data-level="3.1.7" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#p-values"><i class="fa fa-check"></i><b>3.1.7</b> p-values</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#general-permutation-tests"><i class="fa fa-check"></i><b>3.2</b> General Permutation Tests</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#other-test-statistics"><i class="fa fa-check"></i><b>3.2.1</b> Other Test Statistics</a></li>
<li class="chapter" data-level="3.2.2" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#general-permutation-test-procedure"><i class="fa fa-check"></i><b>3.2.2</b> General Permutation Test Procedure</a></li>
<li class="chapter" data-level="3.2.3" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#difference-in-standard-deviation"><i class="fa fa-check"></i><b>3.2.3</b> Difference in Standard Deviation</a></li>
<li class="chapter" data-level="3.2.4" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#permutation-test-for-slope"><i class="fa fa-check"></i><b>3.2.4</b> Permutation Test for Slope</a></li>
<li class="chapter" data-level="3.2.5" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#f-statistic"><i class="fa fa-check"></i><b>3.2.5</b> F-Statistic</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#responsible-hypothesis-testing"><i class="fa fa-check"></i><b>3.3</b> Responsible Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html"><i class="fa fa-check"></i><b>4</b> Bootstrap Interval Estimation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#sampling-distributions"><i class="fa fa-check"></i><b>4.1</b> Sampling Distributions</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#sampling-from-a-population"><i class="fa fa-check"></i><b>4.1.1</b> Sampling From a Population</a></li>
<li class="chapter" data-level="4.1.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#confidence-intervals"><i class="fa fa-check"></i><b>4.1.2</b> Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrapping"><i class="fa fa-check"></i><b>4.2</b> Bootstrapping</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#mercury-levels-in-florida-lakes-1"><i class="fa fa-check"></i><b>4.2.1</b> Mercury Levels in Florida Lakes</a></li>
<li class="chapter" data-level="4.2.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-sampling"><i class="fa fa-check"></i><b>4.2.2</b> Bootstrap Sampling</a></li>
<li class="chapter" data-level="4.2.3" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-samples-of-lakes"><i class="fa fa-check"></i><b>4.2.3</b> Bootstrap Samples of Lakes</a></li>
<li class="chapter" data-level="4.2.4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-distribution"><i class="fa fa-check"></i><b>4.2.4</b> Bootstrap Distribution</a></li>
<li class="chapter" data-level="4.2.5" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-se-confidence-interval"><i class="fa fa-check"></i><b>4.2.5</b> Bootstrap SE Confidence Interval</a></li>
<li class="chapter" data-level="4.2.6" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-distribution-vs-sampling-distribution"><i class="fa fa-check"></i><b>4.2.6</b> Bootstrap Distribution vs Sampling Distribution</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-confidence-interval-example"><i class="fa fa-check"></i><b>4.3</b> Bootstrap Confidence Interval Example</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrapping-other-statistics"><i class="fa fa-check"></i><b>4.3.1</b> Bootstrapping Other Statistics</a></li>
<li class="chapter" data-level="4.3.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-mean"><i class="fa fa-check"></i><b>4.3.2</b> CI for Mean</a></li>
<li class="chapter" data-level="4.3.3" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-standard-deviation"><i class="fa fa-check"></i><b>4.3.3</b> CI for Standard Deviation</a></li>
<li class="chapter" data-level="4.3.4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-median"><i class="fa fa-check"></i><b>4.3.4</b> CI for Median</a></li>
<li class="chapter" data-level="4.3.5" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-difference-in-means"><i class="fa fa-check"></i><b>4.3.5</b> CI for Difference in Means</a></li>
<li class="chapter" data-level="4.3.6" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-regression-slope"><i class="fa fa-check"></i><b>4.3.6</b> CI for Regression Slope</a></li>
<li class="chapter" data-level="4.3.7" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-regression-response"><i class="fa fa-check"></i><b>4.3.7</b> CI for Regression Response</a></li>
<li class="chapter" data-level="4.3.8" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#more-cis-in-regression"><i class="fa fa-check"></i><b>4.3.8</b> More CI’s in Regression</a></li>
<li class="chapter" data-level="4.3.9" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrapping-cautions"><i class="fa fa-check"></i><b>4.3.9</b> Bootstrapping Cautions</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#estimating-standard-error"><i class="fa fa-check"></i><b>4.4</b> Estimating Standard Error</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#standard-error-vs-standard-deviation"><i class="fa fa-check"></i><b>4.4.1</b> Standard Error vs Standard Deviation</a></li>
<li class="chapter" data-level="4.4.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#sample-size-and-standard-error"><i class="fa fa-check"></i><b>4.4.2</b> Sample Size and Standard Error</a></li>
<li class="chapter" data-level="4.4.3" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#standard-error-formulas"><i class="fa fa-check"></i><b>4.4.3</b> Standard Error Formulas</a></li>
<li class="chapter" data-level="4.4.4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#one-sample-mean-example"><i class="fa fa-check"></i><b>4.4.4</b> One-Sample Mean Example</a></li>
<li class="chapter" data-level="4.4.5" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#difference-in-means-example"><i class="fa fa-check"></i><b>4.4.5</b> Difference in Means Example</a></li>
<li class="chapter" data-level="4.4.6" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#regression-example"><i class="fa fa-check"></i><b>4.4.6</b> Regression Example</a></li>
<li class="chapter" data-level="4.4.7" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#theory-based-confidence-intervals"><i class="fa fa-check"></i><b>4.4.7</b> Theory-Based Confidence Intervals</a></li>
<li class="chapter" data-level="4.4.8" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-method-comparison"><i class="fa fa-check"></i><b>4.4.8</b> CI Method Comparison</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html"><i class="fa fa-check"></i><b>5</b> Normal Error Regression Model</a>
<ul>
<li class="chapter" data-level="5.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#the-normal-error-regression-model"><i class="fa fa-check"></i><b>5.1</b> The Normal Error Regression Model</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#example-ice-cream-dispensor"><i class="fa fa-check"></i><b>5.1.1</b> Example: Ice Cream Dispensor</a></li>
<li class="chapter" data-level="5.1.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#signal-and-noise"><i class="fa fa-check"></i><b>5.1.2</b> Signal and Noise</a></li>
<li class="chapter" data-level="5.1.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#normal-distribution"><i class="fa fa-check"></i><b>5.1.3</b> Normal Distribution</a></li>
<li class="chapter" data-level="5.1.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#signal-and-noise-in-icecream-example"><i class="fa fa-check"></i><b>5.1.4</b> Signal and Noise in Icecream Example</a></li>
<li class="chapter" data-level="5.1.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#general-mathematical-form"><i class="fa fa-check"></i><b>5.1.5</b> General Mathematical Form</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#inference-in-llsr-model"><i class="fa fa-check"></i><b>5.2</b> Inference in LLSR Model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#lm-summary-output"><i class="fa fa-check"></i><b>5.2.1</b> <code>lm</code> <code>summary</code> Output</a></li>
<li class="chapter" data-level="5.2.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#example-florida-lakes-hypothesis"><i class="fa fa-check"></i><b>5.2.2</b> Example: Florida Lakes Hypothesis</a></li>
<li class="chapter" data-level="5.2.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#t-distribution"><i class="fa fa-check"></i><b>5.2.3</b> t-distribution</a></li>
<li class="chapter" data-level="5.2.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#t-test"><i class="fa fa-check"></i><b>5.2.4</b> t-test</a></li>
<li class="chapter" data-level="5.2.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#t-test-for-n-vs-s-lakes"><i class="fa fa-check"></i><b>5.2.5</b> t-test for N vs S Lakes</a></li>
<li class="chapter" data-level="5.2.6" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#comparison-to-simulation"><i class="fa fa-check"></i><b>5.2.6</b> Comparison to Simulation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="model-building.html"><a href="model-building.html"><i class="fa fa-check"></i><b>6</b> Model Building</a></li>
<li class="chapter" data-level="7" data-path="classification-and-logistic-regression.html"><a href="classification-and-logistic-regression.html"><i class="fa fa-check"></i><b>7</b> Classification and Logistic Regression</a></li>
<li class="chapter" data-level="8" data-path="predictive-modeling.html"><a href="predictive-modeling.html"><i class="fa fa-check"></i><b>8</b> Predictive Modeling</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Stat 255: Statistics for Data Science Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hypothesis-testing-via-permutation" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Hypothesis Testing via Permutation<a href="hypothesis-testing-via-permutation.html#hypothesis-testing-via-permutation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>Learning Outcomes:</strong></p>
<ol style="list-style-type: decimal">
<li>State null and alternative hypotheses associated with models involving categorical and quantitative explanatory variables.<br />
</li>
<li>Explain how to use permutation tests for hypotheses involving means, medians, F-statistics, slopes, proportions, and other regression coefficients, as well as functions of these statistics.<br />
</li>
<li>Interpret p-values in context.<br />
</li>
<li>Explain the conclusions we should draw from from a hypothesis test, while accounting for other information available in a dataset.<br />
</li>
<li>Distinguish between statistical significance and practical importance.</li>
</ol>
<div id="test-for-difference-in-means" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Test for Difference in Means<a href="hypothesis-testing-via-permutation.html#test-for-difference-in-means" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="mercury-levels-in-florida-lakes" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Mercury Levels in Florida Lakes<a href="hypothesis-testing-via-permutation.html#mercury-levels-in-florida-lakes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A 2004 study by Lange, T., Royals, H. and Connor, L. examined Mercury accumulation in large-mouth bass, taken from a sample of 53 Florida Lakes. If Mercury accumulation exceeds 0.5 ppm, then there are environmental concerns. In fact, the legal safety limit in Canada is 0.5 ppm, although it is 1 ppm in the United States.</p>
<p>In our sample, we have data on 53 lakes, out of more than 30,000 lakes in the the state of Florida. We’ll attempt to draw conclusions about the entire population, consisting of all lakes in Florida, using data from our sample of 53. It is not clear how the lakes in this sample of 53 were selected, or how representative they are of all lakes in the state of Florida. Let’s assume for our purposes that the lakes in the sample can be reasonably thought of as being representative of all lakes in Florida.</p>
<div class="figure"><span style="display:block;" id="fig:Bass"></span>
<img src="Bass.png" alt="https://www.maine.gov/ifw/fish-wildlife/fisheries/species-information/largemouth-bass.html" width="50%" />
<p class="caption">
Figure 3.1: <a href="https://www.maine.gov/ifw/fish-wildlife/fisheries/species-information/largemouth-bass.html" class="uri">https://www.maine.gov/ifw/fish-wildlife/fisheries/species-information/largemouth-bass.html</a>
</p>
</div>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="hypothesis-testing-via-permutation.html#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;FloridaLakes&quot;</span>)</span>
<span id="cb130-2"><a href="hypothesis-testing-via-permutation.html#cb130-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(FloridaLakes)</span></code></pre></div>
<pre><code>## Rows: 53
## Columns: 12
## $ ID                &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1…
## $ Lake              &lt;chr&gt; &quot;Alligator&quot;, &quot;Annie&quot;, &quot;Apopka&quot;, &quot;Blue Cypress&quot;, &quot;Bri…
## $ Alkalinity        &lt;dbl&gt; 5.9, 3.5, 116.0, 39.4, 2.5, 19.6, 5.2, 71.4, 26.4, 4…
## $ pH                &lt;dbl&gt; 6.1, 5.1, 9.1, 6.9, 4.6, 7.3, 5.4, 8.1, 5.8, 6.4, 5.…
## $ Calcium           &lt;dbl&gt; 3.0, 1.9, 44.1, 16.4, 2.9, 4.5, 2.8, 55.2, 9.2, 4.6,…
## $ Chlorophyll       &lt;dbl&gt; 0.7, 3.2, 128.3, 3.5, 1.8, 44.1, 3.4, 33.7, 1.6, 22.…
## $ AvgMercury        &lt;dbl&gt; 1.23, 1.33, 0.04, 0.44, 1.20, 0.27, 0.48, 0.19, 0.83…
## $ NumSamples        &lt;int&gt; 5, 7, 6, 12, 12, 14, 10, 12, 24, 12, 12, 12, 7, 43, …
## $ MinMercury        &lt;dbl&gt; 0.85, 0.92, 0.04, 0.13, 0.69, 0.04, 0.30, 0.08, 0.26…
## $ MaxMercury        &lt;dbl&gt; 1.43, 1.90, 0.06, 0.84, 1.50, 0.48, 0.72, 0.38, 1.40…
## $ ThreeYrStdMercury &lt;dbl&gt; 1.53, 1.33, 0.04, 0.44, 1.33, 0.25, 0.45, 0.16, 0.72…
## $ AgeData           &lt;int&gt; 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1…</code></pre>
<p>We are interested in whether mercury levels are higher or lower, on average, in Northern Florida compared to Southern Florida.</p>
<p>We’ll divide the state along route 50, which runs East-West, passing through Northern Orlando.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-106"></span>
<img src="Florida.png" alt="from Google Maps" width="30%" />
<p class="caption">
Figure 3.2: from Google Maps
</p>
</div>
<p>We add a variable indicating whether each lake lies in the northern or southern part of the state.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="hypothesis-testing-via-permutation.html#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Lock5Data)</span>
<span id="cb132-2"><a href="hypothesis-testing-via-permutation.html#cb132-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(FloridaLakes)</span>
<span id="cb132-3"><a href="hypothesis-testing-via-permutation.html#cb132-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Location relative to rt. 50</span></span>
<span id="cb132-4"><a href="hypothesis-testing-via-permutation.html#cb132-4" aria-hidden="true" tabindex="-1"></a>FloridaLakes<span class="sc">$</span>Location <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">c</span>(<span class="st">&quot;S&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;S&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>,<span class="st">&quot;N&quot;</span>))</span>
<span id="cb132-5"><a href="hypothesis-testing-via-permutation.html#cb132-5" aria-hidden="true" tabindex="-1"></a>FloridaLakes <span class="ot">&lt;-</span> FloridaLakes <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">Mercury =</span> AvgMercury)</span>
<span id="cb132-6"><a href="hypothesis-testing-via-permutation.html#cb132-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print.data.frame</span>(<span class="fu">data.frame</span>(FloridaLakes<span class="sc">%&gt;%</span> <span class="fu">select</span>(Lake, Location, Mercury)), <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>##               Lake Location Mercury
##          Alligator        S    1.23
##              Annie        S    1.33
##             Apopka        N    0.04
##       Blue Cypress        S    0.44
##              Brick        S    1.20
##             Bryant        N    0.27
##             Cherry        N    0.48
##           Crescent        N    0.19
##         Deer Point        N    0.83
##               Dias        N    0.81
##               Dorr        N    0.71
##               Down        S    0.50
##              Eaton        N    0.49
##  East Tohopekaliga        S    1.16
##            Farm-13        N    0.05
##             George        N    0.15
##            Griffin        N    0.19
##             Harney        N    0.77
##               Hart        S    1.08
##         Hatchineha        S    0.98
##            Iamonia        N    0.63
##          Istokpoga        S    0.56
##            Jackson        N    0.41
##          Josephine        S    0.73
##           Kingsley        N    0.34
##          Kissimmee        S    0.59
##          Lochloosa        N    0.34
##             Louisa        S    0.84
##         Miccasukee        N    0.50
##           Minneola        N    0.34
##             Monroe        N    0.28
##            Newmans        N    0.34
##         Ocean Pond        N    0.87
##       Ocheese Pond        N    0.56
##         Okeechobee        S    0.17
##             Orange        N    0.18
##        Panasoffkee        N    0.19
##             Parker        S    0.04
##             Placid        S    0.49
##             Puzzle        N    1.10
##             Rodman        N    0.16
##           Rousseau        N    0.10
##            Sampson        N    0.48
##              Shipp        S    0.21
##            Talquin        N    0.86
##             Tarpon        S    0.52
##       Tohopekaliga        S    0.65
##           Trafford        S    0.27
##              Trout        S    0.94
##       Tsala Apopka        N    0.40
##               Weir        N    0.43
##            Wildcat        N    0.25
##               Yale        N    0.27</code></pre>
<p>We are interested in investigating whether average mercury levels are higher in either Northern Florida or Southern Florida than the other.</p>
<p>The boxplot and table below show the distribution of mercury levels among the 33 northern and 20 southern lakes in the sample.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="hypothesis-testing-via-permutation.html#cb134-1" aria-hidden="true" tabindex="-1"></a>LakesBP <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>FloridaLakes, <span class="fu">aes</span>(<span class="at">x=</span>Location, <span class="at">y=</span>Mercury, <span class="at">fill=</span>Location)) <span class="sc">+</span> </span>
<span id="cb134-2"><a href="hypothesis-testing-via-permutation.html#cb134-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span>   <span class="fu">geom_jitter</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Mercury Levels in Florida Lakes&quot;</span>) <span class="sc">+</span> </span>
<span id="cb134-3"><a href="hypothesis-testing-via-permutation.html#cb134-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Location&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Mercury Level&quot;</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1.5</span>)) <span class="sc">+</span> <span class="fu">coord_flip</span>() </span>
<span id="cb134-4"><a href="hypothesis-testing-via-permutation.html#cb134-4" aria-hidden="true" tabindex="-1"></a>LakesBP</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-108-1.png" width="672" /></p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="hypothesis-testing-via-permutation.html#cb135-1" aria-hidden="true" tabindex="-1"></a>LakesTable <span class="ot">&lt;-</span> FloridaLakes <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Location) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">MeanHg=</span><span class="fu">mean</span>(Mercury), <span class="at">StDevHg=</span><span class="fu">sd</span>(Mercury),  <span class="at">N=</span><span class="fu">n</span>())</span>
<span id="cb135-2"><a href="hypothesis-testing-via-permutation.html#cb135-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(LakesTable)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Location</th>
<th align="right">MeanHg</th>
<th align="right">StDevHg</th>
<th align="right">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">N</td>
<td align="right">0.4245455</td>
<td align="right">0.2696652</td>
<td align="right">33</td>
</tr>
<tr class="even">
<td align="left">S</td>
<td align="right">0.6965000</td>
<td align="right">0.3838760</td>
<td align="right">20</td>
</tr>
</tbody>
</table>
<p>We see that on average mercury levels were higher among the southern lakes than the northern ones, a difference of <span class="math inline">\(0.697-0.445= 0.272\)</span> ppm.</p>
</div>
<div id="model-for-mercury-level" class="section level3 hasAnchor" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Model for Mercury Level<a href="hypothesis-testing-via-permutation.html#model-for-mercury-level" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can use a statistical model to estimate a lake’s mercury level, using its location (N or S) as our explanatory variable.</p>
<p>The model equation is</p>
<p><span class="math inline">\(\widehat{\text{Hg}} = b_0 +b_1\times\text{South}\)</span></p>
<ul>
<li><span class="math inline">\(b_0\)</span> represents the mean mercury level for lakes in North Florida, and<br />
</li>
<li><span class="math inline">\(b_1\)</span> represents the mean difference in mercury level for lakes in South Florida, compared to North Florida</li>
</ul>
<p>Fitting the model in R, we obtain the estimates for <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="hypothesis-testing-via-permutation.html#cb136-1" aria-hidden="true" tabindex="-1"></a>Lakes_M <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>FloridaLakes, Mercury <span class="sc">~</span> Location)</span>
<span id="cb136-2"><a href="hypothesis-testing-via-permutation.html#cb136-2" aria-hidden="true" tabindex="-1"></a>Lakes_M</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Mercury ~ Location, data = FloridaLakes)
## 
## Coefficients:
## (Intercept)    LocationS  
##      0.4245       0.2720</code></pre>
<p><span class="math inline">\(\widehat{\text{Hg}} = 0.4245455 +0.2719545\times\text{South}\)</span></p>
<ul>
<li><p><span class="math inline">\(b_1 = 0.272= 0.6965 - 0.4245\)</span> is equal to the difference in mean mercury levels between Northern and Southern lakes. (We’ve already seen that for categorical variables, the least-squares estimate is the mean, so this makes sense.)</p></li>
<li><p>We can use <span class="math inline">\(b_1\)</span> to assess the size of the difference in mean mercury concentration levels.</p></li>
</ul>
</div>
<div id="hypotheses-and-key-question" class="section level3 hasAnchor" number="3.1.3">
<h3><span class="header-section-number">3.1.3</span> Hypotheses and Key Question<a href="hypothesis-testing-via-permutation.html#hypotheses-and-key-question" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Since the lakes we observed are only a sample of 53 lakes out of more than 30,000, we cannot assume the difference in mercury concentration for <strong>all</strong> Northern vs Southern Florida lakes is exactly 0.272. Instead, we need to determine whether a difference of this size in our sample is large enough to provide evidence of a difference in average mercury level between <strong>all</strong> Northern and Southern lakes in Florida.</p>
<p>One possible explanation for us getting the results we did in our sample is that there really is no difference in average mercury levels between all lakes in Northern and Southern Florida, and we just happened, by chance, to select more lakes with higher mercury concentrations in Southern Florida than in Northern Florida. A different possible explanation is that there really is a difference in average mercury level between lakes in Northern and Southern Florida.</p>
<p>In a statistical investigation, the <strong>null hypothesis</strong> is the one that says there is no difference between groups , or no relationship between variables in the larger population, and that any difference/relationship observed in our sample occurred merely by chance. The <strong>alternative hypothesis</strong> contradicts the null hypothesis, stating that there is a difference/relationship.</p>
<p>Stated formally, the hypotheses are:</p>
<p><strong>Null Hypothesis:</strong> There is no difference in average mercury level between all lakes in Northern Florida and all lakes in Southern Florida.</p>
<p><strong>Alternative Hypothesis:</strong> There is a difference in average mercury level between all lakes in Northern Florida and all lakes in Southern Florida.</p>
<p>A statistician’s job is to determine whether the data provide strong enough evidence to rule out the null hypothesis.</p>
<p>The question we need to investigate is:</p>
<p><em>“How likely is it that we would have observed a difference in means (i.e. a value of <span class="math inline">\(b_1\)</span>) as extreme as 0.6965-0.4245 = 0.272 ppm, merely by chance, if there is really no relationship between location and mercury level?”</em></p>
</div>
<div id="permutation-test-for-difference-in-means" class="section level3 hasAnchor" number="3.1.4">
<h3><span class="header-section-number">3.1.4</span> Permutation Test for Difference in Means<a href="hypothesis-testing-via-permutation.html#permutation-test-for-difference-in-means" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can answer the key question using a procedure known as a <strong>permutation test</strong>. In a permutation test, we randomly permute (or shuffle) the values of our explanatory variable to simulate a situation where there is no relationship between our explanatory and response variable. We observe whether it is plausible to observe values of a statistic (in this case the difference in means) as extreme or more extreme than what we saw in the actual data.</p>
<p>We’ll simulate situations where there is no relationship between location and mercury level, and see how often we observe a difference in means (<span class="math inline">\(b_1\)</span>) as extreme as 0.272.</p>
<p><strong>Procedure:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Randomly shuffle the locations of the lakes, so that any relationship between location and mercury level is due only to chance.</p></li>
<li><p>Calculate the difference in mean mercury levels (i.e. value of <span class="math inline">\(b_1\)</span>) in “Northern” and “Southern” lakes, using the shuffled data. The statistic used to measure the size of the difference or relationship in the sample is called the <strong>test statistic.</strong></p></li>
<li><p>Repeat steps 1 and 2 many (say 10,000) times, recording the test statistic (difference in means, <span class="math inline">\(b_1\)</span>) each time.</p></li>
<li><p>Analyze the distribution of the test statistic (mean difference), simulated under the assumption that there is no relationship between location and mercury level. Look whether the value of the test statistic we observed in the sample (0.272) is consistent with values simulated under the assumption that the null hypothesis is true.</p></li>
</ol>
<p>This simulation can be performed using this <a href="http://www.rossmanchance.com/applets/2021/anovashuffle/AnovaShuffle.htm?hideExtras=2">Rossman-Chance App</a>.</p>
</div>
<div id="five-permutations-in-r" class="section level3 hasAnchor" number="3.1.5">
<h3><span class="header-section-number">3.1.5</span> Five Permutations in R<a href="hypothesis-testing-via-permutation.html#five-permutations-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ll use R to perform permutation test.</p>
<p><strong>First Permutation</strong></p>
<p>Recall these groups were randomly assigned, so the only differences in averages are due to random chance.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="hypothesis-testing-via-permutation.html#cb138-1" aria-hidden="true" tabindex="-1"></a>ShuffledLakes <span class="ot">&lt;-</span> FloridaLakes    <span class="co"># create copy of dataset</span></span>
<span id="cb138-2"><a href="hypothesis-testing-via-permutation.html#cb138-2" aria-hidden="true" tabindex="-1"></a>ShuffledLakes<span class="sc">$</span>Location <span class="ot">&lt;-</span> ShuffledLakes<span class="sc">$</span>Location[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledLakes))] </span></code></pre></div>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="hypothesis-testing-via-permutation.html#cb139-1" aria-hidden="true" tabindex="-1"></a>Shuffle1df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(FloridaLakes<span class="sc">$</span>Lake, FloridaLakes<span class="sc">$</span>Location, </span>
<span id="cb139-2"><a href="hypothesis-testing-via-permutation.html#cb139-2" aria-hidden="true" tabindex="-1"></a>                         FloridaLakes<span class="sc">$</span>Mercury, ShuffledLakes<span class="sc">$</span>Location)</span>
<span id="cb139-3"><a href="hypothesis-testing-via-permutation.html#cb139-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Shuffle1df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Lake&quot;</span>, <span class="st">&quot;Location&quot;</span>, <span class="st">&quot;Mercury&quot;</span>, <span class="st">&quot;Shuffled Location&quot;</span>)</span>
<span id="cb139-4"><a href="hypothesis-testing-via-permutation.html#cb139-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(Shuffle1df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Lake</th>
<th align="left">Location</th>
<th align="right">Mercury</th>
<th align="left">Shuffled Location</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Alligator</td>
<td align="left">S</td>
<td align="right">1.23</td>
<td align="left">N</td>
</tr>
<tr class="even">
<td align="left">Annie</td>
<td align="left">S</td>
<td align="right">1.33</td>
<td align="left">S</td>
</tr>
<tr class="odd">
<td align="left">Apopka</td>
<td align="left">N</td>
<td align="right">0.04</td>
<td align="left">S</td>
</tr>
<tr class="even">
<td align="left">Blue Cypress</td>
<td align="left">S</td>
<td align="right">0.44</td>
<td align="left">N</td>
</tr>
<tr class="odd">
<td align="left">Brick</td>
<td align="left">S</td>
<td align="right">1.20</td>
<td align="left">N</td>
</tr>
<tr class="even">
<td align="left">Bryant</td>
<td align="left">N</td>
<td align="right">0.27</td>
<td align="left">N</td>
</tr>
</tbody>
</table>
<p>Notice that the locations of the lakes have now been mixed up and assigned randomly. So, any relationship between location and mercury level will have occurred merely by chance.</p>
<p>We create a boxplot and calculate the difference in mean mercury levels for the shuffled data.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="hypothesis-testing-via-permutation.html#cb140-1" aria-hidden="true" tabindex="-1"></a>LakesPerm <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Shuffle1df, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>, </span>
<span id="cb140-2"><a href="hypothesis-testing-via-permutation.html#cb140-2" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">y=</span>Mercury, <span class="at">fill=</span><span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb140-3"><a href="hypothesis-testing-via-permutation.html#cb140-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span>   <span class="fu">geom_jitter</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Mercury Levels in Florida Lakes&quot;</span>) <span class="sc">+</span> </span>
<span id="cb140-4"><a href="hypothesis-testing-via-permutation.html#cb140-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Location&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Mercury Level&quot;</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1.5</span>)) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span>
<span id="cb140-5"><a href="hypothesis-testing-via-permutation.html#cb140-5" aria-hidden="true" tabindex="-1"></a>LakesPerm</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-113-1.png" width="672" /></p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="hypothesis-testing-via-permutation.html#cb141-1" aria-hidden="true" tabindex="-1"></a>LakesPermTable <span class="ot">&lt;-</span> Shuffle1df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">MeanHg=</span><span class="fu">mean</span>(Mercury), <span class="at">StDevHg=</span><span class="fu">sd</span>(Mercury),  <span class="at">N=</span><span class="fu">n</span>())</span>
<span id="cb141-2"><a href="hypothesis-testing-via-permutation.html#cb141-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(LakesPermTable)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Shuffled Location</th>
<th align="right">MeanHg</th>
<th align="right">StDevHg</th>
<th align="right">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">N</td>
<td align="right">0.5460606</td>
<td align="right">0.3552986</td>
<td align="right">33</td>
</tr>
<tr class="even">
<td align="left">S</td>
<td align="right">0.4960000</td>
<td align="right">0.3225784</td>
<td align="right">20</td>
</tr>
</tbody>
</table>
<p>Notice that the sample means are not identical. We observe a difference of 0.0500606 just by chance associated with the assignment of the lakes to their random location groups.</p>
<p>This difference is considerably smaller than the difference of 0.272 that we saw in the actual data, suggesting that perhaps a difference as big as 0.272 would not be likely to occur by chance. Before we can be sure of this, however, we should repeat our simulation many times to get a better sense for how big of a difference we might reasonable expect to occur just by chance.</p>
<p><strong>Second Permutation</strong></p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="hypothesis-testing-via-permutation.html#cb142-1" aria-hidden="true" tabindex="-1"></a>ShuffledLakes <span class="ot">&lt;-</span> FloridaLakes    <span class="do">## create copy of dataset</span></span>
<span id="cb142-2"><a href="hypothesis-testing-via-permutation.html#cb142-2" aria-hidden="true" tabindex="-1"></a>ShuffledLakes<span class="sc">$</span>Location <span class="ot">&lt;-</span> ShuffledLakes<span class="sc">$</span>Location[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledLakes))] </span>
<span id="cb142-3"><a href="hypothesis-testing-via-permutation.html#cb142-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(Shuffle1df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Lake</th>
<th align="left">Location</th>
<th align="right">Mercury</th>
<th align="left">Shuffled Location</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Alligator</td>
<td align="left">S</td>
<td align="right">1.23</td>
<td align="left">N</td>
</tr>
<tr class="even">
<td align="left">Annie</td>
<td align="left">S</td>
<td align="right">1.33</td>
<td align="left">S</td>
</tr>
<tr class="odd">
<td align="left">Apopka</td>
<td align="left">N</td>
<td align="right">0.04</td>
<td align="left">S</td>
</tr>
<tr class="even">
<td align="left">Blue Cypress</td>
<td align="left">S</td>
<td align="right">0.44</td>
<td align="left">N</td>
</tr>
<tr class="odd">
<td align="left">Brick</td>
<td align="left">S</td>
<td align="right">1.20</td>
<td align="left">N</td>
</tr>
<tr class="even">
<td align="left">Bryant</td>
<td align="left">N</td>
<td align="right">0.27</td>
<td align="left">N</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="hypothesis-testing-via-permutation.html#cb143-1" aria-hidden="true" tabindex="-1"></a>Shuffle1df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(FloridaLakes<span class="sc">$</span>Lake, FloridaLakes<span class="sc">$</span>Location, FloridaLakes<span class="sc">$</span>Mercury, ShuffledLakes<span class="sc">$</span>Location)</span>
<span id="cb143-2"><a href="hypothesis-testing-via-permutation.html#cb143-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Shuffle1df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Lake&quot;</span>, <span class="st">&quot;Location&quot;</span>, <span class="st">&quot;Mercury&quot;</span>, <span class="st">&quot;Shuffled Location&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="hypothesis-testing-via-permutation.html#cb144-1" aria-hidden="true" tabindex="-1"></a>LakesPerm <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Shuffle1df, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>, <span class="at">y=</span>Mercury, <span class="at">fill=</span><span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb144-2"><a href="hypothesis-testing-via-permutation.html#cb144-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span>   <span class="fu">geom_jitter</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Mercury Levels in Florida Lakes&quot;</span>) <span class="sc">+</span> </span>
<span id="cb144-3"><a href="hypothesis-testing-via-permutation.html#cb144-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Location&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Mercury Level&quot;</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1.5</span>)) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span>
<span id="cb144-4"><a href="hypothesis-testing-via-permutation.html#cb144-4" aria-hidden="true" tabindex="-1"></a>LakesPerm</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-117-1.png" width="672" /></p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="hypothesis-testing-via-permutation.html#cb145-1" aria-hidden="true" tabindex="-1"></a>LakesPermTable <span class="ot">&lt;-</span> Shuffle1df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">MeanHg=</span><span class="fu">mean</span>(Mercury), <span class="at">StDevHg=</span><span class="fu">sd</span>(Mercury),  <span class="at">N=</span><span class="fu">n</span>())</span>
<span id="cb145-2"><a href="hypothesis-testing-via-permutation.html#cb145-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(LakesPermTable)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Shuffled Location</th>
<th align="right">MeanHg</th>
<th align="right">StDevHg</th>
<th align="right">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">N</td>
<td align="right">0.4839394</td>
<td align="right">0.3316431</td>
<td align="right">33</td>
</tr>
<tr class="even">
<td align="left">S</td>
<td align="right">0.5985000</td>
<td align="right">0.3527975</td>
<td align="right">20</td>
</tr>
</tbody>
</table>
<p><strong>Third Permutation</strong></p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="hypothesis-testing-via-permutation.html#cb146-1" aria-hidden="true" tabindex="-1"></a>ShuffledLakes <span class="ot">&lt;-</span> FloridaLakes    <span class="do">## create copy of dataset</span></span>
<span id="cb146-2"><a href="hypothesis-testing-via-permutation.html#cb146-2" aria-hidden="true" tabindex="-1"></a>ShuffledLakes<span class="sc">$</span>Location <span class="ot">&lt;-</span> ShuffledLakes<span class="sc">$</span>Location[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledLakes))] </span>
<span id="cb146-3"><a href="hypothesis-testing-via-permutation.html#cb146-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(Shuffle1df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Lake</th>
<th align="left">Location</th>
<th align="right">Mercury</th>
<th align="left">Shuffled Location</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Alligator</td>
<td align="left">S</td>
<td align="right">1.23</td>
<td align="left">S</td>
</tr>
<tr class="even">
<td align="left">Annie</td>
<td align="left">S</td>
<td align="right">1.33</td>
<td align="left">S</td>
</tr>
<tr class="odd">
<td align="left">Apopka</td>
<td align="left">N</td>
<td align="right">0.04</td>
<td align="left">N</td>
</tr>
<tr class="even">
<td align="left">Blue Cypress</td>
<td align="left">S</td>
<td align="right">0.44</td>
<td align="left">S</td>
</tr>
<tr class="odd">
<td align="left">Brick</td>
<td align="left">S</td>
<td align="right">1.20</td>
<td align="left">N</td>
</tr>
<tr class="even">
<td align="left">Bryant</td>
<td align="left">N</td>
<td align="right">0.27</td>
<td align="left">S</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="hypothesis-testing-via-permutation.html#cb147-1" aria-hidden="true" tabindex="-1"></a>Shuffle1df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(FloridaLakes<span class="sc">$</span>Lake, FloridaLakes<span class="sc">$</span>Location, FloridaLakes<span class="sc">$</span>Mercury, ShuffledLakes<span class="sc">$</span>Location)</span>
<span id="cb147-2"><a href="hypothesis-testing-via-permutation.html#cb147-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Shuffle1df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Lake&quot;</span>, <span class="st">&quot;Location&quot;</span>, <span class="st">&quot;Mercury&quot;</span>, <span class="st">&quot;Shuffled Location&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="hypothesis-testing-via-permutation.html#cb148-1" aria-hidden="true" tabindex="-1"></a>LakesPerm <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Shuffle1df, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>, <span class="at">y=</span>Mercury, <span class="at">fill=</span><span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb148-2"><a href="hypothesis-testing-via-permutation.html#cb148-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span>   <span class="fu">geom_jitter</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Mercury Levels in Florida Lakes&quot;</span>) <span class="sc">+</span> </span>
<span id="cb148-3"><a href="hypothesis-testing-via-permutation.html#cb148-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Location&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Mercury Level&quot;</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1.5</span>)) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span>
<span id="cb148-4"><a href="hypothesis-testing-via-permutation.html#cb148-4" aria-hidden="true" tabindex="-1"></a>LakesPerm</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-121-1.png" width="672" /></p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="hypothesis-testing-via-permutation.html#cb149-1" aria-hidden="true" tabindex="-1"></a>LakesPermTable <span class="ot">&lt;-</span> Shuffle1df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">MeanHg=</span><span class="fu">mean</span>(Mercury), <span class="at">StDevHg=</span><span class="fu">sd</span>(Mercury),  <span class="at">N=</span><span class="fu">n</span>())</span>
<span id="cb149-2"><a href="hypothesis-testing-via-permutation.html#cb149-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(LakesPermTable)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Shuffled Location</th>
<th align="right">MeanHg</th>
<th align="right">StDevHg</th>
<th align="right">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">N</td>
<td align="right">0.5324242</td>
<td align="right">0.3863777</td>
<td align="right">33</td>
</tr>
<tr class="even">
<td align="left">S</td>
<td align="right">0.5185000</td>
<td align="right">0.2583607</td>
<td align="right">20</td>
</tr>
</tbody>
</table>
<p><strong>Fourth Permutation</strong></p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="hypothesis-testing-via-permutation.html#cb150-1" aria-hidden="true" tabindex="-1"></a>ShuffledLakes <span class="ot">&lt;-</span> FloridaLakes    <span class="do">## create copy of dataset</span></span>
<span id="cb150-2"><a href="hypothesis-testing-via-permutation.html#cb150-2" aria-hidden="true" tabindex="-1"></a>ShuffledLakes<span class="sc">$</span>Location <span class="ot">&lt;-</span> ShuffledLakes<span class="sc">$</span>Location[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledLakes))] </span>
<span id="cb150-3"><a href="hypothesis-testing-via-permutation.html#cb150-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(Shuffle1df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Lake</th>
<th align="left">Location</th>
<th align="right">Mercury</th>
<th align="left">Shuffled Location</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Alligator</td>
<td align="left">S</td>
<td align="right">1.23</td>
<td align="left">N</td>
</tr>
<tr class="even">
<td align="left">Annie</td>
<td align="left">S</td>
<td align="right">1.33</td>
<td align="left">N</td>
</tr>
<tr class="odd">
<td align="left">Apopka</td>
<td align="left">N</td>
<td align="right">0.04</td>
<td align="left">N</td>
</tr>
<tr class="even">
<td align="left">Blue Cypress</td>
<td align="left">S</td>
<td align="right">0.44</td>
<td align="left">S</td>
</tr>
<tr class="odd">
<td align="left">Brick</td>
<td align="left">S</td>
<td align="right">1.20</td>
<td align="left">N</td>
</tr>
<tr class="even">
<td align="left">Bryant</td>
<td align="left">N</td>
<td align="right">0.27</td>
<td align="left">S</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="hypothesis-testing-via-permutation.html#cb151-1" aria-hidden="true" tabindex="-1"></a>Shuffle1df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(FloridaLakes<span class="sc">$</span>Lake, FloridaLakes<span class="sc">$</span>Location, FloridaLakes<span class="sc">$</span>Mercury, ShuffledLakes<span class="sc">$</span>Location)</span>
<span id="cb151-2"><a href="hypothesis-testing-via-permutation.html#cb151-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Shuffle1df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Lake&quot;</span>, <span class="st">&quot;Location&quot;</span>, <span class="st">&quot;Mercury&quot;</span>, <span class="st">&quot;Shuffled Location&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="hypothesis-testing-via-permutation.html#cb152-1" aria-hidden="true" tabindex="-1"></a>LakesPerm <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Shuffle1df, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>, <span class="at">y=</span>Mercury, <span class="at">fill=</span><span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb152-2"><a href="hypothesis-testing-via-permutation.html#cb152-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span>   <span class="fu">geom_jitter</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Mercury Levels in Florida Lakes&quot;</span>) <span class="sc">+</span> </span>
<span id="cb152-3"><a href="hypothesis-testing-via-permutation.html#cb152-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Location&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Mercury Level&quot;</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1.5</span>)) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span>
<span id="cb152-4"><a href="hypothesis-testing-via-permutation.html#cb152-4" aria-hidden="true" tabindex="-1"></a>LakesPerm</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-125-1.png" width="672" /></p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="hypothesis-testing-via-permutation.html#cb153-1" aria-hidden="true" tabindex="-1"></a>LakesPermTable <span class="ot">&lt;-</span> Shuffle1df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">MeanHg=</span><span class="fu">mean</span>(Mercury), <span class="at">StDevHg=</span><span class="fu">sd</span>(Mercury),  <span class="at">N=</span><span class="fu">n</span>())</span>
<span id="cb153-2"><a href="hypothesis-testing-via-permutation.html#cb153-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(LakesPermTable)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Shuffled Location</th>
<th align="right">MeanHg</th>
<th align="right">StDevHg</th>
<th align="right">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">N</td>
<td align="right">0.4833333</td>
<td align="right">0.3314803</td>
<td align="right">33</td>
</tr>
<tr class="even">
<td align="left">S</td>
<td align="right">0.5995000</td>
<td align="right">0.3527109</td>
<td align="right">20</td>
</tr>
</tbody>
</table>
<p><strong>Fifth Permutation</strong></p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="hypothesis-testing-via-permutation.html#cb154-1" aria-hidden="true" tabindex="-1"></a>ShuffledLakes <span class="ot">&lt;-</span> FloridaLakes    <span class="do">## create copy of dataset</span></span>
<span id="cb154-2"><a href="hypothesis-testing-via-permutation.html#cb154-2" aria-hidden="true" tabindex="-1"></a>ShuffledLakes<span class="sc">$</span>Location <span class="ot">&lt;-</span> ShuffledLakes<span class="sc">$</span>Location[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledLakes))] </span>
<span id="cb154-3"><a href="hypothesis-testing-via-permutation.html#cb154-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(Shuffle1df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Lake</th>
<th align="left">Location</th>
<th align="right">Mercury</th>
<th align="left">Shuffled Location</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Alligator</td>
<td align="left">S</td>
<td align="right">1.23</td>
<td align="left">N</td>
</tr>
<tr class="even">
<td align="left">Annie</td>
<td align="left">S</td>
<td align="right">1.33</td>
<td align="left">S</td>
</tr>
<tr class="odd">
<td align="left">Apopka</td>
<td align="left">N</td>
<td align="right">0.04</td>
<td align="left">N</td>
</tr>
<tr class="even">
<td align="left">Blue Cypress</td>
<td align="left">S</td>
<td align="right">0.44</td>
<td align="left">N</td>
</tr>
<tr class="odd">
<td align="left">Brick</td>
<td align="left">S</td>
<td align="right">1.20</td>
<td align="left">N</td>
</tr>
<tr class="even">
<td align="left">Bryant</td>
<td align="left">N</td>
<td align="right">0.27</td>
<td align="left">S</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="hypothesis-testing-via-permutation.html#cb155-1" aria-hidden="true" tabindex="-1"></a>Shuffle1df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(FloridaLakes<span class="sc">$</span>Lake, FloridaLakes<span class="sc">$</span>Location, FloridaLakes<span class="sc">$</span>Mercury, ShuffledLakes<span class="sc">$</span>Location)</span>
<span id="cb155-2"><a href="hypothesis-testing-via-permutation.html#cb155-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Shuffle1df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Lake&quot;</span>, <span class="st">&quot;Location&quot;</span>, <span class="st">&quot;Mercury&quot;</span>, <span class="st">&quot;Shuffled Location&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="hypothesis-testing-via-permutation.html#cb156-1" aria-hidden="true" tabindex="-1"></a>LakesPerm <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Shuffle1df, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>, <span class="at">y=</span>Mercury, <span class="at">fill=</span><span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb156-2"><a href="hypothesis-testing-via-permutation.html#cb156-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span>   <span class="fu">geom_jitter</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Mercury Levels in Florida Lakes&quot;</span>) <span class="sc">+</span> </span>
<span id="cb156-3"><a href="hypothesis-testing-via-permutation.html#cb156-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Location&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Mercury Level&quot;</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1.5</span>)) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span>
<span id="cb156-4"><a href="hypothesis-testing-via-permutation.html#cb156-4" aria-hidden="true" tabindex="-1"></a>LakesPerm</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-129-1.png" width="672" /></p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="hypothesis-testing-via-permutation.html#cb157-1" aria-hidden="true" tabindex="-1"></a>LakesPermTable <span class="ot">&lt;-</span> Shuffle1df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Shuffled Location</span><span class="st">`</span>) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">MeanHg=</span><span class="fu">mean</span>(Mercury), <span class="at">StDevHg=</span><span class="fu">sd</span>(Mercury),  <span class="at">N=</span><span class="fu">n</span>())</span>
<span id="cb157-2"><a href="hypothesis-testing-via-permutation.html#cb157-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(LakesPermTable)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Shuffled Location</th>
<th align="right">MeanHg</th>
<th align="right">StDevHg</th>
<th align="right">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">N</td>
<td align="right">0.5642424</td>
<td align="right">0.3259508</td>
<td align="right">33</td>
</tr>
<tr class="even">
<td align="left">S</td>
<td align="right">0.4660000</td>
<td align="right">0.3647551</td>
<td align="right">20</td>
</tr>
</tbody>
</table>
</div>
<div id="r-code-for-permutation-test" class="section level3 hasAnchor" number="3.1.6">
<h3><span class="header-section-number">3.1.6</span> R Code for Permutation Test<a href="hypothesis-testing-via-permutation.html#r-code-for-permutation-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ll write a <code>for</code> loop to perform 10,000 permutations and record the value of <span class="math inline">\(b_1\)</span> (the difference in sample means) for each simulation.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="hypothesis-testing-via-permutation.html#cb158-1" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> Lakes_M<span class="sc">$</span>coef[<span class="dv">2</span>] <span class="do">## record value of b1 from actual data</span></span>
<span id="cb158-2"><a href="hypothesis-testing-via-permutation.html#cb158-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb158-3"><a href="hypothesis-testing-via-permutation.html#cb158-3" aria-hidden="true" tabindex="-1"></a><span class="do">## perform simulation</span></span>
<span id="cb158-4"><a href="hypothesis-testing-via-permutation.html#cb158-4" aria-hidden="true" tabindex="-1"></a>b1Sim <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">10000</span>)          <span class="do">## vector to hold results</span></span>
<span id="cb158-5"><a href="hypothesis-testing-via-permutation.html#cb158-5" aria-hidden="true" tabindex="-1"></a>ShuffledLakes <span class="ot">&lt;-</span> FloridaLakes    <span class="do">## create copy of dataset</span></span>
<span id="cb158-6"><a href="hypothesis-testing-via-permutation.html#cb158-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>){</span>
<span id="cb158-7"><a href="hypothesis-testing-via-permutation.html#cb158-7" aria-hidden="true" tabindex="-1"></a>  <span class="co">#randomly shuffle locations</span></span>
<span id="cb158-8"><a href="hypothesis-testing-via-permutation.html#cb158-8" aria-hidden="true" tabindex="-1"></a>ShuffledLakes<span class="sc">$</span>Location <span class="ot">&lt;-</span> ShuffledLakes<span class="sc">$</span>Location[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledLakes))] </span>
<span id="cb158-9"><a href="hypothesis-testing-via-permutation.html#cb158-9" aria-hidden="true" tabindex="-1"></a>ShuffledLakes_M<span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>ShuffledLakes, Mercury <span class="sc">~</span> Location)   <span class="co">#fit model to shuffled data</span></span>
<span id="cb158-10"><a href="hypothesis-testing-via-permutation.html#cb158-10" aria-hidden="true" tabindex="-1"></a>b1Sim[i] <span class="ot">&lt;-</span> ShuffledLakes_M<span class="sc">$</span>coef[<span class="dv">2</span>]  <span class="do">## record b1 from shuffled model</span></span>
<span id="cb158-11"><a href="hypothesis-testing-via-permutation.html#cb158-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb158-12"><a href="hypothesis-testing-via-permutation.html#cb158-12" aria-hidden="true" tabindex="-1"></a>NSLakes_SimulationResults <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(b1Sim)  <span class="co">#save results in dataframe</span></span></code></pre></div>
<p>The histogram shows the distribution of differences in the group means observed in our simulation. The red lines indicate the difference we actually observed in the data (0.272), as well as an equally large difference in the opposite direction (-0.272).</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="hypothesis-testing-via-permutation.html#cb159-1" aria-hidden="true" tabindex="-1"></a>NSLakes_SimulationResultsPlot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>NSLakes_SimulationResults, </span>
<span id="cb159-2"><a href="hypothesis-testing-via-permutation.html#cb159-2" aria-hidden="true" tabindex="-1"></a>                                        <span class="fu">aes</span>(<span class="at">x=</span>b1Sim)) <span class="sc">+</span> </span>
<span id="cb159-3"><a href="hypothesis-testing-via-permutation.html#cb159-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">&quot;lightblue&quot;</span>, <span class="at">color=</span><span class="st">&quot;white&quot;</span>) <span class="sc">+</span> </span>
<span id="cb159-4"><a href="hypothesis-testing-via-permutation.html#cb159-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">c</span>(b1, <span class="sc">-</span><span class="dv">1</span><span class="sc">*</span>b1), <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb159-5"><a href="hypothesis-testing-via-permutation.html#cb159-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Lakes: Simulated Value of b1&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Frequency&quot;</span>) <span class="sc">+</span> </span>
<span id="cb159-6"><a href="hypothesis-testing-via-permutation.html#cb159-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Distribution of b1 under assumption of no relationship&quot;</span>)</span>
<span id="cb159-7"><a href="hypothesis-testing-via-permutation.html#cb159-7" aria-hidden="true" tabindex="-1"></a>NSLakes_SimulationResultsPlot</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-132-1.png" width="672" /></p>
<p>The red lines are quite extreme, relative to the simulated values shown in the histogram. Based on the simulation, it is rare to obtain a difference as extreme as the 0.272 value we saw in the actual data, by chance when there is actually no difference in average mercury levels between Northern and Southern Florida lakes.</p>
<p>We calculate the precise number of simulations (out of 10,000) resulting in difference in means more extreme than 0.27195.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="hypothesis-testing-via-permutation.html#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(b1Sim) <span class="sc">&gt;</span> <span class="fu">abs</span>(b1))</span></code></pre></div>
<pre><code>## [1] 39</code></pre>
<p>The proportion of simulations resulting in difference in means more extreme than 0.272 is:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="hypothesis-testing-via-permutation.html#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(b1Sim) <span class="sc">&gt;</span> <span class="fu">abs</span>(b1))<span class="sc">/</span><span class="dv">10000</span></span></code></pre></div>
<pre><code>## [1] 0.0039</code></pre>
<p>We only observed a difference between the groups as extreme or more extreme than the 0.272 difference we saw in the sample in a proportion of 0.0039 of our simulations (less than 1%).</p>
<p>It is very unlikely that we would have gotten a difference as extreme as 0.272 by chance when there is no relationship between location and mercury level is very low. Thus, we have strong evidence that there is a difference in average mercury level between lakes in Northern and Southern Florida. In this case, there is strong evidence that mercury level is higher in Southern Florida lakes than Northern Florida lakes.</p>
</div>
<div id="p-values" class="section level3 hasAnchor" number="3.1.7">
<h3><span class="header-section-number">3.1.7</span> p-values<a href="hypothesis-testing-via-permutation.html#p-values" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <strong>p-value</strong> represents the probability of getting a test statistic as extreme or more extreme than we did in our sample when the null hypothesis is true.</p>
<p>In our study, the p-value was 0.0039, which is very low. This provides strong evidence against the null hypothesis that there is no difference in average mercury levels between all Northern and Southern Florida lakes.</p>
<p>A low p-value tells us that the difference in average Mercury levels that we saw in our sample is unlikely to have occurred by chance, providing evidence that there is indeed a difference in average Mercury levels between Northern and Southern lakes.</p>
<p>The p-value does not tell us anything about the size of the difference! If the difference is really small (say 0.001 ppm), perhaps there is no need to worry about it. It is possible to get a small p-value even when the true difference is very small (especially when our sample size is large). In addition to a p-value, we should consider whether a difference is big enough to be meaningful in a practical way, before making any policy decisions.</p>
<p>For now, we can use the difference in sample means of 0.272 ppm as an estimate of the size of the difference. Based on our limited knowledge of mercury levels, this does seem big enough to merit further investigation, and possible action.</p>
<p>At this point, a reasonable question is “how small must a p-value be in order to provide evidence against the null hypothesis?” While it is sometimes common to establish strict cutoffs for what counts as a small p-value (such as <span class="math inline">\(&lt;0.05\)</span>), the American Statistical Association does not recommend this. In reality, a p-value of 0.04 is practically no different than a p-value of 0.06. Rather than using strict cutoffs for what counts as small, it is better to interpreting p-values on a sliding scale, as illustrated in the diagram below. A p-value of 0.10 or less provides at least some evidence against a null hypothesis, and the smaller the p-value is, the stronger the evidence gets.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="hypothesis-testing-via-permutation.html#cb164-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">&quot;pvals.png&quot;</span>)</span></code></pre></div>
<p><img src="pvals.png" width="100%" /></p>
</div>
</div>
<div id="general-permutation-tests" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> General Permutation Tests<a href="hypothesis-testing-via-permutation.html#general-permutation-tests" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="other-test-statistics" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Other Test Statistics<a href="hypothesis-testing-via-permutation.html#other-test-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The permutation test procedure can be used to test hypotheses involving lots of different test statistics, in addition to testing for a difference in means, as we saw seen in the previous section. For example we could test whether there is evidence of:</p>
<ol style="list-style-type: decimal">
<li><p>a difference in the median mercury level between lakes in Northern Florida, compared to southern Florida</p></li>
<li><p>a difference in the amount of variability in mercury levels between lakes in Northern Florida, compared to southern Florida<br />
</p></li>
<li><p>a difference in the proportion of lakes whose mercury level exceeds 1 ppm between lakes in Northern Florida, compared to southern Florida<br />
</p></li>
<li><p>a difference in mean price between King County houses in very good, good, and average or below conditions</p></li>
<li><p>a relationship between mercury level and pH level among all Florida lakes</p></li>
</ol>
<p>For each of these investigations, the null hypothesis will be that there is no difference or relationship among all lakes (that is, whatever difference or relationship occurred in the sample occurred just by random chance). We’ll need to find a test statistic that measures the quantity we’re interested in (for example, difference in means). Then, we use the permutation procedure to simulate a scenario where our null hypothesis is true, and see if test statistic we saw in our data is consistent with the ones we simulate under the null hypothesis.</p>
</div>
<div id="general-permutation-test-procedure" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> General Permutation Test Procedure<a href="hypothesis-testing-via-permutation.html#general-permutation-test-procedure" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Procedure:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Randomly shuffle the values or categories of the explanatory variable, so that any relationship between the explanatory and response variable occurs just by chance.</p></li>
<li><p>Calculate the test statistic on the shuffled data.</p></li>
<li><p>Repeat steps 1 and 2 many (say 10,000) times, recording the test statistic each time.</p></li>
<li><p>Analyze the distribution of the test statistic, simulated under the assumption that the null hypothesis is true. Look whether the value of the test statistic we observed in the sample is consistent with values simulated under the assumption that the null hypothesis is true. (We might calculate a p-value, which represents the proportion of simulations in which we observed a test statistic as extreme or more extreme than the one we saw in our actual sample.)</p></li>
</ol>
<p>Next, we’ll apply these steps to questions 2, 4, and 5 from the previous subsection.</p>
</div>
<div id="difference-in-standard-deviation" class="section level3 hasAnchor" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Difference in Standard Deviation<a href="hypothesis-testing-via-permutation.html#difference-in-standard-deviation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ll test whether there is evidence of a difference in variability between lakes in Northern Florida, compared to Southern Florida. Since standard deviation is a measure of variability, we’ll use the difference in standard deviation in Northern vs Southern lakes as our test statistic.</p>
<p>Recall that the standard deviation among the 53 Northern Florida Lakes in our sample was 0.270 ppm, which is lower than the 0.384 ppm in Southern Florida.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="hypothesis-testing-via-permutation.html#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(LakesTable)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Location</th>
<th align="right">MeanHg</th>
<th align="right">StDevHg</th>
<th align="right">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">N</td>
<td align="right">0.4245455</td>
<td align="right">0.2696652</td>
<td align="right">33</td>
</tr>
<tr class="even">
<td align="left">S</td>
<td align="right">0.6965000</td>
<td align="right">0.3838760</td>
<td align="right">20</td>
</tr>
</tbody>
</table>
<p>The test statistic we observe in our sample is <span class="math inline">\(0.2696-0.3839 = -0.1142\)</span> ppm.</p>
<p>We need to determine whether a difference this large could have plausibly occurred in our sample, just by chance, if there is really no difference in standard deviation among all lakes in Northern Florida, compared to Southern Florida.</p>
<p><strong>Null Hypothesis:</strong> There is no difference in standard deviation of mercury levels between all lakes in Northern Florida and all lakes in Southern Florida.</p>
<p><strong>Alternative Hypothesis:</strong> There is a difference in standard deviation of mercury levels between all lakes in Northern Florida and all lakes in Southern Florida.</p>
<p>We’ll apply the general hypothesis testing procedure, using standard deviation as our test statistic.</p>
<p><strong>Procedure:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Randomly shuffle the locations of the lakes, so that any relationship between the location and mercury level occurs just by chance.</p></li>
<li><p>Calculate the difference in standard deviation between lakes in the two samples of the shuffled data.</p></li>
<li><p>Repeat steps 1 and 2 many (say 10,000) times, recording the difference in standard deviations each time.</p></li>
<li><p>Analyze the distribution of difference in standard deviations, simulated under the assumption that there is no difference in standard deviations between North and South. Look whether the value of the test statistic we observed in the sample is consistent with values simulated under the assumption that there is no difference in standard deviations.</p></li>
</ol>
<p><strong>R Code for Permutation Test</strong></p>
<p>We’ll write a <code>for</code> loop to perform 10,000 permutations and record the value of <span class="math inline">\(b_1\)</span> (the difference in sample means) for each simulation.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="hypothesis-testing-via-permutation.html#cb166-1" aria-hidden="true" tabindex="-1"></a>SDTab <span class="ot">&lt;-</span> FloridaLakes <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Location) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">SD=</span><span class="fu">sd</span>(Mercury))</span>
<span id="cb166-2"><a href="hypothesis-testing-via-permutation.html#cb166-2" aria-hidden="true" tabindex="-1"></a>DiffSD <span class="ot">&lt;-</span> SDTab<span class="sc">$</span>SD[<span class="dv">2</span>] <span class="sc">-</span> SDTab<span class="sc">$</span>SD[<span class="dv">1</span>] </span>
<span id="cb166-3"><a href="hypothesis-testing-via-permutation.html#cb166-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb166-4"><a href="hypothesis-testing-via-permutation.html#cb166-4" aria-hidden="true" tabindex="-1"></a><span class="do">## perform simulation</span></span>
<span id="cb166-5"><a href="hypothesis-testing-via-permutation.html#cb166-5" aria-hidden="true" tabindex="-1"></a>DiffSim <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">10000</span>)          <span class="do">## vector to hold results</span></span>
<span id="cb166-6"><a href="hypothesis-testing-via-permutation.html#cb166-6" aria-hidden="true" tabindex="-1"></a>ShuffledLakes <span class="ot">&lt;-</span> FloridaLakes    <span class="do">## create copy of dataset</span></span>
<span id="cb166-7"><a href="hypothesis-testing-via-permutation.html#cb166-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>){</span>
<span id="cb166-8"><a href="hypothesis-testing-via-permutation.html#cb166-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#randomly shuffle locations</span></span>
<span id="cb166-9"><a href="hypothesis-testing-via-permutation.html#cb166-9" aria-hidden="true" tabindex="-1"></a>ShuffledLakes<span class="sc">$</span>Location <span class="ot">&lt;-</span> ShuffledLakes<span class="sc">$</span>Location[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledLakes))] </span>
<span id="cb166-10"><a href="hypothesis-testing-via-permutation.html#cb166-10" aria-hidden="true" tabindex="-1"></a>SDTabSim <span class="ot">&lt;-</span> ShuffledLakes <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Location) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">SD=</span><span class="fu">sd</span>(Mercury))</span>
<span id="cb166-11"><a href="hypothesis-testing-via-permutation.html#cb166-11" aria-hidden="true" tabindex="-1"></a>DiffSim[i] <span class="ot">&lt;-</span> SDTabSim<span class="sc">$</span>SD[<span class="dv">2</span>] <span class="sc">-</span> SDTabSim<span class="sc">$</span>SD[<span class="dv">1</span>] <span class="co">#record difference in SD for simulated data</span></span>
<span id="cb166-12"><a href="hypothesis-testing-via-permutation.html#cb166-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb166-13"><a href="hypothesis-testing-via-permutation.html#cb166-13" aria-hidden="true" tabindex="-1"></a>NSLakes_SDSimResults <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(DiffSim)  <span class="co">#save results in dataframe</span></span></code></pre></div>
<p>The distribution of the simulated differences in standard deviation is shown below. Recall that these were simulated assuming that the null hypothesis, that there is no difference in standard deviation of mercury levels among all lakes in Northern Florida, compared to Southern Florida is true.</p>
<p>The red lines represent differences as extreme as -0.1142 that we saw in our sample.</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="hypothesis-testing-via-permutation.html#cb167-1" aria-hidden="true" tabindex="-1"></a>NSLakes_SDSimResultsPlot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>NSLakes_SDSimResults, <span class="fu">aes</span>(<span class="at">x=</span>DiffSim)) <span class="sc">+</span> </span>
<span id="cb167-2"><a href="hypothesis-testing-via-permutation.html#cb167-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">&quot;lightblue&quot;</span>, <span class="at">color=</span><span class="st">&quot;white&quot;</span>) <span class="sc">+</span> </span>
<span id="cb167-3"><a href="hypothesis-testing-via-permutation.html#cb167-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">c</span>(DiffSD, <span class="sc">-</span><span class="dv">1</span><span class="sc">*</span>DiffSD), <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb167-4"><a href="hypothesis-testing-via-permutation.html#cb167-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Simulated Difference in SD&#39;s&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Frequency&quot;</span>) <span class="sc">+</span> </span>
<span id="cb167-5"><a href="hypothesis-testing-via-permutation.html#cb167-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Distribution of Difference in SD under assumption of no relationship&quot;</span>)</span>
<span id="cb167-6"><a href="hypothesis-testing-via-permutation.html#cb167-6" aria-hidden="true" tabindex="-1"></a>NSLakes_SDSimResultsPlot</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-138-1.png" width="672" /></p>
<p>We calculate the number of simulations (out of 10,000) resulting in standard deviations greater the 0.1142.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="hypothesis-testing-via-permutation.html#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(DiffSim) <span class="sc">&gt;</span> <span class="fu">abs</span>(DiffSD))</span></code></pre></div>
<pre><code>## [1] 612</code></pre>
<p><strong>p-value:</strong> Proportion of simulations (out of 10,000) resulting in difference in standard deviations greater the 0.1142.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="hypothesis-testing-via-permutation.html#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(DiffSim) <span class="sc">&gt;</span> <span class="fu">abs</span>(DiffSD))</span></code></pre></div>
<pre><code>## [1] 0.0612</code></pre>
<p>This p-value represents the probability of observing a difference in sample standard deviations as extreme as 0.1142 in a samples of size 33 and 20 by chance, if in fact, the standard deviation in mercury concentration levels is the same for lakes in Northern Florida as in Southern Florida.</p>
<p>Since the p-value is small, it is unlikely that we would observe a difference in standard deviations as extreme as 0.1142 by chance. There is evidence that lakes in Southern Florida exhibit more variability in mercury levels than lakes in Northern Florida (though the evidence is not as strong as it was when we were testing for a difference in means).</p>
<p>Note that we have avoided the fallacy of using 0.05 as a strict cutoff for rejecting the null hypothesis.</p>
<p>Although the difference in standard deviations is statistically discernible, it is hard to say whether it is practically meaningful. Without knowing a lot about mercury levels, and their impact on the ecosystem, it’s harder to tell whether an estimated difference in standard deviations of 0.11 ppm is meaningful or not. It would be good to consult a biologist before making any decisions based on these results.</p>
</div>
<div id="permutation-test-for-slope" class="section level3 hasAnchor" number="3.2.4">
<h3><span class="header-section-number">3.2.4</span> Permutation Test for Slope<a href="hypothesis-testing-via-permutation.html#permutation-test-for-slope" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In addition to the mercury levels of the Florida lakes, we have data on the pH level of each lake. pH level measures the acidity of a lake, ranging from 0 to 14, with 7 being neutral, and lower levels indicating more acidity. We plot the pH level against the mercury level in our sample of 53 lakes.</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="hypothesis-testing-via-permutation.html#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>FloridaLakes, <span class="fu">aes</span>(<span class="at">y=</span>Mercury, <span class="at">x=</span>pH)) <span class="sc">+</span> </span>
<span id="cb172-2"><a href="hypothesis-testing-via-permutation.html#cb172-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb172-3"><a href="hypothesis-testing-via-permutation.html#cb172-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">10</span>)) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">1.5</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-141-1.png" width="672" /></p>
<p>The regression equation is</p>
<p><span class="math display">\[
\widehat{\text{Mercury}} = b_0 + b_1\times\text{pH}
\]</span></p>
<p>Regression estimates <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are shown below.</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="hypothesis-testing-via-permutation.html#cb173-1" aria-hidden="true" tabindex="-1"></a>Lakes_M_pH <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>FloridaLakes, Mercury<span class="sc">~</span>pH)</span>
<span id="cb173-2"><a href="hypothesis-testing-via-permutation.html#cb173-2" aria-hidden="true" tabindex="-1"></a>Lakes_M_pH</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Mercury ~ pH, data = FloridaLakes)
## 
## Coefficients:
## (Intercept)           pH  
##      1.5309      -0.1523</code></pre>
<p>We can use the slope of the regression line <span class="math inline">\(b_1\)</span> to measure the strength relationship between Mercury and pH. Based on our sample, each one-unit increase in pH, mercury level is expected to decrease by 0.15 ppm.</p>
<p>If there was really no relationship, then the slope among all lakes would be 0. But, of course, we would not expect the slope in our sample to exactly match the slope for all lakes. Our question of interest is whether it is plausible that we could have randomly selected a sample resulting in a slope as extreme as 0.15 by chance, when there is actually no relationship between mercury and pH levels, among all lakes. In other words, could we plausible have drawn the sample of 53 lakes shown in blue from a population like the one in red, shown below?</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-143-1.png" width="672" /></p>
<p><strong>Key Question:</strong></p>
<ul>
<li>How likely is it that we would have observed a slope (i.e. a value of <span class="math inline">\(b_1\)</span>) as extreme as 0.15 by chance, if there is really no relationship between mercury level and pH?</li>
</ul>
<p><strong>Null Hypothesis:</strong> Among all Florida lakes, there is no relationship between mercury level and pH.</p>
<p><strong>Alternative Hypothesis:</strong> Among all Florida lakes, there is a relationship between mercury level and pH.</p>
<p><strong>Procedure:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Randomly shuffle the pH values, so that any relationship between acceleration mercury and pH is due only to chance.</p></li>
<li><p>Fit a regression line to the shuffled data and record the slope of the regression line.</p></li>
<li><p>Repeat steps 1 and 2 many (say 10,000) times, recording the slope (i.e. value of <span class="math inline">\(b_1\)</span>) each time.</p></li>
<li><p>Analyze the distribution of slopes, simulated under the assumption that there is no relationship between mercury and pH. Look whether the actual slope we observed is consistent with the simulation results.</p></li>
</ol>
<p>We’ll illustrate the first three permutations.</p>
<p><strong>First Permutation</strong></p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="hypothesis-testing-via-permutation.html#cb175-1" aria-hidden="true" tabindex="-1"></a>ShuffledLakes <span class="ot">&lt;-</span> FloridaLakes    <span class="do">## create copy of dataset</span></span>
<span id="cb175-2"><a href="hypothesis-testing-via-permutation.html#cb175-2" aria-hidden="true" tabindex="-1"></a>ShuffledLakes<span class="sc">$</span>pH <span class="ot">&lt;-</span> ShuffledLakes<span class="sc">$</span>pH[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledLakes))] </span></code></pre></div>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="hypothesis-testing-via-permutation.html#cb176-1" aria-hidden="true" tabindex="-1"></a>Shuffle1df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(ShuffledLakes<span class="sc">$</span>Lake, FloridaLakes<span class="sc">$</span>Mercury, FloridaLakes<span class="sc">$</span>pH, ShuffledLakes<span class="sc">$</span>pH)</span>
<span id="cb176-2"><a href="hypothesis-testing-via-permutation.html#cb176-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Shuffle1df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Lake&quot;</span>, <span class="st">&quot;Mercury&quot;</span>, <span class="st">&quot;pH&quot;</span>, <span class="st">&quot;Shuffled_pH&quot;</span>)</span>
<span id="cb176-3"><a href="hypothesis-testing-via-permutation.html#cb176-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(Shuffle1df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Lake</th>
<th align="right">Mercury</th>
<th align="right">pH</th>
<th align="right">Shuffled_pH</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Alligator</td>
<td align="right">1.23</td>
<td align="right">6.1</td>
<td align="right">8.3</td>
</tr>
<tr class="even">
<td align="left">Annie</td>
<td align="right">1.33</td>
<td align="right">5.1</td>
<td align="right">7.8</td>
</tr>
<tr class="odd">
<td align="left">Apopka</td>
<td align="right">0.04</td>
<td align="right">9.1</td>
<td align="right">7.2</td>
</tr>
<tr class="even">
<td align="left">Blue Cypress</td>
<td align="right">0.44</td>
<td align="right">6.9</td>
<td align="right">6.7</td>
</tr>
<tr class="odd">
<td align="left">Brick</td>
<td align="right">1.20</td>
<td align="right">4.6</td>
<td align="right">7.6</td>
</tr>
<tr class="even">
<td align="left">Bryant</td>
<td align="right">0.27</td>
<td align="right">7.3</td>
<td align="right">3.6</td>
</tr>
</tbody>
</table>
<p>The red line indicates the slope of the regression line fit to the shuffled data. The blue line indicates the regression line for the actual lakes in the sampe, which has a slope of -0.15.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="hypothesis-testing-via-permutation.html#cb177-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Shuffle1df, <span class="fu">aes</span>(<span class="at">x=</span>Shuffled_pH, <span class="at">y=</span>Mercury)) <span class="sc">+</span> </span>
<span id="cb177-2"><a href="hypothesis-testing-via-permutation.html#cb177-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb177-3"><a href="hypothesis-testing-via-permutation.html#cb177-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">10</span>)) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">1.5</span>)) <span class="sc">+</span> </span>
<span id="cb177-4"><a href="hypothesis-testing-via-permutation.html#cb177-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="sc">-</span><span class="fl">0.1523</span>, <span class="at">intercept=</span><span class="fl">1.5309</span>, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-146-1.png" width="672" /></p>
<p>Slope of regression line from permuted data:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="hypothesis-testing-via-permutation.html#cb178-1" aria-hidden="true" tabindex="-1"></a>M_Lakes_Shuffle <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Shuffle1df, Mercury<span class="sc">~</span>Shuffled_pH)</span>
<span id="cb178-2"><a href="hypothesis-testing-via-permutation.html#cb178-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Lakes_Shuffle)<span class="sc">$</span>coef[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 0.03177036</code></pre>
<p><strong>Second Permutation</strong></p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="hypothesis-testing-via-permutation.html#cb180-1" aria-hidden="true" tabindex="-1"></a>ShuffledLakes <span class="ot">&lt;-</span> FloridaLakes    <span class="do">## create copy of dataset</span></span>
<span id="cb180-2"><a href="hypothesis-testing-via-permutation.html#cb180-2" aria-hidden="true" tabindex="-1"></a>ShuffledLakes<span class="sc">$</span>pH <span class="ot">&lt;-</span> ShuffledLakes<span class="sc">$</span>pH[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledLakes))] </span></code></pre></div>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="hypothesis-testing-via-permutation.html#cb181-1" aria-hidden="true" tabindex="-1"></a>Shuffle2df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(ShuffledLakes<span class="sc">$</span>Lake, FloridaLakes<span class="sc">$</span>Mercury, FloridaLakes<span class="sc">$</span>pH, ShuffledLakes<span class="sc">$</span>pH)</span>
<span id="cb181-2"><a href="hypothesis-testing-via-permutation.html#cb181-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Shuffle2df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Lake&quot;</span>, <span class="st">&quot;Mercury&quot;</span>, <span class="st">&quot;pH&quot;</span>, <span class="st">&quot;Shuffled_pH&quot;</span>)</span>
<span id="cb181-3"><a href="hypothesis-testing-via-permutation.html#cb181-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(Shuffle2df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Lake</th>
<th align="right">Mercury</th>
<th align="right">pH</th>
<th align="right">Shuffled_pH</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Alligator</td>
<td align="right">1.23</td>
<td align="right">6.1</td>
<td align="right">7.9</td>
</tr>
<tr class="even">
<td align="left">Annie</td>
<td align="right">1.33</td>
<td align="right">5.1</td>
<td align="right">8.3</td>
</tr>
<tr class="odd">
<td align="left">Apopka</td>
<td align="right">0.04</td>
<td align="right">9.1</td>
<td align="right">5.2</td>
</tr>
<tr class="even">
<td align="left">Blue Cypress</td>
<td align="right">0.44</td>
<td align="right">6.9</td>
<td align="right">4.6</td>
</tr>
<tr class="odd">
<td align="left">Brick</td>
<td align="right">1.20</td>
<td align="right">4.6</td>
<td align="right">6.1</td>
</tr>
<tr class="even">
<td align="left">Bryant</td>
<td align="right">0.27</td>
<td align="right">7.3</td>
<td align="right">9.1</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="hypothesis-testing-via-permutation.html#cb182-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Shuffle2df, <span class="fu">aes</span>(<span class="at">x=</span>Shuffled_pH, <span class="at">y=</span>Mercury)) <span class="sc">+</span> </span>
<span id="cb182-2"><a href="hypothesis-testing-via-permutation.html#cb182-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb182-3"><a href="hypothesis-testing-via-permutation.html#cb182-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">10</span>)) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">1.5</span>)) <span class="sc">+</span> </span>
<span id="cb182-4"><a href="hypothesis-testing-via-permutation.html#cb182-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="sc">-</span><span class="fl">0.1523</span>, <span class="at">intercept=</span><span class="fl">1.5309</span>, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-150-1.png" width="672" /></p>
<p>Slope of regression line from permuted data:</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="hypothesis-testing-via-permutation.html#cb183-1" aria-hidden="true" tabindex="-1"></a>M_Lakes_Shuffle <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Shuffle2df, Mercury<span class="sc">~</span>Shuffled_pH)</span>
<span id="cb183-2"><a href="hypothesis-testing-via-permutation.html#cb183-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Lakes_Shuffle)<span class="sc">$</span>coef[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 0.04657482</code></pre>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="hypothesis-testing-via-permutation.html#cb185-1" aria-hidden="true" tabindex="-1"></a>ShuffledLakes <span class="ot">&lt;-</span> FloridaLakes    <span class="do">## create copy of dataset</span></span>
<span id="cb185-2"><a href="hypothesis-testing-via-permutation.html#cb185-2" aria-hidden="true" tabindex="-1"></a>ShuffledLakes<span class="sc">$</span>pH <span class="ot">&lt;-</span> ShuffledLakes<span class="sc">$</span>pH[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledLakes))] </span></code></pre></div>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="hypothesis-testing-via-permutation.html#cb186-1" aria-hidden="true" tabindex="-1"></a>Shuffle3df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(ShuffledLakes<span class="sc">$</span>Lake, FloridaLakes<span class="sc">$</span>Mercury, FloridaLakes<span class="sc">$</span>pH, ShuffledLakes<span class="sc">$</span>pH)</span>
<span id="cb186-2"><a href="hypothesis-testing-via-permutation.html#cb186-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Shuffle3df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Lake&quot;</span>, <span class="st">&quot;Mercury&quot;</span>, <span class="st">&quot;pH&quot;</span>, <span class="st">&quot;Shuffled_pH&quot;</span>)</span>
<span id="cb186-3"><a href="hypothesis-testing-via-permutation.html#cb186-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(Shuffle3df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Lake</th>
<th align="right">Mercury</th>
<th align="right">pH</th>
<th align="right">Shuffled_pH</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Alligator</td>
<td align="right">1.23</td>
<td align="right">6.1</td>
<td align="right">6.9</td>
</tr>
<tr class="even">
<td align="left">Annie</td>
<td align="right">1.33</td>
<td align="right">5.1</td>
<td align="right">7.1</td>
</tr>
<tr class="odd">
<td align="left">Apopka</td>
<td align="right">0.04</td>
<td align="right">9.1</td>
<td align="right">7.2</td>
</tr>
<tr class="even">
<td align="left">Blue Cypress</td>
<td align="right">0.44</td>
<td align="right">6.9</td>
<td align="right">7.9</td>
</tr>
<tr class="odd">
<td align="left">Brick</td>
<td align="right">1.20</td>
<td align="right">4.6</td>
<td align="right">7.5</td>
</tr>
<tr class="even">
<td align="left">Bryant</td>
<td align="right">0.27</td>
<td align="right">7.3</td>
<td align="right">6.8</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="hypothesis-testing-via-permutation.html#cb187-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Shuffle3df, <span class="fu">aes</span>(<span class="at">x=</span>Shuffled_pH, <span class="at">y=</span>Mercury)) <span class="sc">+</span> </span>
<span id="cb187-2"><a href="hypothesis-testing-via-permutation.html#cb187-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb187-3"><a href="hypothesis-testing-via-permutation.html#cb187-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">10</span>)) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">1.5</span>)) <span class="sc">+</span> </span>
<span id="cb187-4"><a href="hypothesis-testing-via-permutation.html#cb187-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="sc">-</span><span class="fl">0.1523</span>, <span class="at">intercept=</span><span class="fl">1.5309</span>, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-154-1.png" width="672" /></p>
<p>Slope of regression line from permuted data:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="hypothesis-testing-via-permutation.html#cb188-1" aria-hidden="true" tabindex="-1"></a>M_Lakes_Shuffle <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Shuffle3df, Mercury<span class="sc">~</span>Shuffled_pH)</span>
<span id="cb188-2"><a href="hypothesis-testing-via-permutation.html#cb188-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Lakes_Shuffle)<span class="sc">$</span>coef[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 0.05767238</code></pre>
<p>None of our three simulations resulted in a slope near as extreme as the -0.15 that we saw in the actual data. This seems to suggest that it is unlikely that we would have observed a slope as extreme as -0.15 if there is actually no relationship between mercury and pH among all lakes.</p>
<p>That said, we should repeat the simulation many more times to see whether getting a slope as extreme as -0.15 is plausible.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="hypothesis-testing-via-permutation.html#cb190-1" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> Lakes_M_pH<span class="sc">$</span>coef[<span class="dv">2</span>] <span class="do">## record value of b1 from actual data</span></span>
<span id="cb190-2"><a href="hypothesis-testing-via-permutation.html#cb190-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb190-3"><a href="hypothesis-testing-via-permutation.html#cb190-3" aria-hidden="true" tabindex="-1"></a><span class="do">## perform simulation</span></span>
<span id="cb190-4"><a href="hypothesis-testing-via-permutation.html#cb190-4" aria-hidden="true" tabindex="-1"></a>b1Sim <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">10000</span>)          <span class="do">## vector to hold results</span></span>
<span id="cb190-5"><a href="hypothesis-testing-via-permutation.html#cb190-5" aria-hidden="true" tabindex="-1"></a>ShuffledLakes <span class="ot">&lt;-</span> FloridaLakes    <span class="do">## create copy of dataset</span></span>
<span id="cb190-6"><a href="hypothesis-testing-via-permutation.html#cb190-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>){</span>
<span id="cb190-7"><a href="hypothesis-testing-via-permutation.html#cb190-7" aria-hidden="true" tabindex="-1"></a>  <span class="co">#randomly shuffle acceleration times</span></span>
<span id="cb190-8"><a href="hypothesis-testing-via-permutation.html#cb190-8" aria-hidden="true" tabindex="-1"></a>ShuffledLakes<span class="sc">$</span>pH <span class="ot">&lt;-</span> ShuffledLakes<span class="sc">$</span>pH[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledLakes))] </span>
<span id="cb190-9"><a href="hypothesis-testing-via-permutation.html#cb190-9" aria-hidden="true" tabindex="-1"></a>ShuffledLakes_M<span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>ShuffledLakes, Mercury <span class="sc">~</span> pH)   <span class="co">#fit model to shuffled data</span></span>
<span id="cb190-10"><a href="hypothesis-testing-via-permutation.html#cb190-10" aria-hidden="true" tabindex="-1"></a>b1Sim[i] <span class="ot">&lt;-</span> ShuffledLakes_M<span class="sc">$</span>coef[<span class="dv">2</span>]  <span class="do">## record b1 from shuffled model</span></span>
<span id="cb190-11"><a href="hypothesis-testing-via-permutation.html#cb190-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb190-12"><a href="hypothesis-testing-via-permutation.html#cb190-12" aria-hidden="true" tabindex="-1"></a>Lakes_pHSimulationResults <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(b1Sim)  <span class="co">#save results in dataframe</span></span></code></pre></div>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="hypothesis-testing-via-permutation.html#cb191-1" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> Lakes_M_pH<span class="sc">$</span>coef[<span class="dv">2</span>] <span class="do">## record value of b1 from actual data</span></span>
<span id="cb191-2"><a href="hypothesis-testing-via-permutation.html#cb191-2" aria-hidden="true" tabindex="-1"></a>Lakes_pHSimulationResultsPlot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Lakes_pHSimulationResults, <span class="fu">aes</span>(<span class="at">x=</span>b1Sim)) <span class="sc">+</span> </span>
<span id="cb191-3"><a href="hypothesis-testing-via-permutation.html#cb191-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">&quot;lightblue&quot;</span>, <span class="at">color=</span><span class="st">&quot;white&quot;</span>) <span class="sc">+</span> </span>
<span id="cb191-4"><a href="hypothesis-testing-via-permutation.html#cb191-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">c</span>(b1, <span class="sc">-</span><span class="dv">1</span><span class="sc">*</span>b1), <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb191-5"><a href="hypothesis-testing-via-permutation.html#cb191-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Simulated Value of b1&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Frequency&quot;</span>) <span class="sc">+</span> </span>
<span id="cb191-6"><a href="hypothesis-testing-via-permutation.html#cb191-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Distribution of b1 under assumption of no relationship&quot;</span>)</span>
<span id="cb191-7"><a href="hypothesis-testing-via-permutation.html#cb191-7" aria-hidden="true" tabindex="-1"></a>Lakes_pHSimulationResultsPlot</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-157-1.png" width="672" /></p>
<p><strong>p-value:</strong> Proportion of simulations resulting in value of <span class="math inline">\(b_1\)</span> more extreme than -0.15</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="hypothesis-testing-via-permutation.html#cb192-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(b1Sim) <span class="sc">&gt;</span> <span class="fu">abs</span>(b1))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>The p-value represents the probability of observing a slope as extreme or more extreme than -0.15 by chance when there is actually no relationship between mercury level and pH.</p>
<p>It is extremely unlikely that we would observe a value of <span class="math inline">\(b_1\)</span> as extreme as -0.15 by chance, if there is really no relationship between mercury level and pH. In fact, this never happened in any of our 10,000 simulations!</p>
<p>There is very strong evidence of a relationship mercury level and pH.</p>
<p>A low p-value tells us only that there is evidence of a relationship, not that it is practically meaningful. We have seen that for each one-unit increase in pH, mercury level is expected to decrease by 0.15 ppm on average, which seems like a pretty meaningful decrease, especially considering that mercury levels typically stay between 0 and 1.</p>
<p>We used the slope as our test statistic to measure the evidence of the relationship between the explanatory and response variables. In fact, we could have also used the correlation coefficient <span class="math inline">\(r\)</span> as our test statistic, and we would have gotten the same p-value. Either slope or correlation may be used for a hypothesis test involving two quantitative variables, but we will use slope in this class.</p>
</div>
<div id="f-statistic" class="section level3 hasAnchor" number="3.2.5">
<h3><span class="header-section-number">3.2.5</span> F-Statistic<a href="hypothesis-testing-via-permutation.html#f-statistic" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall when we examined the prices of houses in King County, WA, whose conditions were rated as either very good, good, or average or below. Suppose we want to test the hypotheses:</p>
<p><strong>Null Hypothesis:</strong> There is no difference in average prices between houses of the three different conditions, among all houses in King County, WA.</p>
<p><strong>Alternative Hypothesis:</strong> There is a difference in average prices between houses of the three different conditions, among all houses in King County, WA.</p>
<p>Comparative boxplots are shown below.</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="hypothesis-testing-via-permutation.html#cb194-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Houses, <span class="fu">aes</span>(<span class="at">x=</span>condition, <span class="at">y=</span>price, <span class="at">fill=</span>condition)) <span class="sc">+</span> </span>
<span id="cb194-2"><a href="hypothesis-testing-via-permutation.html#cb194-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">coord_flip</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Houses&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-159-1.png" width="672" /></p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="hypothesis-testing-via-permutation.html#cb195-1" aria-hidden="true" tabindex="-1"></a>Cond_Tab <span class="ot">&lt;-</span> Houses <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(condition) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">Mean_Price =</span> <span class="fu">mean</span>(price), </span>
<span id="cb195-2"><a href="hypothesis-testing-via-permutation.html#cb195-2" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">SD_Price=</span> <span class="fu">sd</span> (price), </span>
<span id="cb195-3"><a href="hypothesis-testing-via-permutation.html#cb195-3" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">N=</span> <span class="fu">n</span>())</span>
<span id="cb195-4"><a href="hypothesis-testing-via-permutation.html#cb195-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(Cond_Tab)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">condition</th>
<th align="right">Mean_Price</th>
<th align="right">SD_Price</th>
<th align="right">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">average or below</td>
<td align="right">700.6349</td>
<td align="right">768.1179</td>
<td align="right">61</td>
</tr>
<tr class="even">
<td align="left">good</td>
<td align="right">861.0000</td>
<td align="right">1048.9521</td>
<td align="right">30</td>
</tr>
<tr class="odd">
<td align="left">very_good</td>
<td align="right">551.8361</td>
<td align="right">332.8597</td>
<td align="right">9</td>
</tr>
</tbody>
</table>
<p>We notice differences in price. Surprisingly, houses in good condition cost more than 300 thousand dollars more than those in very good condition, on average.</p>
<p>If we were only comparing two groups, we could use the difference in average price between them as a test statistic. But since we’re comparing three, we need a statistic that can measure the size of differences between all three groups. An F-statistic can do this, so we’ll use the F-statistic as our test statistic here.</p>
<p>We calculated the F-statistic in the previous chapter.</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="hypothesis-testing-via-permutation.html#cb196-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(M_House_Cond, M0_House)<span class="sc">$</span>F[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 0.6046888</code></pre>
<p>Our question of interest is “How likely is it to observe an F-statistic as extreme or more extreme than 0.605 if there is actually no difference in average price between houses of the three conditions?”</p>
<p>We’ll use a permutation-based hypothesis test to investigate this question.</p>
<p><strong>Procedure:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Randomly shuffle the conditions of the houses, so that any relationship between condition and price is due only to chance.</p></li>
<li><p>Using the shuffled data, calculate an F-statistic for a predicting price, comparing a full model that uses condition as an explanatory variable, to a reduced model with no explanatory variables.</p></li>
<li><p>Repeat steps 1 and 2 many (say 10,000) times, recording the F-statistic each time.</p></li>
<li><p>Analyze the distribution of F-statistics, simulated under the assumption that there is no relationship between condition and price. Look whether the actual F-statistic we observed is consistent with the simulation results.</p></li>
</ol>
<p>We’ll illustrate the first three permutations.</p>
<p><strong>First Permutation</strong></p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="hypothesis-testing-via-permutation.html#cb198-1" aria-hidden="true" tabindex="-1"></a>ShuffledHouses <span class="ot">&lt;-</span> Houses    <span class="do">## create copy of dataset</span></span>
<span id="cb198-2"><a href="hypothesis-testing-via-permutation.html#cb198-2" aria-hidden="true" tabindex="-1"></a>ShuffledHouses<span class="sc">$</span>condition <span class="ot">&lt;-</span> ShuffledHouses<span class="sc">$</span>condition[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledHouses))] </span></code></pre></div>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="hypothesis-testing-via-permutation.html#cb199-1" aria-hidden="true" tabindex="-1"></a>Shuffle1df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Houses<span class="sc">$</span>Id, Houses<span class="sc">$</span>price, Houses<span class="sc">$</span>condition, ShuffledHouses<span class="sc">$</span>condition)</span>
<span id="cb199-2"><a href="hypothesis-testing-via-permutation.html#cb199-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Shuffle1df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Id&quot;</span>, <span class="st">&quot;price&quot;</span>, <span class="st">&quot;condition&quot;</span>, <span class="st">&quot;Shuffled_Condition&quot;</span>)</span>
<span id="cb199-3"><a href="hypothesis-testing-via-permutation.html#cb199-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(Shuffle1df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">Id</th>
<th align="right">price</th>
<th align="left">condition</th>
<th align="left">Shuffled_Condition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1225.0</td>
<td align="left">average or below</td>
<td align="left">average or below</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">885.0</td>
<td align="left">average or below</td>
<td align="left">average or below</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">385.0</td>
<td align="left">good</td>
<td align="left">average or below</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">252.7</td>
<td align="left">average or below</td>
<td align="left">very_good</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">468.0</td>
<td align="left">good</td>
<td align="left">average or below</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">310.0</td>
<td align="left">good</td>
<td align="left">good</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="hypothesis-testing-via-permutation.html#cb200-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>ShuffledHouses, <span class="fu">aes</span>(<span class="at">x=</span>condition, <span class="at">y=</span>price, <span class="at">fill=</span>condition)) <span class="sc">+</span> </span>
<span id="cb200-2"><a href="hypothesis-testing-via-permutation.html#cb200-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">coord_flip</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Shuffled Houses&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-164-1.png" width="672" /></p>
<p>We fit a model to predict price using condition, and compare it to one that predicts price without using condition, and calculate the F-statistic.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="hypothesis-testing-via-permutation.html#cb201-1" aria-hidden="true" tabindex="-1"></a>M1_Shuffled_Houses <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>ShuffledHouses, price<span class="sc">~</span>condition)</span>
<span id="cb201-2"><a href="hypothesis-testing-via-permutation.html#cb201-2" aria-hidden="true" tabindex="-1"></a>M0_Shuffled_Houses <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>ShuffledHouses, price<span class="sc">~</span><span class="dv">1</span>)</span>
<span id="cb201-3"><a href="hypothesis-testing-via-permutation.html#cb201-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(M1_Shuffled_Houses, M0_Shuffled_Houses)<span class="sc">$</span>F[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 0.7510288</code></pre>
<p><strong>Second Permutation</strong></p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="hypothesis-testing-via-permutation.html#cb203-1" aria-hidden="true" tabindex="-1"></a>ShuffledHouses <span class="ot">&lt;-</span> Houses    <span class="do">## create copy of dataset</span></span>
<span id="cb203-2"><a href="hypothesis-testing-via-permutation.html#cb203-2" aria-hidden="true" tabindex="-1"></a>ShuffledHouses<span class="sc">$</span>condition <span class="ot">&lt;-</span> ShuffledHouses<span class="sc">$</span>condition[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledHouses))] </span></code></pre></div>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="hypothesis-testing-via-permutation.html#cb204-1" aria-hidden="true" tabindex="-1"></a>Shuffle2df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Houses<span class="sc">$</span>Id, Houses<span class="sc">$</span>price, Houses<span class="sc">$</span>condition, ShuffledHouses<span class="sc">$</span>condition)</span>
<span id="cb204-2"><a href="hypothesis-testing-via-permutation.html#cb204-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Shuffle2df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Id&quot;</span>, <span class="st">&quot;price&quot;</span>, <span class="st">&quot;condition&quot;</span>, <span class="st">&quot;Shuffled_Condition&quot;</span>)</span>
<span id="cb204-3"><a href="hypothesis-testing-via-permutation.html#cb204-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(Shuffle2df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">Id</th>
<th align="right">price</th>
<th align="left">condition</th>
<th align="left">Shuffled_Condition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1225.0</td>
<td align="left">average or below</td>
<td align="left">average or below</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">885.0</td>
<td align="left">average or below</td>
<td align="left">good</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">385.0</td>
<td align="left">good</td>
<td align="left">average or below</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">252.7</td>
<td align="left">average or below</td>
<td align="left">average or below</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">468.0</td>
<td align="left">good</td>
<td align="left">good</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">310.0</td>
<td align="left">good</td>
<td align="left">good</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="hypothesis-testing-via-permutation.html#cb205-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>ShuffledHouses, <span class="fu">aes</span>(<span class="at">x=</span>condition, <span class="at">y=</span>price, <span class="at">fill=</span>condition)) <span class="sc">+</span> </span>
<span id="cb205-2"><a href="hypothesis-testing-via-permutation.html#cb205-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">coord_flip</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Shuffled Houses&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-168-1.png" width="672" /></p>
<p>We fit a model to predict price using condition, and compare it to one that predicts price without using condition, and calculate the F-statistic.</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="hypothesis-testing-via-permutation.html#cb206-1" aria-hidden="true" tabindex="-1"></a>M1_Shuffled_Houses <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>ShuffledHouses, price<span class="sc">~</span>condition)</span>
<span id="cb206-2"><a href="hypothesis-testing-via-permutation.html#cb206-2" aria-hidden="true" tabindex="-1"></a>M0_Shuffled_Houses <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>ShuffledHouses, price<span class="sc">~</span><span class="dv">1</span>)</span>
<span id="cb206-3"><a href="hypothesis-testing-via-permutation.html#cb206-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(M1_Shuffled_Houses, M0_Shuffled_Houses)<span class="sc">$</span>F[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 0.204532</code></pre>
<p><strong>Third Permutation</strong></p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="hypothesis-testing-via-permutation.html#cb208-1" aria-hidden="true" tabindex="-1"></a>ShuffledHouses <span class="ot">&lt;-</span> Houses    <span class="do">## create copy of dataset</span></span>
<span id="cb208-2"><a href="hypothesis-testing-via-permutation.html#cb208-2" aria-hidden="true" tabindex="-1"></a>ShuffledHouses<span class="sc">$</span>condition <span class="ot">&lt;-</span> ShuffledHouses<span class="sc">$</span>condition[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledHouses))] </span></code></pre></div>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="hypothesis-testing-via-permutation.html#cb209-1" aria-hidden="true" tabindex="-1"></a>Shuffle3df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Houses<span class="sc">$</span>Id, Houses<span class="sc">$</span>price, Houses<span class="sc">$</span>condition, ShuffledHouses<span class="sc">$</span>condition)</span>
<span id="cb209-2"><a href="hypothesis-testing-via-permutation.html#cb209-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Shuffle3df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Id&quot;</span>, <span class="st">&quot;price&quot;</span>, <span class="st">&quot;condition&quot;</span>, <span class="st">&quot;Shuffled_Condition&quot;</span>)</span>
<span id="cb209-3"><a href="hypothesis-testing-via-permutation.html#cb209-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(Shuffle1df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">Id</th>
<th align="right">price</th>
<th align="left">condition</th>
<th align="left">Shuffled_Condition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1225.0</td>
<td align="left">average or below</td>
<td align="left">average or below</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">885.0</td>
<td align="left">average or below</td>
<td align="left">average or below</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">385.0</td>
<td align="left">good</td>
<td align="left">average or below</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">252.7</td>
<td align="left">average or below</td>
<td align="left">very_good</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">468.0</td>
<td align="left">good</td>
<td align="left">average or below</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">310.0</td>
<td align="left">good</td>
<td align="left">good</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="hypothesis-testing-via-permutation.html#cb210-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>ShuffledHouses, <span class="fu">aes</span>(<span class="at">x=</span>condition, <span class="at">y=</span>price, <span class="at">fill=</span>condition)) <span class="sc">+</span> </span>
<span id="cb210-2"><a href="hypothesis-testing-via-permutation.html#cb210-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">coord_flip</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Shuffled Houses&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-172-1.png" width="672" /></p>
<p>We fit a model to predict price using condition, and compare it to one that predicts price without using condition, and calculate the F-statistic.</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="hypothesis-testing-via-permutation.html#cb211-1" aria-hidden="true" tabindex="-1"></a>M1_Shuffled_Houses <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>ShuffledHouses, price<span class="sc">~</span>condition)</span>
<span id="cb211-2"><a href="hypothesis-testing-via-permutation.html#cb211-2" aria-hidden="true" tabindex="-1"></a>M0_Shuffled_Houses <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>ShuffledHouses, price<span class="sc">~</span><span class="dv">1</span>)</span>
<span id="cb211-3"><a href="hypothesis-testing-via-permutation.html#cb211-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(M1_Shuffled_Houses, M0_Shuffled_Houses)<span class="sc">$</span>F[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 0.5485496</code></pre>
<p>We’ll simulate 10,000 permutations and record the F-statistic for each set of permuted data.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="hypothesis-testing-via-permutation.html#cb213-1" aria-hidden="true" tabindex="-1"></a>Fstat <span class="ot">&lt;-</span> <span class="fu">anova</span>(M_House_Cond, M0_House)<span class="sc">$</span>F[<span class="dv">2</span>] <span class="do">## record value of F-statistic from actual data</span></span>
<span id="cb213-2"><a href="hypothesis-testing-via-permutation.html#cb213-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb213-3"><a href="hypothesis-testing-via-permutation.html#cb213-3" aria-hidden="true" tabindex="-1"></a><span class="do">## perform simulation</span></span>
<span id="cb213-4"><a href="hypothesis-testing-via-permutation.html#cb213-4" aria-hidden="true" tabindex="-1"></a>FSim <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">10000</span>)          <span class="do">## vector to hold results</span></span>
<span id="cb213-5"><a href="hypothesis-testing-via-permutation.html#cb213-5" aria-hidden="true" tabindex="-1"></a>ShuffledHouses <span class="ot">&lt;-</span> Houses    <span class="do">## create copy of dataset</span></span>
<span id="cb213-6"><a href="hypothesis-testing-via-permutation.html#cb213-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>){</span>
<span id="cb213-7"><a href="hypothesis-testing-via-permutation.html#cb213-7" aria-hidden="true" tabindex="-1"></a>  <span class="co">#randomly shuffle acceleration times</span></span>
<span id="cb213-8"><a href="hypothesis-testing-via-permutation.html#cb213-8" aria-hidden="true" tabindex="-1"></a>ShuffledHouses<span class="sc">$</span>condition <span class="ot">&lt;-</span> ShuffledHouses<span class="sc">$</span>condition[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ShuffledHouses))] </span>
<span id="cb213-9"><a href="hypothesis-testing-via-permutation.html#cb213-9" aria-hidden="true" tabindex="-1"></a>ShuffledHouses_M1<span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>ShuffledHouses, price <span class="sc">~</span> condition)  <span class="co">#fit full model to shuffled data</span></span>
<span id="cb213-10"><a href="hypothesis-testing-via-permutation.html#cb213-10" aria-hidden="true" tabindex="-1"></a>ShuffledHouses_M0<span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>ShuffledHouses, price <span class="sc">~</span> <span class="dv">1</span>)  <span class="co">#fit reduced model to shuffled data</span></span>
<span id="cb213-11"><a href="hypothesis-testing-via-permutation.html#cb213-11" aria-hidden="true" tabindex="-1"></a>FSim[i] <span class="ot">&lt;-</span> <span class="fu">anova</span>(ShuffledHouses_M1, ShuffledHouses_M0)<span class="sc">$</span>F[<span class="dv">2</span>]  <span class="do">## record F from shuffled model</span></span>
<span id="cb213-12"><a href="hypothesis-testing-via-permutation.html#cb213-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb213-13"><a href="hypothesis-testing-via-permutation.html#cb213-13" aria-hidden="true" tabindex="-1"></a>House_Cond_SimulationResults <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(FSim)  <span class="co">#save results in dataframe</span></span></code></pre></div>
<p>The distribution of the F-statistics is shown below. Recall that these are simulated under the assumption that there is no difference in average price between houses of the three different conditions, i.e. no relationship between price and condition.</p>
<p>The red line shows the location of the F-statistic we saw in our data (0.60). Since F-statistics cannot be negative, we don’t need to worry about finding an F-statistic as extreme in the opposite direction.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="hypothesis-testing-via-permutation.html#cb214-1" aria-hidden="true" tabindex="-1"></a>House_Cond_SimulationResults_Plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>House_Cond_SimulationResults, </span>
<span id="cb214-2"><a href="hypothesis-testing-via-permutation.html#cb214-2" aria-hidden="true" tabindex="-1"></a>                                            <span class="fu">aes</span>(<span class="at">x=</span>FSim)) <span class="sc">+</span> </span>
<span id="cb214-3"><a href="hypothesis-testing-via-permutation.html#cb214-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill=</span><span class="st">&quot;lightblue&quot;</span>, <span class="at">color=</span><span class="st">&quot;white&quot;</span>) <span class="sc">+</span>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">c</span>(Fstat), <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb214-4"><a href="hypothesis-testing-via-permutation.html#cb214-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Simulated Value of F&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Frequency&quot;</span>) <span class="sc">+</span>  <span class="fu">ggtitle</span>(<span class="st">&quot;Distribution of F under assumption of no relationship&quot;</span>)</span>
<span id="cb214-5"><a href="hypothesis-testing-via-permutation.html#cb214-5" aria-hidden="true" tabindex="-1"></a>House_Cond_SimulationResults_Plot</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-175-1.png" width="672" /></p>
<p>The F-statistic in our actual we observed does not appear to be very extreme.</p>
<p><strong>p-value:</strong> Proportion of simulations resulting in value of F more extreme than 0.60.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="hypothesis-testing-via-permutation.html#cb215-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(FSim <span class="sc">&gt;</span> Fstat)</span></code></pre></div>
<pre><code>## [1] 0.5568</code></pre>
<p>The p-value represents the probability of observing an F-statistic as extreme as 0.60 by chance, in samples of size 61, 30, and 9, if in fact there is no relationship between price and size of car.</p>
<p>More than half of our simulations resulted in an F-statistic as extreme or more extreme than the one we saw in our actual data, even though the simulation was performed in a situation where there was no relationship between price and condition. Thus, it is very plausible that we would observe an F-statistic as extreme or more extreme than we saw in our data, even if there is no relationship between price and condition (or no difference in average price between the conditions), among all houses.</p>
<p>Since the p-value is large, we cannot reject the null hypothesis. We do not have evidence to say that average price differs between houses of the different condition types.</p>
<p>It is important to note that we are not saying that we believe the average price is the same for each condition. Recall that the average prices among the conditions in our sample differed by more than 300 thousand dollars! It’s just that given the size of our samples, and the amount of variability in our data, we cannot rule out the possibility that this difference occurred purely by chance.</p>
</div>
</div>
<div id="responsible-hypothesis-testing" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Responsible Hypothesis Testing<a href="hypothesis-testing-via-permutation.html#responsible-hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>While hypothesis tests are a powerful tool in statistics, they are also one that has been widely misused, to the detriment of scientific research. The hard caused by these misuses caused the American Statistical Association to release a <a href="https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf">2016 statement</a>, intended to provide guidance and clarification to scientists who use hypothesis testing and p-values in their research.</p>
<p>The statement provides the following six principles for responsible use of hypothesis tests and p-values.</p>
<ol style="list-style-type: decimal">
<li><p>P-values can indicate how incompatible the data are with a specified statistical model.</p></li>
<li><p>P-values do not measure the probability that the studied hypothesis is true, or the probability that the data were produced by random chance alone.</p></li>
<li><p>Scientific conclusions and business or policy decisions should not be based only on whether a p-value passes a specific threshold.</p></li>
<li><p>Proper inference requires full reporting and transparency.</p></li>
<li><p>A p-value, or statistical significance, does not measure the size of an effect or the importance of a result.</p></li>
<li><p>By itself, a p-value does not provide a good measure of evidence regarding a model or hypothesis.</p></li>
</ol>
<p>The statement provides important guidance for us to consider as we work with hypothesis testing in this class, as well as in future classes and potentially in our own research.</p>
<ul>
<li><p>A hypothesis test can only tell us the strength of evidence against the null hypothesis. The absence of evidence against the null hypothesis should not be interpreted as evidence for the null hypothesis.</p></li>
<li><p>We should never say that the data support/prove/confirm the null hypothesis.</p></li>
<li><p>We can only say that the data do not provide evidence against the null hypothesis.</p></li>
</ul>
<p><strong>What to conclude from p-values and what not to:</strong></p>
<ul>
<li><p>A low p-value provides evidence against the null hypothesis. It suggests the test statistic we observed is inconsistent with the null hypothesis.</p></li>
<li><p>A low p-value does <strong>not</strong> tell us that the difference or relationship we observed is meaningful in a practical sense. Researchers should look at the size of the difference or strength of the relationship in the sample before deciding whether it merits being acted upon.</p></li>
<li><p>A high p-value means that the data could have plausibly been obtained when the null hypothesis is true. The test statistic we observed is consistent with what we would have expected to see when the null hypothesis is true, and thus we cannot rule out the null hypothesis.</p></li>
<li><p>A high p-value does <strong>not</strong> mean that the null hypothesis is true or probably true. A p-value can only tell us the strength of evidence against the null hypothesis, and should never be interpreted as support for the null hypothesis.</p></li>
</ul>
<p>Just because our result is consistent with the null hypothesis does not mean that we should believe that null hypothesis is true. Lack of evidence against a claim does not necessarily mean that the claim is true.</p>
<p>In this scenario, we got a small p-value, but we should also be aware of what we should conclude if the p-value is large. Remember that the p-value only measures the strength of evidence <em>against</em> the null hypothesis. A large p-value means we lack evidence against the null hypothesis. This does not mean, however, that we have evidence <em>supporting</em> null hypothesis.</p>
<p>A hypothesis test can be thought of as being analogous to a courtroom trial, where the null hypothesis is that the defendant did not commit the crime. Suppose that after each side presents evidence, the jury remains unsure whether the defendant committed the crime. Since the jury does not have enough evidence to be sure, they must, under the law of the United States find the defendant “not guilty.” This does not mean that the jury thinks the defendant is innocent, only that they do not have enough evidence to be sure they are guilty. Similarly in a hypothesis test, a large p-value indicates a lack of evidence against the null hypothesis, rather than evidence supporting it. As such, we should avoid statements suggesting we “support”, “accept”, or “believe” the null hypothesis, and simply state that we lack evidence against it.</p>
<p><strong>Things to say when the p-value is large:</strong></p>
<ul>
<li>The data are consistent with the null hypothesis.<br />
</li>
<li>We do not have enough evidence against the null hypothesis.<br />
</li>
<li>We cannot reject the null hypothesis.<br />
</li>
<li>The null hypothesis is plausible.</li>
</ul>
<p><strong>Things NOT to say when the p-value is large:</strong></p>
<ul>
<li>The data support the null hypothesis.<br />
</li>
<li>The data provide evidence for the null hypothesis.<br />
</li>
<li>We accept the null hypothesis.<br />
</li>
<li>We conclude that the null hypothesis is true.</li>
</ul>
<p>Thus, if we had obtained a large p-value in the comparison in mercury levels between Northern and Southern lakes, the appropriate conclusion would be</p>
<p>“We do not have evidence that the average mercury level differs between lakes in Northern Florida, compared to Southern Florida.”</p>
<p>Even if we got a large p-value it would be incorrect to say “There is no difference in average mercury levels between lakes in Northern Florida and Southern Florida.”</p>
<p>We would just be saying that given the size of our sample and the amount of variability on the date, we cannot rule out the possibility of observing a difference like we did by chance, when there really is no difference.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-statistical-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="bootstrap-interval-estimation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Stat255-LU/Notes/edit/master/03-Hypothesis_Testing.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/Stat255-LU/Notes/blob/master/03-Hypothesis_Testing.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
