<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Normal Error Regression Model | Stat 255: Statistics for Data Science Notes</title>
  <meta name="description" content="Chapter 5 Normal Error Regression Model | Stat 255: Statistics for Data Science Notes" />
  <meta name="generator" content="bookdown 0.31 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Normal Error Regression Model | Stat 255: Statistics for Data Science Notes" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Normal Error Regression Model | Stat 255: Statistics for Data Science Notes" />
  
  
  

<meta name="author" content="Andrew Sage - Lawrence University" />


<meta name="date" content="2023-10-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="bootstrap-interval-estimation.html"/>
<link rel="next" href="model-building.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STAT 255 Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html"><i class="fa fa-check"></i><b>1</b> Exploratory Data Analysis</a>
<ul>
<li class="chapter" data-level="1.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#getting-started-in-r"><i class="fa fa-check"></i><b>1.1</b> Getting Started in R</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#previewing-the-data"><i class="fa fa-check"></i><b>1.1.1</b> Previewing the Data</a></li>
<li class="chapter" data-level="1.1.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#modifying-the-data"><i class="fa fa-check"></i><b>1.1.2</b> Modifying the Data</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#data-visualization"><i class="fa fa-check"></i><b>1.2</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#histogram"><i class="fa fa-check"></i><b>1.2.1</b> Histogram</a></li>
<li class="chapter" data-level="1.2.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#density-plot"><i class="fa fa-check"></i><b>1.2.2</b> Density Plot</a></li>
<li class="chapter" data-level="1.2.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#boxplot"><i class="fa fa-check"></i><b>1.2.3</b> Boxplot</a></li>
<li class="chapter" data-level="1.2.4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#violin-plot"><i class="fa fa-check"></i><b>1.2.4</b> Violin Plot</a></li>
<li class="chapter" data-level="1.2.5" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#scatterplot"><i class="fa fa-check"></i><b>1.2.5</b> Scatterplot</a></li>
<li class="chapter" data-level="1.2.6" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#bar-graph"><i class="fa fa-check"></i><b>1.2.6</b> Bar Graph</a></li>
<li class="chapter" data-level="1.2.7" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#stacked-and-side-by-side-bar-graphs"><i class="fa fa-check"></i><b>1.2.7</b> Stacked and Side-by-Side Bar Graphs</a></li>
<li class="chapter" data-level="1.2.8" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#correlation-plot"><i class="fa fa-check"></i><b>1.2.8</b> Correlation Plot</a></li>
<li class="chapter" data-level="1.2.9" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#scatterplot-matrix"><i class="fa fa-check"></i><b>1.2.9</b> Scatterplot Matrix</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#summary-tables"><i class="fa fa-check"></i><b>1.3</b> Summary Tables</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#calculating-summary-statistics"><i class="fa fa-check"></i><b>1.3.1</b> Calculating Summary Statistics</a></li>
<li class="chapter" data-level="1.3.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#grouped-summaries"><i class="fa fa-check"></i><b>1.3.2</b> Grouped Summaries</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html"><i class="fa fa-check"></i><b>2</b> Introduction to Statistical Models</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#fitting-models-to-data"><i class="fa fa-check"></i><b>2.1</b> Fitting Models to Data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#terminology"><i class="fa fa-check"></i><b>2.1.1</b> Terminology</a></li>
<li class="chapter" data-level="2.1.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-with-quantitative-explanatory-variable"><i class="fa fa-check"></i><b>2.1.2</b> Model with Quantitative Explanatory Variable</a></li>
<li class="chapter" data-level="2.1.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-with-categorical-variable"><i class="fa fa-check"></i><b>2.1.3</b> Model with Categorical Variable</a></li>
<li class="chapter" data-level="2.1.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-with-multiple-explanatory-variables"><i class="fa fa-check"></i><b>2.1.4</b> Model with Multiple Explanatory Variables</a></li>
<li class="chapter" data-level="2.1.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-with-no-explanatory-variable"><i class="fa fa-check"></i><b>2.1.5</b> Model with No Explanatory Variable</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#variability-explained-by-a-model"><i class="fa fa-check"></i><b>2.2</b> Variability Explained by a Model</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#quantifying-variability"><i class="fa fa-check"></i><b>2.2.1</b> Quantifying Variability</a></li>
<li class="chapter" data-level="2.2.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#total-variability"><i class="fa fa-check"></i><b>2.2.2</b> Total Variability</a></li>
<li class="chapter" data-level="2.2.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#residuals"><i class="fa fa-check"></i><b>2.2.3</b> Residuals</a></li>
<li class="chapter" data-level="2.2.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#variability-explained-by-sq.-ft.-model"><i class="fa fa-check"></i><b>2.2.4</b> Variability Explained by Sq. Ft. Model</a></li>
<li class="chapter" data-level="2.2.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#linear-correlation-coefficient"><i class="fa fa-check"></i><b>2.2.5</b> Linear Correlation Coefficient</a></li>
<li class="chapter" data-level="2.2.6" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#variability-explained-by-waterfront-model"><i class="fa fa-check"></i><b>2.2.6</b> Variability Explained by Waterfront Model</a></li>
<li class="chapter" data-level="2.2.7" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#variability-explained-by-multiple-regression-model"><i class="fa fa-check"></i><b>2.2.7</b> Variability Explained by Multiple Regression Model</a></li>
<li class="chapter" data-level="2.2.8" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#summary-sst-ssr-ssm-r2"><i class="fa fa-check"></i><b>2.2.8</b> Summary: SST, SSR, SSM, <span class="math inline">\(R^2\)</span></a></li>
<li class="chapter" data-level="2.2.9" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#r2-visually"><i class="fa fa-check"></i><b>2.2.9</b> <span class="math inline">\(R^2\)</span> Visually</a></li>
<li class="chapter" data-level="2.2.10" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#model-comparison-summary"><i class="fa fa-check"></i><b>2.2.10</b> Model Comparison Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#models-with-interaction"><i class="fa fa-check"></i><b>2.3</b> Models with Interaction</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#definition-of-interaction"><i class="fa fa-check"></i><b>2.3.1</b> Definition of Interaction</a></li>
<li class="chapter" data-level="2.3.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#interaction-term"><i class="fa fa-check"></i><b>2.3.2</b> Interaction Term</a></li>
<li class="chapter" data-level="2.3.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#interaction-models-in-r"><i class="fa fa-check"></i><b>2.3.3</b> Interaction Models in R</a></li>
<li class="chapter" data-level="2.3.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#r2-for-interaction-model"><i class="fa fa-check"></i><b>2.3.4</b> <span class="math inline">\(R^2\)</span> for Interaction Model</a></li>
<li class="chapter" data-level="2.3.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#considerations-for-using-interactions"><i class="fa fa-check"></i><b>2.3.5</b> Considerations for Using Interactions</a></li>
<li class="chapter" data-level="2.3.6" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#interaction-vs-correlation"><i class="fa fa-check"></i><b>2.3.6</b> Interaction vs Correlation</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#least-squares-estimation-lse"><i class="fa fa-check"></i><b>2.4</b> Least Squares Estimation (LSE)</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#estimating-regression-coefficients"><i class="fa fa-check"></i><b>2.4.1</b> Estimating Regression Coefficients</a></li>
<li class="chapter" data-level="2.4.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#mathematics-of-lse-for-slr"><i class="fa fa-check"></i><b>2.4.2</b> Mathematics of LSE for SLR</a></li>
<li class="chapter" data-level="2.4.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#lse-for-categorical-variable"><i class="fa fa-check"></i><b>2.4.3</b> LSE for Categorical Variable</a></li>
<li class="chapter" data-level="2.4.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#lse-more-generally"><i class="fa fa-check"></i><b>2.4.4</b> LSE More Generally</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#analysis-of-variance"><i class="fa fa-check"></i><b>2.5</b> ANalysis Of VAriance</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#submodels"><i class="fa fa-check"></i><b>2.5.1</b> Submodels</a></li>
<li class="chapter" data-level="2.5.2" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#f-statistics"><i class="fa fa-check"></i><b>2.5.2</b> F-Statistics</a></li>
<li class="chapter" data-level="2.5.3" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#comparing-3-or-more-categories"><i class="fa fa-check"></i><b>2.5.3</b> Comparing 3 or More Categories</a></li>
<li class="chapter" data-level="2.5.4" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#f-statistic-illustration"><i class="fa fa-check"></i><b>2.5.4</b> F-Statistic Illustration</a></li>
<li class="chapter" data-level="2.5.5" data-path="introduction-to-statistical-models.html"><a href="introduction-to-statistical-models.html#alternative-f-statistic-formula"><i class="fa fa-check"></i><b>2.5.5</b> Alternative F-Statistic Formula</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html"><i class="fa fa-check"></i><b>3</b> Hypothesis Testing via Permutation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#test-for-difference-in-means"><i class="fa fa-check"></i><b>3.1</b> Test for Difference in Means</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#mercury-levels-in-florida-lakes"><i class="fa fa-check"></i><b>3.1.1</b> Mercury Levels in Florida Lakes</a></li>
<li class="chapter" data-level="3.1.2" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#model-for-mercury-level"><i class="fa fa-check"></i><b>3.1.2</b> Model for Mercury Level</a></li>
<li class="chapter" data-level="3.1.3" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#hypotheses-and-key-question"><i class="fa fa-check"></i><b>3.1.3</b> Hypotheses and Key Question</a></li>
<li class="chapter" data-level="3.1.4" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#permutation-test-for-difference-in-means"><i class="fa fa-check"></i><b>3.1.4</b> Permutation Test for Difference in Means</a></li>
<li class="chapter" data-level="3.1.5" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#five-permutations-in-r"><i class="fa fa-check"></i><b>3.1.5</b> Five Permutations in R</a></li>
<li class="chapter" data-level="3.1.6" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#r-code-for-permutation-test"><i class="fa fa-check"></i><b>3.1.6</b> R Code for Permutation Test</a></li>
<li class="chapter" data-level="3.1.7" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#p-values"><i class="fa fa-check"></i><b>3.1.7</b> p-values</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#general-permutation-tests"><i class="fa fa-check"></i><b>3.2</b> General Permutation Tests</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#other-test-statistics"><i class="fa fa-check"></i><b>3.2.1</b> Other Test Statistics</a></li>
<li class="chapter" data-level="3.2.2" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#general-permutation-test-procedure"><i class="fa fa-check"></i><b>3.2.2</b> General Permutation Test Procedure</a></li>
<li class="chapter" data-level="3.2.3" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#difference-in-standard-deviation"><i class="fa fa-check"></i><b>3.2.3</b> Difference in Standard Deviation</a></li>
<li class="chapter" data-level="3.2.4" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#permutation-test-for-slope"><i class="fa fa-check"></i><b>3.2.4</b> Permutation Test for Slope</a></li>
<li class="chapter" data-level="3.2.5" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#f-statistic"><i class="fa fa-check"></i><b>3.2.5</b> F-Statistic</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="hypothesis-testing-via-permutation.html"><a href="hypothesis-testing-via-permutation.html#responsible-hypothesis-testing"><i class="fa fa-check"></i><b>3.3</b> Responsible Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html"><i class="fa fa-check"></i><b>4</b> Bootstrap Interval Estimation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#sampling-distributions"><i class="fa fa-check"></i><b>4.1</b> Sampling Distributions</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#sampling-from-a-population"><i class="fa fa-check"></i><b>4.1.1</b> Sampling From a Population</a></li>
<li class="chapter" data-level="4.1.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#confidence-intervals"><i class="fa fa-check"></i><b>4.1.2</b> Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrapping"><i class="fa fa-check"></i><b>4.2</b> Bootstrapping</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#mercury-levels-in-florida-lakes-1"><i class="fa fa-check"></i><b>4.2.1</b> Mercury Levels in Florida Lakes</a></li>
<li class="chapter" data-level="4.2.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-sampling"><i class="fa fa-check"></i><b>4.2.2</b> Bootstrap Sampling</a></li>
<li class="chapter" data-level="4.2.3" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-samples-of-lakes"><i class="fa fa-check"></i><b>4.2.3</b> Bootstrap Samples of Lakes</a></li>
<li class="chapter" data-level="4.2.4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-distribution"><i class="fa fa-check"></i><b>4.2.4</b> Bootstrap Distribution</a></li>
<li class="chapter" data-level="4.2.5" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-se-confidence-interval"><i class="fa fa-check"></i><b>4.2.5</b> Bootstrap SE Confidence Interval</a></li>
<li class="chapter" data-level="4.2.6" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-distribution-vs-sampling-distribution"><i class="fa fa-check"></i><b>4.2.6</b> Bootstrap Distribution vs Sampling Distribution</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrap-confidence-interval-example"><i class="fa fa-check"></i><b>4.3</b> Bootstrap Confidence Interval Example</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrapping-other-statistics"><i class="fa fa-check"></i><b>4.3.1</b> Bootstrapping Other Statistics</a></li>
<li class="chapter" data-level="4.3.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-mean"><i class="fa fa-check"></i><b>4.3.2</b> CI for Mean</a></li>
<li class="chapter" data-level="4.3.3" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-standard-deviation"><i class="fa fa-check"></i><b>4.3.3</b> CI for Standard Deviation</a></li>
<li class="chapter" data-level="4.3.4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-median"><i class="fa fa-check"></i><b>4.3.4</b> CI for Median</a></li>
<li class="chapter" data-level="4.3.5" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-difference-in-means"><i class="fa fa-check"></i><b>4.3.5</b> CI for Difference in Means</a></li>
<li class="chapter" data-level="4.3.6" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-regression-slope"><i class="fa fa-check"></i><b>4.3.6</b> CI for Regression Slope</a></li>
<li class="chapter" data-level="4.3.7" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-for-regression-response"><i class="fa fa-check"></i><b>4.3.7</b> CI for Regression Response</a></li>
<li class="chapter" data-level="4.3.8" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#more-cis-in-regression"><i class="fa fa-check"></i><b>4.3.8</b> More CI’s in Regression</a></li>
<li class="chapter" data-level="4.3.9" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#bootstrapping-cautions"><i class="fa fa-check"></i><b>4.3.9</b> Bootstrapping Cautions</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#estimating-standard-error"><i class="fa fa-check"></i><b>4.4</b> Estimating Standard Error</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#standard-error-vs-standard-deviation"><i class="fa fa-check"></i><b>4.4.1</b> Standard Error vs Standard Deviation</a></li>
<li class="chapter" data-level="4.4.2" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#sample-size-and-standard-error"><i class="fa fa-check"></i><b>4.4.2</b> Sample Size and Standard Error</a></li>
<li class="chapter" data-level="4.4.3" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#standard-error-formulas"><i class="fa fa-check"></i><b>4.4.3</b> Standard Error Formulas</a></li>
<li class="chapter" data-level="4.4.4" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#one-sample-mean-example"><i class="fa fa-check"></i><b>4.4.4</b> One-Sample Mean Example</a></li>
<li class="chapter" data-level="4.4.5" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#difference-in-means-example"><i class="fa fa-check"></i><b>4.4.5</b> Difference in Means Example</a></li>
<li class="chapter" data-level="4.4.6" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#regression-example"><i class="fa fa-check"></i><b>4.4.6</b> Regression Example</a></li>
<li class="chapter" data-level="4.4.7" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#theory-based-confidence-intervals"><i class="fa fa-check"></i><b>4.4.7</b> Theory-Based Confidence Intervals</a></li>
<li class="chapter" data-level="4.4.8" data-path="bootstrap-interval-estimation.html"><a href="bootstrap-interval-estimation.html#ci-method-comparison"><i class="fa fa-check"></i><b>4.4.8</b> CI Method Comparison</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html"><i class="fa fa-check"></i><b>5</b> Normal Error Regression Model</a>
<ul>
<li class="chapter" data-level="5.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#the-normal-error-regression-model"><i class="fa fa-check"></i><b>5.1</b> The Normal Error Regression Model</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#example-ice-cream-dispensor"><i class="fa fa-check"></i><b>5.1.1</b> Example: Ice Cream Dispensor</a></li>
<li class="chapter" data-level="5.1.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#signal-and-noise"><i class="fa fa-check"></i><b>5.1.2</b> Signal and Noise</a></li>
<li class="chapter" data-level="5.1.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#normal-distribution"><i class="fa fa-check"></i><b>5.1.3</b> Normal Distribution</a></li>
<li class="chapter" data-level="5.1.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#signal-and-noise-in-icecream-example"><i class="fa fa-check"></i><b>5.1.4</b> Signal and Noise in Icecream Example</a></li>
<li class="chapter" data-level="5.1.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#normal-error-regression-model-1"><i class="fa fa-check"></i><b>5.1.5</b> Normal Error Regression Model</a></li>
<li class="chapter" data-level="5.1.6" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#examples-of-normal-error-regression-model"><i class="fa fa-check"></i><b>5.1.6</b> Examples of Normal Error Regression Model</a></li>
<li class="chapter" data-level="5.1.7" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#implications-of-normal-error-regression-model"><i class="fa fa-check"></i><b>5.1.7</b> Implications of Normal Error Regression Model</a></li>
<li class="chapter" data-level="5.1.8" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#philosophical-question"><i class="fa fa-check"></i><b>5.1.8</b> Philosophical Question</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#inference-in-normal-error-regression-model"><i class="fa fa-check"></i><b>5.2</b> Inference in Normal Error Regression Model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#lm-summary-output"><i class="fa fa-check"></i><b>5.2.1</b> <code>lm</code> <code>summary</code> Output</a></li>
<li class="chapter" data-level="5.2.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#t-distribution"><i class="fa fa-check"></i><b>5.2.2</b> t-distribution</a></li>
<li class="chapter" data-level="5.2.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#difference-in-means-example-1"><i class="fa fa-check"></i><b>5.2.3</b> Difference in Means Example</a></li>
<li class="chapter" data-level="5.2.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#simple-linear-regression-example"><i class="fa fa-check"></i><b>5.2.4</b> Simple Linear Regression Example</a></li>
<li class="chapter" data-level="5.2.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#multiple-regression-example"><i class="fa fa-check"></i><b>5.2.5</b> Multiple Regression Example</a></li>
<li class="chapter" data-level="5.2.6" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#mr-with-interaction-example"><i class="fa fa-check"></i><b>5.2.6</b> MR with Interaction Example</a></li>
<li class="chapter" data-level="5.2.7" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#limitations"><i class="fa fa-check"></i><b>5.2.7</b> Limitations</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#f-distributions"><i class="fa fa-check"></i><b>5.3</b> F-Distributions</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#f-distribution"><i class="fa fa-check"></i><b>5.3.1</b> F-Distribution</a></li>
<li class="chapter" data-level="5.3.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#house-condition-example"><i class="fa fa-check"></i><b>5.3.2</b> House Condition Example</a></li>
<li class="chapter" data-level="5.3.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#interaction-example"><i class="fa fa-check"></i><b>5.3.3</b> Interaction Example</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#regression-model-assumptions"><i class="fa fa-check"></i><b>5.4</b> Regression Model Assumptions</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#regression-assumptions"><i class="fa fa-check"></i><b>5.4.1</b> Regression Assumptions</a></li>
<li class="chapter" data-level="5.4.2" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#checking-model-assumptions"><i class="fa fa-check"></i><b>5.4.2</b> Checking Model Assumptions</a></li>
<li class="chapter" data-level="5.4.3" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#summary-of-checks-for-model-assumptions"><i class="fa fa-check"></i><b>5.4.3</b> Summary of Checks for Model Assumptions</a></li>
<li class="chapter" data-level="5.4.4" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#example-n-v-s-lakes"><i class="fa fa-check"></i><b>5.4.4</b> Example: N v S Lakes</a></li>
<li class="chapter" data-level="5.4.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#example-ph-model"><i class="fa fa-check"></i><b>5.4.5</b> Example: pH Model</a></li>
<li class="chapter" data-level="5.4.6" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#example-house-prices"><i class="fa fa-check"></i><b>5.4.6</b> Example: House Prices</a></li>
<li class="chapter" data-level="5.4.7" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#general-comments-on-model-assumptions"><i class="fa fa-check"></i><b>5.4.7</b> General Comments on Model Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#confidence-and-prediction-intervals"><i class="fa fa-check"></i><b>5.5</b> Confidence and Prediction Intervals</a></li>
<li class="chapter" data-level="5.6" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#transformations"><i class="fa fa-check"></i><b>5.6</b> Transformations</a></li>
<li class="chapter" data-level="5.7" data-path="normal-error-regression-model.html"><a href="normal-error-regression-model.html#responsible-statistical-inference"><i class="fa fa-check"></i><b>5.7</b> Responsible Statistical Inference</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="model-building.html"><a href="model-building.html"><i class="fa fa-check"></i><b>6</b> Model Building</a></li>
<li class="chapter" data-level="7" data-path="classification-and-logistic-regression.html"><a href="classification-and-logistic-regression.html"><i class="fa fa-check"></i><b>7</b> Classification and Logistic Regression</a></li>
<li class="chapter" data-level="8" data-path="predictive-modeling.html"><a href="predictive-modeling.html"><i class="fa fa-check"></i><b>8</b> Predictive Modeling</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Stat 255: Statistics for Data Science Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="normal-error-regression-model" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Normal Error Regression Model<a href="normal-error-regression-model.html#normal-error-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>Learning Outcomes:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Explain when it is appropriate to use “theory-based” standard error formulas.<br />
</p></li>
<li><p>Interpret estimates, standard errors, test statistics, and p-values resulting from linear model output in R.<br />
</p></li>
<li><p>List the assumptions made in the normal error regression model.<br />
</p></li>
<li><p>Calculate p-values corresponding to t-statistics and F-statistics in R.<br />
</p></li>
<li><p>Interpret confidence intervals for an expected response, and prediction intervals, and distinguish between these two types of intervals.<br />
</p></li>
<li><p>Assess the whether linear model assumptions are reasonably satisfied, using residual plots, histograms, and normal QQ plots.<br />
</p></li>
<li><p>Explain when we should or should not expect p-values and confidence intervals obtained via “theory-based” approaches to agree with those obtained via simulation.</p></li>
<li><p>Identify situations where a log transformation of the response variable is appropriate.<br />
</p></li>
<li><p>Calculate predicted values for models involving a log transformation of the response variable.<br />
</p></li>
<li><p>Interpret regression coefficients in models involving a log transformation of the response variable.<br />
</p></li>
<li><p>Explain the regression effect.</p></li>
</ol>
<div id="the-normal-error-regression-model" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> The Normal Error Regression Model<a href="normal-error-regression-model.html#the-normal-error-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You’ve probably noticed that many (though not all) of the distributions of statistics associated with permutation-based hypothesis tests in Chapter 3 and bootstrap confidence intervals in Chapter 4 were symmetric and bell-shaped in nature. We also saw in Section 4.4 that certain statistics, such as differences in means, and regression coefficients have known standard error formulas, allowing us to approximate their standard errors without performing simulation.</p>
<p>When working with statistics that have symmetric and bell-shaped distributions and know standard error formulas, it is possible to use well-known probability facts to obtain confidence intervals and perform hypothesis tests without actually performing the simulation seen in Chapters 3 and 4. In order to be able to use these facts, however, we must know that the sampling distribution of our statistic is in fact symmetric and bell-shaped. One way to know that would be to actually perform the simulations and check the shape of the distribution. This, of course, would defeat the purpose of bypassing the simulations, however.</p>
<p>In this chapter, we’ll examine ways to check whether a statistic such as a mean, regression slope, or expected response will follow a symmetric and bell-shaped sampling distribution, without actually having to perform a simulation. For situations where the statistic does follow such a distribution, we’ll examine methods for obtaining confidence intervals and p-values, based on probability theory, rather than simulation.</p>
<div id="example-ice-cream-dispensor" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Example: Ice Cream Dispensor<a href="normal-error-regression-model.html#example-ice-cream-dispensor" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="Ice_Cream.png" width="50%" /></p>
<p>Suppose an ice cream machine is manufactured to dispense 2 oz. of ice cream per second, on average. If 15 people used the ice cream machine, holding the dispensor for different amounts of time, and each person got exactly 2 oz. per second, the relationship between time holding the dispensor and amount dispensed would look like this:</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-354-1.png" width="672" /></p>
<p>In reality, however, the actual amount dispensed each time it is used will vary due to unknown factors like:</p>
<ul>
<li>force applied to dispensor<br />
</li>
<li>temperature<br />
</li>
<li>build-up of ice cream<br />
</li>
<li>other unknown factors</li>
</ul>
<p>Thus, if 15 real people held the dispenser and recorded the amount of ice cream they got, the scatter plot we would see would look something like this:</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-355-1.png" width="672" /></p>
</div>
<div id="signal-and-noise" class="section level3 hasAnchor" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Signal and Noise<a href="normal-error-regression-model.html#signal-and-noise" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can think of the amount of ice cream a person receives as being a result of two separate components, often referred to as <strong>signal</strong> and <strong>noise</strong>.</p>
<p>Signal represents the average amount of ice cream a person is expected to receive based on the amount of time holding the dispenser. In this case, signal is given by the function <span class="math inline">\(\text{Expected Amount} = 2\times\text{Time}\)</span>. Everyone who holds the dispenser for <span class="math inline">\(t\)</span> seconds is expected to receive <span class="math inline">\(2t\)</span> ounces of ice cream.</p>
<p>Noise represents how much each person’s actual amount of ice cream deviates from their expected amount. For example, a person who holds the dispenser for 1.5 seconds and receives 3.58 oz. of ice cream will have received 0.58 ounces more than expected due to noise (i.e. factors beyond time holding the dispenser).</p>
<p>In a statistical model, we assume that the response value of a response variable we observe is the sum of the signal, or expected response, which is a function of the explanatory variables in the model, and noise, which results from deviations due to factos beyond those accounted for in the model.</p>
</div>
<div id="normal-distribution" class="section level3 hasAnchor" number="5.1.3">
<h3><span class="header-section-number">5.1.3</span> Normal Distribution<a href="normal-error-regression-model.html#normal-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It is common to model noise using a symmetric, bell-shaped distribution, known as a <strong>normal distribution</strong>.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-356-1.png" width="576" /></p>
<p>We can think of the error term as a random draw from somewhere in the area below the bell-curve. For example, in the above illustration, most of the area under the curve lies between <span class="math inline">\(-1\leq x\leq 1\)</span>. If this curve represented the noise term in the ice cream example, it would mean that most people’s actual amount of ice cream dispensed would be within <span class="math inline">\(\pm 1\)</span> ounce of their expected amount (or signal). Notice that the normal distribution is centered at 0, indicating that on average, a person would be expected to get an amount exactly equal to their signal, but that they might deviate above or below this amount by unexplained factors, which can be modeled by random chance.</p>
<p>A normal distribution is defined by two parameters:<br />
- <span class="math inline">\(\mu\)</span> representing the center of the distribution<br />
- <span class="math inline">\(\sigma\)</span> representing the standard deviation</p>
<p>This distribution is denoted <span class="math inline">\(\mathcal{N}(\mu, \sigma)\)</span>.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-358-1.png" width="576" /></p>
<p>When the standard deviation is small, such as for the blue curve, noise tends to be close to 0, meaning the observed values will be close to their expectation. On the other hand, the green curve, which has higher standard deviation, would often produce noise values as extreme as <span class="math inline">\(\pm 2\)</span> or more.</p>
<p>Note that the square of the standard deviation <span class="math inline">\(\sigma^2\)</span> is called the variance. Some books denote the normal distribution as <span class="math inline">\(\mathcal{N}(\mu, \sigma^2)\)</span>, instead of <span class="math inline">\(\mathcal{N}(\mu,\sigma)\)</span>. We will use the <span class="math inline">\(\mathcal{N}(\mu,\sigma)\)</span> here, which is consistent with R.</p>
</div>
<div id="signal-and-noise-in-icecream-example" class="section level3 hasAnchor" number="5.1.4">
<h3><span class="header-section-number">5.1.4</span> Signal and Noise in Icecream Example<a href="normal-error-regression-model.html#signal-and-noise-in-icecream-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this example, we’ll simulate the amount of ice cream dispensed for each person by adding a random number from a normal distribution with mean 0 and standard deviation 0.5 to the expected amount dispensed, which is given by <span class="math inline">\(2x\)</span>, where <span class="math inline">\(x\)</span> represents time pressing the dispenser. We’ll let <span class="math inline">\(\epsilon_i\)</span> represent the random noise term for the <span class="math inline">\(i\)</span> person.</p>
<p>Thus, amount dispensed (<span class="math inline">\(Y_i\)</span>) for person <span class="math inline">\(i\)</span> is given by</p>
<p><span class="math display">\[Y_i = 2x_i+\epsilon_i, \text{ where } \epsilon_i\sim\mathcal{N}(0, 0.5)
\]</span></p>
<p>We simulate the amount dispensed for a sample of 15 people below.</p>
<div class="sourceCode" id="cb493"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb493-1"><a href="normal-error-regression-model.html#cb493-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">10082020</span>)</span>
<span id="cb493-2"><a href="normal-error-regression-model.html#cb493-2" aria-hidden="true" tabindex="-1"></a><span class="co"># set times </span></span>
<span id="cb493-3"><a href="normal-error-regression-model.html#cb493-3" aria-hidden="true" tabindex="-1"></a>time <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">1.2</span>, <span class="fl">1.5</span>, <span class="fl">1.8</span>, <span class="fl">2.1</span>, <span class="fl">2.1</span>, <span class="fl">2.3</span>, <span class="fl">2.5</span>, <span class="fl">2.6</span>, <span class="fl">2.8</span>, <span class="fl">2.9</span>, <span class="fl">2.9</span>, <span class="fl">3.1</span>, <span class="fl">3.2</span>, <span class="fl">3.6</span>)</span>
<span id="cb493-4"><a href="normal-error-regression-model.html#cb493-4" aria-hidden="true" tabindex="-1"></a>expected <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span>time  <span class="co"># expected amount</span></span>
<span id="cb493-5"><a href="normal-error-regression-model.html#cb493-5" aria-hidden="true" tabindex="-1"></a>noise <span class="ot">&lt;-</span><span class="fu">rnorm</span>(<span class="dv">15</span>, <span class="dv">0</span>, <span class="fl">0.5</span>) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">2</span>)  <span class="co">#generate noise from normal distribution</span></span>
<span id="cb493-6"><a href="normal-error-regression-model.html#cb493-6" aria-hidden="true" tabindex="-1"></a>amount <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span>time <span class="sc">+</span> noise  <span class="co"># calculate observed amounts</span></span>
<span id="cb493-7"><a href="normal-error-regression-model.html#cb493-7" aria-hidden="true" tabindex="-1"></a>Icecream <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(time, signal, noise, amount) <span class="co"># set up data table</span></span>
<span id="cb493-8"><a href="normal-error-regression-model.html#cb493-8" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>((Icecream)) <span class="co">#display table</span></span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">time</th>
<th align="right">signal</th>
<th align="right">noise</th>
<th align="right">amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1.0</td>
<td align="right">2.0</td>
<td align="right">0.23</td>
<td align="right">2.23</td>
</tr>
<tr class="even">
<td align="right">1.2</td>
<td align="right">2.4</td>
<td align="right">-0.49</td>
<td align="right">1.91</td>
</tr>
<tr class="odd">
<td align="right">1.5</td>
<td align="right">3.0</td>
<td align="right">0.58</td>
<td align="right">3.58</td>
</tr>
<tr class="even">
<td align="right">1.8</td>
<td align="right">3.6</td>
<td align="right">-0.03</td>
<td align="right">3.57</td>
</tr>
<tr class="odd">
<td align="right">2.1</td>
<td align="right">4.2</td>
<td align="right">0.17</td>
<td align="right">4.37</td>
</tr>
<tr class="even">
<td align="right">2.1</td>
<td align="right">4.2</td>
<td align="right">-0.93</td>
<td align="right">3.27</td>
</tr>
<tr class="odd">
<td align="right">2.3</td>
<td align="right">4.6</td>
<td align="right">0.05</td>
<td align="right">4.65</td>
</tr>
<tr class="even">
<td align="right">2.5</td>
<td align="right">5.0</td>
<td align="right">-0.37</td>
<td align="right">4.63</td>
</tr>
<tr class="odd">
<td align="right">2.6</td>
<td align="right">5.2</td>
<td align="right">-0.46</td>
<td align="right">4.74</td>
</tr>
<tr class="even">
<td align="right">2.8</td>
<td align="right">5.6</td>
<td align="right">0.17</td>
<td align="right">5.77</td>
</tr>
<tr class="odd">
<td align="right">2.9</td>
<td align="right">5.8</td>
<td align="right">-0.59</td>
<td align="right">5.21</td>
</tr>
<tr class="even">
<td align="right">2.9</td>
<td align="right">5.8</td>
<td align="right">0.12</td>
<td align="right">5.92</td>
</tr>
<tr class="odd">
<td align="right">3.1</td>
<td align="right">6.2</td>
<td align="right">0.00</td>
<td align="right">6.20</td>
</tr>
<tr class="even">
<td align="right">3.2</td>
<td align="right">6.4</td>
<td align="right">0.67</td>
<td align="right">7.07</td>
</tr>
<tr class="odd">
<td align="right">3.6</td>
<td align="right">7.2</td>
<td align="right">0.05</td>
<td align="right">7.25</td>
</tr>
</tbody>
</table>
<p>The scatterplot displays the amount dispensed, compared to the time pressing the dispenser. The red line indicates the line <span class="math inline">\(y=2x\)</span>. If there was no random noise, then each person’s amount dispensed would lie exactly on this line.</p>
<div class="sourceCode" id="cb494"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb494-1"><a href="normal-error-regression-model.html#cb494-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Icecream1, <span class="fu">aes</span>(<span class="at">x=</span>time, <span class="at">y=</span>amount)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Icecream Dispensed&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Time Pressing Dispensor&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Amount Dispensed&quot;</span>) <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="dv">2</span>, <span class="at">intercept=</span><span class="dv">0</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb494-2"><a href="normal-error-regression-model.html#cb494-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">label=</span><span class="st">&quot;y=2x&quot;</span>, <span class="at">x=</span> <span class="fl">3.5</span>, <span class="at">y=</span><span class="fl">6.5</span>, <span class="at">size=</span><span class="dv">10</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-360-1.png" width="672" /></p>
<p>In a real situation, we would not see the signal and noise columns in the table or the red line on the graph. We would only see the time and amount, and points on the scatter plot. From these, we would need to estimate the location of the red line by fitting a least squares regression line to the data, as we’ve done before.</p>
<p>The blue line represents the location of the least squares regression line fit to the time and amounts observed.</p>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb495-1"><a href="normal-error-regression-model.html#cb495-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Icecream1, <span class="fu">aes</span>(<span class="at">x=</span>time, <span class="at">y=</span>amount)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Icecream Dispensed&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Time Pressing Dispensor&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Amount Dispensed&quot;</span>) <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="dv">2</span>, <span class="at">intercept=</span><span class="dv">0</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb495-2"><a href="normal-error-regression-model.html#cb495-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">label=</span><span class="st">&quot;y=2x&quot;</span>, <span class="at">x=</span> <span class="fl">3.5</span>, <span class="at">y=</span><span class="fl">6.5</span>, <span class="at">size=</span><span class="dv">10</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-361-1.png" width="672" />
The blue line is close, but not identical to the red line, representing the true (usually unknown) signal.</p>
<p>The slope and intercept of the blue line are given by:</p>
<div class="sourceCode" id="cb496"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb496-1"><a href="normal-error-regression-model.html#cb496-1" aria-hidden="true" tabindex="-1"></a>IC_Model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Icecream1, <span class="fu">lm</span>(amount<span class="sc">~</span>time))</span>
<span id="cb496-2"><a href="normal-error-regression-model.html#cb496-2" aria-hidden="true" tabindex="-1"></a>IC_Model</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = lm(amount ~ time), data = Icecream1)
## 
## Coefficients:
## (Intercept)         time  
##     -0.1299       2.0312</code></pre>
<p>Notice that these estimates are close, but not identical to the intercept and slope of the red line, which are 0 and 2, respectively.</p>
<p>The equation of the red line is given by:</p>
<p><span class="math inline">\(Y_i = \beta_0 + \beta_1X_{i} + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span>,</p>
<p>where <span class="math inline">\(Y_i\)</span> represents amount dispensed, and <span class="math inline">\(X_i\)</span> represents time. <span class="math inline">\(\beta_0, \beta_1,\)</span>, and <span class="math inline">\(\sigma\)</span> are the unknown model parameters associated with the ice cream machine’s process.</p>
<p>Using the values of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> obtained by fitting a model to our observed data as estimates of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, our estimated regression equation is</p>
<p><span class="math display">\[Y_i = b_0 + b_1X_i + \epsilon_i = -0.1299087 + 2.0312489X_i + \epsilon_i
\]</span></p>
<p>where <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span>.</p>
<p>An estimate for <span class="math inline">\(\sigma\)</span> is given by</p>
<p><span class="math inline">\(s =\sqrt{\frac{\text{SSR}}{n-(p+1)}} = \sqrt{\frac{\displaystyle\sum_{i=1}^n(y_i-\hat{y}_i)^2}{(n-(p+1))}}\)</span>.</p>
<p>We calculate this estimate of <span class="math inline">\(\hat{\sigma}\)</span>, using R.</p>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb498-1"><a href="normal-error-regression-model.html#cb498-1" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(IC_Model<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(<span class="dv">15-2</span>))</span>
<span id="cb498-2"><a href="normal-error-regression-model.html#cb498-2" aria-hidden="true" tabindex="-1"></a>s</span></code></pre></div>
<pre><code>## [1] 0.4527185</code></pre>
<p>The estimates of <span class="math inline">\(b_0 = -0.1299087\)</span>, <span class="math inline">\(b_1=2.0312489\)</span>, and <span class="math inline">\(s = 0.4527185\)</span> are resonably close estimates to the values <span class="math inline">\(\beta_0=0, \beta_1=2\)</span>, and <span class="math inline">\(\sigma = 0.5\)</span>, that we used to generate the data.</p>
<p>In a real situation, we’ll have only statistics <span class="math inline">\(b_0\)</span>, <span class="math inline">\(b_1\)</span>, and <span class="math inline">\(s\)</span>, and we’ll need to use them to draw conclusions about parameters <span class="math inline">\(\beta_0=0, \beta_1=2\)</span>, and <span class="math inline">\(\sigma = 0.5\)</span>.</p>
</div>
<div id="normal-error-regression-model-1" class="section level3 hasAnchor" number="5.1.5">
<h3><span class="header-section-number">5.1.5</span> Normal Error Regression Model<a href="normal-error-regression-model.html#normal-error-regression-model-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the ice cream example, the relationship between expected amount and time holding the dispenser was given by a linear equation involving a single numeric explanatory variable. We can generalize this to situations with multiple explanatory variables, which might be numeric or categorical.</p>
<p>Individual observations are then assumed to vary from their expectation in accordance with a normal distribution, representing random noise (or error).</p>
<p>The mathematical form of a normal error linear regression model is</p>
<p><span class="math inline">\(Y_i = \beta_0 + \beta_1X_{i1}+ \ldots + \beta_pX_{ip} + \epsilon_i\)</span>, with <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span>.</p>
<p>Note that in place of <span class="math inline">\(X_{ip}\)</span>, we could have indicators for categories, or functions of <span class="math inline">\(X_{ip}\)</span>, such as <span class="math inline">\(X_{ip}^2\)</span>, <span class="math inline">\(\text{log}(X_{ip})\)</span>, or <span class="math inline">\(\text{sin}(X_{ip})\)</span>.</p>
<ul>
<li><p>The quantities <span class="math inline">\(\beta_0, \beta_1, \ldots, \beta_p\)</span> are parameters, pertaining to the true but unknown data generating mechanism.</p></li>
<li><p>The estimates <span class="math inline">\(b_0, b_1, \ldots, b_p\)</span>, are statistics, calculated from our observed data.<br />
</p></li>
<li><p>We use confidence intervals and hypothesis tests to make statements about parameters, based on information provided by statistics.</p></li>
</ul>
</div>
<div id="examples-of-normal-error-regression-model" class="section level3 hasAnchor" number="5.1.6">
<h3><span class="header-section-number">5.1.6</span> Examples of Normal Error Regression Model<a href="normal-error-regression-model.html#examples-of-normal-error-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can formulate all of the examples we’ve worked with so far in terms of the normal error regression model.</p>
<p>In the house price example, consider the following models:</p>
<p><strong>Model 1:</strong>
<span class="math inline">\(\text{Price}_i = \beta_0 + \beta_1\text{Sq.Ft.}_{i} + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span>.
If we use this model, we’re saying that we believe the expected price of a house is a linear function of its size, and that for any given size, the distribution of actual prices are normally distributed around their expected value of <span class="math inline">\(\beta_0 + \beta_1\text{Sq.Ft.}_{i}\)</span>.</p>
<p><strong>Model 2:</strong></p>
<p><span class="math inline">\(\text{Price}_i = \beta_0 + \beta_2\text{Waterfront}_{i}+ \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span>.</p>
<p>If we use this model, we’re saying that we believe the expected price of a house depends only on whether or not it is on the waterfront, and that prices of both waterfront and non-waterfront houses follow normal distributions, though these distributions may have different means (<span class="math inline">\(\beta_0\)</span> for non-waterfront houses, and <span class="math inline">\(\beta_1\)</span> for waterfront houses).</p>
<p><strong>Model 3:</strong></p>
<p><span class="math inline">\(\text{Price}_i = \beta_0 + \beta_1\text{Sq.Ft.}_{i}+ \beta_2\text{Waterfront}_{i}+ \beta_3\times\text{Sq.Ft.}_i\times\text{Waterfront}_{i} + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span>.</p>
<p>and</p>
<p><strong>Model 4:</strong>
<span class="math inline">\(\text{Price}_i = \beta_0 + \beta_1\text{Sq.Ft.}_{i}+ \beta_2\text{Waterfront}_{i}+ \beta_3\times\text{Sq.Ft.}_i\times\text{Waterfront}_{i} + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span>.</p>
<p>Both models assume that actual prices of houses with the same size and waterfront status are normally distributed, and that the mean of the normal distribution is a linear function of its size. Model 3 allows for the intercept of the lines to differ between waterfront and non-waterfront houses, while Model 4 allows both the intercept and slope to differ.</p>
</div>
<div id="implications-of-normal-error-regression-model" class="section level3 hasAnchor" number="5.1.7">
<h3><span class="header-section-number">5.1.7</span> Implications of Normal Error Regression Model<a href="normal-error-regression-model.html#implications-of-normal-error-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If we really believe that data come about as the normal error regression model describes, then probability theory tells us that regression coefficients <span class="math inline">\(b_j\)</span>’s, representing differences between categories for categorical variables and rates of change for quantitative variables, follow symmetric and bell-shaped distributions. We can use this fact, along with the standard error formulas in Section 4.4 to create confidence intervals and perform hypothesis tests, without needing to perform simulation. This is, in fact what R does in it’s model summary output.</p>
<p>These methods are only valid, however, if data can reasonably be thought of as having come the normal error regression model process. Thus, if we don’t believe that our observed data can be reasonably thought of terms representing underlying signal as a linear function of explanatory variables, and a normally distributed random error (or noise) term, then the confidence intervals and p-values produced by R, and other places that rely on probability-based methods will not be reliable.</p>
</div>
<div id="philosophical-question" class="section level3 hasAnchor" number="5.1.8">
<h3><span class="header-section-number">5.1.8</span> Philosophical Question<a href="normal-error-regression-model.html#philosophical-question" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We close the section with a philosophical question:</p>
<p>Do data really come about from processes like the normal error regression model? That is, do you think it is reasonable to believe that data we see in the real world (perhaps the amount of ice cream dispensed by an ice cream machine) is a combination of some true, but unknown equation involving the explanatory and response variables, and some unexplained noise, coming from a normal distribution?</p>
<p>We won’t attempt to answer that question here, but it is worth thinking about. After all, it is an assumption on which many frequently employed methods of statistical inference depends.</p>
</div>
</div>
<div id="inference-in-normal-error-regression-model" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Inference in Normal Error Regression Model<a href="normal-error-regression-model.html#inference-in-normal-error-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When data can reasonably be assumed to have come from a process consistent with the normal error regression model, we can perform hypothesis tests and make confidence intervals for regression coefficients <span class="math inline">\(\beta_j\)</span>’s, (which represent slopes or differences in means), using probability-based methods rather than simulation. This is done in the R output for the <code>lm</code> <code>summary</code> command.</p>
<div id="lm-summary-output" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> <code>lm</code> <code>summary</code> Output<a href="normal-error-regression-model.html#lm-summary-output" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>summary</code> command for a linear model in R displays a table including 4 columns.</p>
<p><strong>Columns in Linear Model <code>summary()</code> Output</strong></p>
<ul>
<li><p><strong>Estimate</strong> gives the least-squares estimates <span class="math inline">\(b_0, b_1, \ldots, b_p\)</span></p></li>
<li><p><strong>Standard Error</strong> gives estimates of the standard deviation in the sampling distribution for estimate. (i.e. how much uncertainty is there about the estimate?) These are computed using the formulas in Section 4.4.</p></li>
<li><p><strong>t value</strong> is the estimate divided by its standard error.</p></li>
<li><p><strong>Pr(&gt;|t|)</strong> is a p-value for the hypothesis test associated with the null hypothesis <span class="math inline">\(\beta_j = 0\)</span>, where <span class="math inline">\(\beta_j\)</span> is the regression coefficient pertaining to the given line. Note that <span class="math inline">\(\beta_j\)</span> is the unknown population parameter estimated by <span class="math inline">\(b_j\)</span>.</p></li>
</ul>
<p>Recall our linear model for mercury levels of lakes in Northern Florida, compared to Southern Florida.</p>
<p>The equation of the model is:</p>
<p><span class="math display">\[
\widehat{\text{Mercury}} = \beta_0+\beta_1\times\text{South}
\]</span></p>
<p>We fit the model in R and display its summary output below.</p>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb500-1"><a href="normal-error-regression-model.html#cb500-1" aria-hidden="true" tabindex="-1"></a>Lakes_M <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>FloridaLakes, Mercury<span class="sc">~</span>Location)</span>
<span id="cb500-2"><a href="normal-error-regression-model.html#cb500-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Lakes_M)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Mercury ~ Location, data = FloridaLakes)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.65650 -0.23455 -0.08455  0.24350  0.67545 
## 
## Coefficients:
##             Estimate Std. Error t value       Pr(&gt;|t|)    
## (Intercept)  0.42455    0.05519   7.692 0.000000000441 ***
## LocationS    0.27195    0.08985   3.027        0.00387 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3171 on 51 degrees of freedom
## Multiple R-squared:  0.1523, Adjusted R-squared:  0.1357 
## F-statistic: 9.162 on 1 and 51 DF,  p-value: 0.003868</code></pre>
<p>The estimated regression equation is</p>
<p><span class="math display">\[
\widehat{\text{Mercury}} = 0.42455+0.27195\times\text{South}
\]</span></p>
<p>We’ve seen how to obtain the first two columns of the summary table, labeled “Estimate” and “Std. Error”.</p>
<p>The last column, labeled “Pr(&gt;|t|)” is, in fact a p-value associated with associated with the null hypothesis that the regression parameter on that line is zero. (i.e. <span class="math inline">\(\beta_j=0\)</span>).</p>
<p><strong>Example</strong> Florida Lakes</p>
<p><strong>Hypothesis Test for line (intercept)</strong></p>
<p><strong>Null Hypothesis:</strong> The average mercury level among all lakes in North Florida is 0 (<span class="math inline">\(\beta_0=0\)</span>).</p>
<p><strong>Alternative Hypothesis:</strong> The average mercury level among all lakes in Northern Florida is not 0 (<span class="math inline">\(\beta_0\neq 0\)</span>).</p>
<p>We already know the average mercury level among all lakes in North Florida is not 0, so this is a silly test.</p>
<p><strong>Hypothesis Test for line LocationS</strong></p>
<p><strong>Null Hypothesis:</strong> There is no difference in average mercury levels between Northern and Southern Florida (<span class="math inline">\(\beta_1=0\)</span>).</p>
<p><strong>Alternative Hypothesis:</strong> There is a difference in average mercury levels in Northern and Southern Florida (<span class="math inline">\(\beta_1\neq 0\)</span>).</p>
<p>This test is relevant to us.</p>
<p>R does not obtain these p-values through simulation, but rather by using the symmetric and bell-shaped t-distribution to approximate the distribution of these statistics. This is appropriate when the sampling distribution for our test statistic is reasonably symmetric and bell-shaped.</p>
<p>You’ve probably noticed that the sampling distributions in our permutation-based hypothesis tests, and our bootstrap distributions for regression coefficients have often been roughly symmetric and bell-shaped. When this happens, we can use a symmetric and bell-shaped distribution to model the distribution of a test statistic when the null hypothesis is true, bypassing the need to use simulation.</p>
<p>There is statistical theory which shows that if data really do come from the normal error regression model process, like the ice cream dispenser in the previous section, then the ratio of regression coefficients (means, differences in means, slopes) divided by their standard error, will follow a symmetric bell-shaped distribution called a t-distribution.</p>
</div>
<div id="t-distribution" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> t-distribution<a href="normal-error-regression-model.html#t-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A t-distribution is a symmetric, bell-shaped curve, with thicker tails (hence more variability), than a <span class="math inline">\(\mathcal{N}(0,1)\)</span> distribution. The t-distribution depends on a parameter called <strong>degrees of freedom</strong>, which determines the thickness of the distribution’s tails.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-367-1.png" width="768" /></p>
<p>For data that come from a normal error regression model, we can use a t-distribution to approximate the sampling distribution used in our hypothesis tests, when the null hypothesis is assumed to be true.</p>
<p><strong>Important Fact:</strong> If <span class="math inline">\(Y_i = \beta_0 + \beta_1X_{i1}+ \ldots + \beta_pX_{ip} + \epsilon_i\)</span>, with <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span>, then</p>
<p><span class="math display">\[
t= \frac{{b_j}}{\text{SE}(b_j)}  
\]</span></p>
<p>follows a t-distribution.</p>
<p>The <span class="math inline">\(t=\frac{{b_j}}{\text{SE}(b_j)}\)</span> is called a <strong>t-statistic</strong>.</p>
<p>We’ll use this t-statistic as the test statistic in our hypothesis test.</p>
<p>The degrees of freedom are given by <span class="math inline">\(n-(p+1)\)</span>, where <span class="math inline">\(p\)</span> represents the number of terms in the model, not including the intercept.</p>
</div>
<div id="difference-in-means-example-1" class="section level3 hasAnchor" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Difference in Means Example<a href="normal-error-regression-model.html#difference-in-means-example-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall the hypothesis test we performed to investigate whether there is a difference in average mercury level between lakes in Northern Florida and Southern Florida.</p>
<p><strong>Null Hypothesis:</strong> There is no difference in average mercury levels between Northern and Southern Florida (<span class="math inline">\(\beta_1=0\)</span>).</p>
<p><strong>Alternative Hypothesis:</strong> There is a difference in average mercury levels in Northern and Southern Florida (<span class="math inline">\(\beta_1\neq 0\)</span>).</p>
<p><strong>Test Statistic</strong>: <span class="math inline">\(t=\frac{{b_j}}{\text{SE}(b_j)} = \frac{0.27195}{0.08985} = 3.027\)</span></p>
<p><strong>Key Question:</strong> What is the probability of getting a t-statistic as extreme as 3.027 if <span class="math inline">\(\beta_1=0\)</span> (i.e. there is no difference in mercury levels between northern and southern lakes).</p>
<p>We plot the t-statistic of 3.027 that we observed in our data and observe where it lies on a t-distribution.</p>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb502-1"><a href="normal-error-regression-model.html#cb502-1" aria-hidden="true" tabindex="-1"></a>ts<span class="ot">=</span><span class="fl">3.027</span></span>
<span id="cb502-2"><a href="normal-error-regression-model.html#cb502-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_dist</span>(<span class="st">&quot;t&quot;</span>, <span class="at">df=</span><span class="dv">51</span>, <span class="at">geom =</span> <span class="st">&quot;area&quot;</span>, <span class="at">fill =</span> <span class="sc">~</span> (<span class="fu">abs</span>(x)<span class="sc">&lt;</span> <span class="fu">abs</span>(ts)), <span class="at">show.legend=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">c</span>(ts, <span class="sc">-</span>ts), <span class="at">color=</span><span class="st">&quot;red&quot;</span>)  <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;t&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-368-1.png" width="768" /></p>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb503-1"><a href="normal-error-regression-model.html#cb503-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(<span class="sc">-</span><span class="fu">abs</span>(ts), <span class="at">df=</span><span class="dv">51</span>)</span></code></pre></div>
<pre><code>## [1] 0.003866374</code></pre>
<p>The low p-value gives us strong evidence of a difference in average mercury levels between lakes in Northern and Southern Florida.</p>
<p>This is the p-value reported in R’s <code>lm</code> <code>summary()</code> output.</p>
<p>A t-statistic more extreme than <span class="math inline">\(\pm 2\)</span> will roughly correspond to a p-value less than 0.05.</p>
<p>*<strong>Comparison to Simulation</strong></p>
<p>Let’s compare these results to those given by the permutation test and bootstrap confidence interval.</p>
<p><strong>Permutation Test</strong></p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb505-1"><a href="normal-error-regression-model.html#cb505-1" aria-hidden="true" tabindex="-1"></a>NSLakes_SimulationResultsPlot</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-370-1.png" width="672" /></p>
<p>p-value:</p>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb506-1"><a href="normal-error-regression-model.html#cb506-1" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> Lakes_M<span class="sc">$</span>coef[<span class="dv">2</span>] <span class="do">## record value of b1 from actual data</span></span>
<span id="cb506-2"><a href="normal-error-regression-model.html#cb506-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb506-3"><a href="normal-error-regression-model.html#cb506-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(NSLakes_SimulationResults<span class="sc">$</span>b1Sim) <span class="sc">&gt;</span> <span class="fu">abs</span>(b1))</span></code></pre></div>
<pre><code>## [1] 0.0039</code></pre>
</div>
<div id="simple-linear-regression-example" class="section level3 hasAnchor" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> Simple Linear Regression Example<a href="normal-error-regression-model.html#simple-linear-regression-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We examine the model summary output for the model predicting a lake’s mercury level, using pH as the explanatory variable.</p>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb508-1"><a href="normal-error-regression-model.html#cb508-1" aria-hidden="true" tabindex="-1"></a>M_pH <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>FloridaLakes, Mercury<span class="sc">~</span>pH)</span>
<span id="cb508-2"><a href="normal-error-regression-model.html#cb508-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_pH)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Mercury ~ pH, data = FloridaLakes)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.48895 -0.19188 -0.05774  0.09456  0.71134 
## 
## Coefficients:
##             Estimate Std. Error t value       Pr(&gt;|t|)    
## (Intercept)  1.53092    0.20349   7.523 0.000000000814 ***
## pH          -0.15230    0.03031  -5.024 0.000006572811 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2816 on 51 degrees of freedom
## Multiple R-squared:  0.3311, Adjusted R-squared:  0.318 
## F-statistic: 25.24 on 1 and 51 DF,  p-value: 0.000006573</code></pre>
<p><strong>Hypothesis Test for Intercept Line</strong></p>
<p><strong>Null Hypothesis:</strong> The average mercury level among all Florida lakes with pH = 0 is 0. (<span class="math inline">\(\beta_0=0\)</span>).</p>
<p><strong>Alternative Hypothesis:</strong> The average mercury level among all Florida lakes with pH = 0 not 0. (<span class="math inline">\(\beta_0 \neq 0\)</span>).</p>
<p>Since there are no lakes with pH level 0, this is not a meaningful test.</p>
<p><strong>Hypothesis Test for pH Line</strong></p>
<p><strong>Null Hypothesis:</strong> There is no relationship between mercury and pH level among all Florida lakes. (<span class="math inline">\(\beta_1=0\)</span>).</p>
<p><strong>Alternative Hypothesis:</strong> There is a relationship between mercury and pH level among all Florida lakes. (<span class="math inline">\(\beta_1 \neq 0\)</span>).</p>
<p><strong>Test Statistic</strong>: <span class="math inline">\(t=\frac{{b_j}}{\text{SE}(b_j)} = \frac{-0.15230}{0.03031} = -5.024\)</span></p>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb510-1"><a href="normal-error-regression-model.html#cb510-1" aria-hidden="true" tabindex="-1"></a>ts<span class="ot">=</span><span class="fl">5.024</span></span>
<span id="cb510-2"><a href="normal-error-regression-model.html#cb510-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_dist</span>(<span class="st">&quot;t&quot;</span>, <span class="at">df=</span><span class="dv">51</span>, <span class="at">geom =</span> <span class="st">&quot;area&quot;</span>, <span class="at">fill =</span> <span class="sc">~</span> (<span class="fu">abs</span>(x)<span class="sc">&lt;</span> <span class="fu">abs</span>(ts)), <span class="at">show.legend=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">c</span>(ts, <span class="sc">-</span>ts), <span class="at">color=</span><span class="st">&quot;red&quot;</span>)  <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;t&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-373-1.png" width="768" /></p>
<div class="sourceCode" id="cb511"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb511-1"><a href="normal-error-regression-model.html#cb511-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(<span class="sc">-</span><span class="fu">abs</span>(ts), <span class="at">df=</span><span class="dv">51</span>)</span></code></pre></div>
<pre><code>## [1] 0.000006578117</code></pre>
<p>The p-value is extremely small, just as the simulation-based p-value we saw in Chapter 3.</p>
</div>
<div id="multiple-regression-example" class="section level3 hasAnchor" number="5.2.5">
<h3><span class="header-section-number">5.2.5</span> Multiple Regression Example<a href="normal-error-regression-model.html#multiple-regression-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We perform hypothesis tests on a model predicting house price using square feet and waterfront status as explanatory variables.</p>
<div class="sourceCode" id="cb513"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb513-1"><a href="normal-error-regression-model.html#cb513-1" aria-hidden="true" tabindex="-1"></a>M_wf_sqft <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Houses, price<span class="sc">~</span>sqft_living<span class="sc">+</span>waterfront)</span>
<span id="cb513-2"><a href="normal-error-regression-model.html#cb513-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_wf_sqft)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = price ~ sqft_living + waterfront, data = Houses)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1363.79  -251.55    59.28   177.58  1599.72 
## 
## Coefficients:
##                Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)   -407.6549    86.2868  -4.724        0.00000779668 ***
## sqft_living      0.4457     0.0353  12.626 &lt; 0.0000000000000002 ***
## waterfrontYes  814.3613   124.8546   6.522        0.00000000313 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 412.7 on 97 degrees of freedom
## Multiple R-squared:  0.7607, Adjusted R-squared:  0.7558 
## F-statistic: 154.2 on 2 and 97 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p><strong>Intercept Line:</strong></p>
<p><strong>Null Hypothesis</strong> The average price among all non-waterfront houses with 0 square feet is 0 dollars. (<span class="math inline">\(\beta_0=0\)</span>)</p>
<p>This is not a sensible hypothesis to test.</p>
<p><strong>sqft_living Line:</strong></p>
<p><strong>Null Hypothesis</strong> There is no relationship between price and square feet in a house, after accounting for waterfront status. (<span class="math inline">\(\beta_1=0\)</span>)</p>
<p>The large t-statistic (12.626) and small p-value provide strong evidence against this null hypothesis.</p>
<p>We know that a small p-value alone does not provide evidence of a relationship that is practically meaningful, but since our model estimates an expected 45 thousand dollar increase for each additional 100 square feet, this seems like a meaningful relationship.</p>
<p><strong>waterfrontYes Line:</strong></p>
<p><strong>Null Hypothesis</strong> On average, there is no difference between average price of waterfront and non-waterfront houses, assuming they are the same size. (<span class="math inline">\(\beta_2=0\)</span>)</p>
<p>The large t-statistic (6.522) and small p-value provide strong evidence against this null hypothesis. Waterfront houses are estimated to cost 814 thousand dollars more, on average, than non-waterfront houses of the same size.</p>
</div>
<div id="mr-with-interaction-example" class="section level3 hasAnchor" number="5.2.6">
<h3><span class="header-section-number">5.2.6</span> MR with Interaction Example<a href="normal-error-regression-model.html#mr-with-interaction-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb515"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb515-1"><a href="normal-error-regression-model.html#cb515-1" aria-hidden="true" tabindex="-1"></a>M_House_Int <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Houses, price <span class="sc">~</span> sqft_living <span class="sc">*</span> waterfront)</span>
<span id="cb515-2"><a href="normal-error-regression-model.html#cb515-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_House_Int)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = price ~ sqft_living * waterfront, data = Houses)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1559.34  -114.93   -30.24   131.09  1266.58 
## 
## Coefficients:
##                             Estimate Std. Error t value         Pr(&gt;|t|)    
## (Intercept)                 67.39594   91.39267   0.737           0.4627    
## sqft_living                  0.21837    0.04035   5.412 0.00000045752269 ***
## waterfrontYes             -364.59498  180.75875  -2.017           0.0465 *  
## sqft_living:waterfrontYes    0.43267    0.05566   7.773 0.00000000000857 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 325 on 96 degrees of freedom
## Multiple R-squared:  0.8531, Adjusted R-squared:  0.8486 
## F-statistic: 185.9 on 3 and 96 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p><strong>Intercept Line:</strong></p>
<p><strong>Null Hypothesis</strong> The average price among all non-waterfront houses with 0 square feet is 0 dollars. (<span class="math inline">\(\beta_0=0\)</span>)</p>
<p>This is not a sensible hypothesis to test.</p>
<p><strong>sqft_living Line:</strong></p>
<p><strong>Null Hypothesis</strong> There is no relationship between price and square feet among non-waterfront houses. (<span class="math inline">\(\beta_1=0\)</span>)</p>
<p>The large t-statistic (5.412) and small p-value provide strong evidence against this null hypothesis.</p>
<p><strong>waterfrontYes Line:</strong></p>
<p><strong>Null Hypothesis</strong> On average, there is no difference between average price of waterfront and non-waterfront houses with 0 square feet. (<span class="math inline">\(\beta_2=0\)</span>)</p>
<p>This is not a sensible hypothesis to test.</p>
<p><strong>sqft_living:waterfrontYes</strong></p>
<p><strong>Null Hypothesis</strong>: There is no interaction between square feet and waterfront. (<span class="math inline">\(\beta_3=0\)</span>) (That is, the effect of size on price is the same for waterfront and non-waterfront houses).</p>
<p>The large t-statistic (7.773) and small p-value provide strong evidence against this null hypothesis. It appears there really is evidence of an interaction between price and waterfront status, as we previously suspected, based on graphical representation and background knowledge.</p>
<p>Note that if the interaction term had yielded a large p-value, indicating a lack of evidence of an interaction, we might have wanted to drop the interaction term from the model, in order to make the interpretations of the other estimates and hypothesis tests simpler.</p>
</div>
<div id="limitations" class="section level3 hasAnchor" number="5.2.7">
<h3><span class="header-section-number">5.2.7</span> Limitations<a href="normal-error-regression-model.html#limitations" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ve seen that in situations where the sampling distribution for a regression coefficient <span class="math inline">\(b_j\)</span> is symmetric and bell-shaped, we can create confidence intervals and perform hypothesis tests using the t-distribution without performing permutation for hypothesis tests, or bootstrapping for confidence intervals.</p>
<p>There are, however, limitations to this approach, which underscore the importance of the simulation-based approaches seen in Chapters 3 and 4.</p>
<p>These include:</p>
<ol style="list-style-type: decimal">
<li><p>There are lots of statistics, like medians and standard deviations, that do not have known standard error formulas, and do not follow symmetric bell-shaped distributions. In more advanced and complicated models, it is common to encounter statistics of interest with unknown sampling distributions. In these cases, we can estimate p-values and build confidence intervals via simulation, even if we cannot identify the distribution by name.</p></li>
<li><p>Even for statistics with known standard error formulas, the t-test is only appropriate when the sampling distribution for <span class="math inline">\(b_j\)</span> is symmetric and bell-shaped. While there is probability theory that shows this will happen when the sample size is “large enough,” there is no set sample size that guarantees this. Datasets with heavier skewness in the response variable will require larger sample sizes than datasets with less skewness in the response.</p></li>
<li><p>The simulation-based approaches provide valuable insight to the logic behind hypothesis tests. When we permute values of an explanatory variable in a hypothesis test it is clear that we are simulating a situation where the null hypothesis is true. Likewise, when we simulate taking many samples in bootstrapping, it is clear that we are assessing the variability in a statistic across samples. Simply jumping to the t-based approximations of these distributions makes it easy to lose our sense of what they actually represent, and thus increases the likelihood of interpreting them incorrectly.</p></li>
</ol>
<p>In fact prominent statistician R.A. Fisher wrote of simulation-based methods in 1936:</p>
<p><em>``Actually, the statistician does not carry out this very simple and very tedious process, but his conclusions have no justification beyond the fact that they agree with those which could have been arrived at by this elementary method.”</em></p>
<p>Fisher’s comment emphasizes the fact that probability-based tests, like the t-test are simply approximations to what we would obtain via simulation-based approaches, which were not possible in his day, but are now.</p>
<p>Proponents of simulation-based inference include Tim Hesterberg, Senior Statistician at Instacart, and former Senior Statistician at Google, which heavily used simulation-based tests associated with computer experiments associated with their search settings. Hesterberg wrote a <a href="https://browse.arxiv.org/pdf/1411.5279.pdf">2015 paper</a>, arguing for the use and teaching of simulation-based techniques.</p>
<p>We will move forward by using probability-based inference where appropriate, while understanding that we are merely approximating what we would obtain via simulation. Meanwhile, we’ll continue to employ simulation-based approaches where probability-based techniques are inappropriate or unavailable.</p>
</div>
</div>
<div id="f-distributions" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> F-Distributions<a href="normal-error-regression-model.html#f-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Just as we’ve seen that the ratio of a regression statistic to its standard error follows a t-distribution when can be thought of as having come from a process that can be approximated with the normal error regression model, F-statistics also follow a known probability distribution under this assumption.</p>
<div id="f-distribution" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> F-Distribution<a href="normal-error-regression-model.html#f-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An <strong>F distribution</strong> is a right-skewed distribution. It is defined by two parameters, <span class="math inline">\(\nu_1, \nu_2\)</span>, called numerator and denominator degrees of freedom.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-377-1.png" width="960" /></p>
<p><strong>Important Fact:</strong></p>
<p>If <span class="math inline">\(Y_i = \beta_0 + \beta_1X_{i1} + \beta_2{X_i2} + \ldots + \beta_qX_{iq} + \epsilon_i\)</span>, with <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span>,</p>
<p>and <span class="math inline">\(Y_i = \beta_0 + \beta_1X_{i1} + \beta_2{X_i2} + \ldots + \beta_qX_{iq} + \beta_{q+1}X_{i{q+1}} \ldots + \beta_pX_{ip}+ \epsilon_i\)</span>, is another proposed model, then</p>
<p><span class="math display">\[
F=\frac{\frac{\text{Unexplained Variability in Reduced Model}-\text{Unexplained Variability in Full Model}}{p-q}}{\frac{\text{Unexplained Variability in Full Model}}{n-(p+1)}}
\]</span></p>
<p>follows an F-distribution.</p>
<p>The numerator and denominator degrees of freedom are given by <span class="math inline">\(p-q\)</span> and <span class="math inline">\(n-(p+1)\)</span>, respectively. These are the same values we divided by when computing the F-statistic.</p>
</div>
<div id="house-condition-example" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> House Condition Example<a href="normal-error-regression-model.html#house-condition-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall our F-statistic for comparing prices of houses in either very good, good, or average condition, calculated in Section 2.5.3 and the simulation-based F-test associated with this statistic that we performed in Section 3.2.5.</p>
<p><strong>Null Hypothesis:</strong> There is no difference in average prices between houses of the three different conditions, among all houses in King County, WA.</p>
<p><strong>Alternative Hypothesis:</strong> There is a difference in average prices between houses of the three different conditions, among all houses in King County, WA.</p>
<p>Reduced Model: <span class="math inline">\(\widehat{\text{Price}}= b_0\)</span></p>
<p>Full Model: <span class="math inline">\(\widehat{\text{Price}}= b_0+ b_1 \times\text{good condition}+ b_2\times\text{very good condition}\)</span></p>
<p><span class="math display">\[
\begin{aligned}
F &amp;= \frac{\frac{\text{SSR}_{\text{Reduced}}-\text{SSR}_{\text{Full}}}{p-q}}{\frac{\text{SSR}_{\text{Full}}}{n-(p+1)}} \\
&amp;=\frac{\frac{69,045,634-68,195,387}{2-0}}{\frac{68,195,387}{100-(2+1)}} \\
\end{aligned}
\]</span></p>
<div class="sourceCode" id="cb517"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb517-1"><a href="normal-error-regression-model.html#cb517-1" aria-hidden="true" tabindex="-1"></a>((SST <span class="sc">-</span> SSR_cond)<span class="sc">/</span>(<span class="dv">2-0</span>))<span class="sc">/</span>(SSR_cond<span class="sc">/</span>(<span class="dv">100</span><span class="sc">-</span>(<span class="dv">2</span><span class="sc">+</span><span class="dv">1</span>)))</span></code></pre></div>
<pre><code>## [1] 0.6046888</code></pre>
<p>The results of the simulation-based hypothesis test are shown below.</p>
<div class="sourceCode" id="cb519"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb519-1"><a href="normal-error-regression-model.html#cb519-1" aria-hidden="true" tabindex="-1"></a>House_Cond_SimulationResults_Plot</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-379-1.png" width="672" /></p>
<p><strong>simulation-based p-value:</strong></p>
<div class="sourceCode" id="cb520"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb520-1"><a href="normal-error-regression-model.html#cb520-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(FSim <span class="sc">&gt;</span> Fstat)</span></code></pre></div>
<pre><code>## [1] 0.5568</code></pre>
<p>Now, we calculate the p-value using the probability-based F-distribution.</p>
<div class="sourceCode" id="cb522"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb522-1"><a href="normal-error-regression-model.html#cb522-1" aria-hidden="true" tabindex="-1"></a>ts<span class="ot">=</span><span class="fl">0.605</span></span>
<span id="cb522-2"><a href="normal-error-regression-model.html#cb522-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_dist</span>(<span class="st">&quot;f&quot;</span>, <span class="at">df1=</span><span class="dv">2</span>, <span class="at">df2=</span><span class="dv">97</span>, <span class="at">geom =</span> <span class="st">&quot;area&quot;</span>, <span class="at">fill =</span> <span class="sc">~</span> (<span class="fu">abs</span>(x)<span class="sc">&lt;</span> <span class="fu">abs</span>(ts)), <span class="at">show.legend=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">c</span>(ts), <span class="at">color=</span><span class="st">&quot;red&quot;</span>)  <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-381-1.png" width="768" /></p>
<p><strong>p-value:</strong></p>
<div class="sourceCode" id="cb523"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb523-1"><a href="normal-error-regression-model.html#cb523-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pf</span>(ts, <span class="at">df1=</span><span class="dv">2</span>, <span class="at">df2=</span><span class="dv">97</span>)</span></code></pre></div>
<pre><code>## [1] 0.5481219</code></pre>
<p>The p-value we obtained is very similar to the one we obtained using the simulation-based test.</p>
<p>We can obtain this p-value directly using the <code>anova</code> command.</p>
<div class="sourceCode" id="cb525"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb525-1"><a href="normal-error-regression-model.html#cb525-1" aria-hidden="true" tabindex="-1"></a>M_cond <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Houses, price <span class="sc">~</span> condition)</span>
<span id="cb525-2"><a href="normal-error-regression-model.html#cb525-2" aria-hidden="true" tabindex="-1"></a>M0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Houses, price <span class="sc">~</span> <span class="dv">1</span>)</span>
<span id="cb525-3"><a href="normal-error-regression-model.html#cb525-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(M0, M_cond)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: price ~ 1
## Model 2: price ~ condition
##   Res.Df      RSS Df Sum of Sq      F Pr(&gt;F)
## 1     99 69045634                           
## 2     97 68195387  2    850247 0.6047 0.5483</code></pre>
</div>
<div id="interaction-example" class="section level3 hasAnchor" number="5.3.3">
<h3><span class="header-section-number">5.3.3</span> Interaction Example<a href="normal-error-regression-model.html#interaction-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can also use an F-test to compare a model predicting house prices with an interaction term to one without one.</p>
<p>Reduced Model: <span class="math inline">\(\widehat{\text{Price}}= b_0+ b_1 \times\text{sqft_living} + b_2\times\text{Waterfront}\)</span></p>
<p>Full Model: <span class="math inline">\(\widehat{\text{Price}}= b_0+ b_1 \times\text{sqft_living}+ b_2\times\text{Waterfront} + b_3\times\text{sqft_living}\times\text{Waterfront}\)</span></p>
<p><span class="math display">\[
\begin{aligned}
F &amp;= \frac{\frac{\text{SSR}_{\text{Reduced}}-\text{SSR}_{\text{Full}}}{p-q}}{\frac{\text{SSR}_{\text{Full}}}{n-(p+1)}} \\
&amp;=\frac{\frac{16,521,296-10,139,974}{3-2}}{\frac{10,139,974}{100-(3+1)}} \\
\end{aligned}
\]</span></p>
<div class="sourceCode" id="cb527"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb527-1"><a href="normal-error-regression-model.html#cb527-1" aria-hidden="true" tabindex="-1"></a>((SSR_wf_sqft<span class="sc">-</span>SSR_int)<span class="sc">/</span>(<span class="dv">3-2</span>))<span class="sc">/</span>((SSR_int)<span class="sc">/</span>(<span class="dv">100</span><span class="sc">-</span>(<span class="dv">3</span><span class="sc">+</span><span class="dv">1</span>)))</span></code></pre></div>
<pre><code>## [1] 60.41505</code></pre>
<div class="sourceCode" id="cb529"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb529-1"><a href="normal-error-regression-model.html#cb529-1" aria-hidden="true" tabindex="-1"></a>ts<span class="ot">=</span><span class="fl">60.41505</span></span>
<span id="cb529-2"><a href="normal-error-regression-model.html#cb529-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_dist</span>(<span class="st">&quot;f&quot;</span>, <span class="at">df1=</span><span class="dv">1</span>, <span class="at">df2=</span><span class="dv">96</span>, <span class="at">geom =</span> <span class="st">&quot;area&quot;</span>, <span class="at">fill =</span> <span class="sc">~</span> (<span class="fu">abs</span>(x)<span class="sc">&gt;!</span> <span class="fu">abs</span>(ts)), <span class="at">show.legend=</span><span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">c</span>(ts), <span class="at">color=</span><span class="st">&quot;red&quot;</span>)  <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-385-1.png" width="768" /></p>
<p><strong>p-value:</strong></p>
<div class="sourceCode" id="cb530"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb530-1"><a href="normal-error-regression-model.html#cb530-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pf</span>(ts, <span class="at">df1=</span><span class="dv">1</span>, <span class="at">df2=</span><span class="dv">96</span>)</span></code></pre></div>
<pre><code>## [1] 0.000000000008572476</code></pre>
<p>The probability-based F-test is used in the <code>anova</code> command.</p>
<div class="sourceCode" id="cb532"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb532-1"><a href="normal-error-regression-model.html#cb532-1" aria-hidden="true" tabindex="-1"></a>M_wf_SqFt <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Houses, price<span class="sc">~</span>sqft_living <span class="sc">+</span> waterfront)</span>
<span id="cb532-2"><a href="normal-error-regression-model.html#cb532-2" aria-hidden="true" tabindex="-1"></a>M_House_Int <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>Houses, price<span class="sc">~</span>sqft_living <span class="sc">*</span> waterfront)</span>
<span id="cb532-3"><a href="normal-error-regression-model.html#cb532-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(M_wf_SqFt, M_House_Int)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: price ~ sqft_living + waterfront
## Model 2: price ~ sqft_living * waterfront
##   Res.Df      RSS Df Sum of Sq      F            Pr(&gt;F)    
## 1     97 16521296                                          
## 2     96 10139974  1   6381323 60.415 0.000000000008572 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Notice that this p-value is identical to the one we obtained in the previous section, using the <code>lm</code> command.</p>
</div>
</div>
<div id="regression-model-assumptions" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Regression Model Assumptions<a href="normal-error-regression-model.html#regression-model-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="regression-assumptions" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Regression Assumptions<a href="normal-error-regression-model.html#regression-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s think carefully about what we are assuming in order to use the hypothesis tests and confidence intervals associated with the normal error regression model.</p>
<p>The statement <span class="math inline">\(Y_i = \beta_0 + \beta_1X_{i1}+ \ldots + \beta_pX_{ip} + \epsilon_i\)</span>, with <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span> implies the following:</p>
<ol style="list-style-type: decimal">
<li><p>Linearity: the expected value of <span class="math inline">\(Y\)</span> is a linear function of <span class="math inline">\(X_1, X_2, \ldots, X_p\)</span>. (This assumption is only relevent for models including at least one quantitative explanatory variable.)</p></li>
<li><p>Normality: Given the values of <span class="math inline">\(X_1, X_2, \ldots, X_p\)</span>, <span class="math inline">\(Y\)</span> follows a normal distribution.</p></li>
<li><p>Constant Variance: Regardless of the values of <span class="math inline">\(X_1, X_2, \ldots, X_p\)</span>, the variance (or standard deviation) in the normal distribution for <span class="math inline">\(Y\)</span> is the same.</p></li>
<li><p>Independence: each observation is independent of the rest.</p></li>
</ol>
<p><strong>Illustration of Model Assumptions</strong></p>
<p><img src="SLR_Model_Assumptions.png" width="50%" /></p>
<p>We know that these assumptions held true in the ice cream example, because we generated the data in a way that was consistent with these.</p>
<p>In practice, we will have only the data, without knowing the exact mechanism that produced it. We should only rely on the t-distribution based p-values and confidence intervals in the R output if these appear to be reasonable assumptions.</p>
<p>Of course, these assumptions will almost never be truly satisfied, but they should at least be a reasonable approximation if we are to draw meaningful conclusions.</p>
</div>
<div id="checking-model-assumptions" class="section level3 hasAnchor" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Checking Model Assumptions<a href="normal-error-regression-model.html#checking-model-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following plots are useful when assessing the appropriateness of the normal error regression model.</p>
<ol style="list-style-type: decimal">
<li><p>Scatterplot of residuals against predicted values</p></li>
<li><p>Histogram of standardized residuals</p>
<ul>
<li>heavy skewness indicates a problem with normality assumption</li>
</ul></li>
<li><p>Normal quantile plot</p>
<ul>
<li>severe departures from diagonal line indicate problem with normality assumption</li>
</ul></li>
</ol>
<p><strong>Residual vs Predicted Plots</strong></p>
<p>A residual vs predicted plot is useful for detecting issues with the linearity or constant variance assumption.</p>
<ul>
<li>curvature indicates a problem with linearity assumption<br />
</li>
<li>“funnel” or “megaphone” shape indicates problem with constant variance assumption</li>
</ul>
<div class="sourceCode" id="cb534"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb534-1"><a href="normal-error-regression-model.html#cb534-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Violations, <span class="fu">aes</span>(<span class="at">y=</span>no_viol_Model<span class="sc">$</span>residuals, <span class="at">x=</span>no_viol_Model<span class="sc">$</span>fitted.values)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;No Violation&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted Values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb534-2"><a href="normal-error-regression-model.html#cb534-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Violations, <span class="fu">aes</span>(<span class="at">y=</span>lin_viol_Model<span class="sc">$</span>residuals, <span class="at">x=</span>no_viol_Model<span class="sc">$</span>fitted.values)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Violation of Linearity Assumption&quot;</span>)<span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted Values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb534-3"><a href="normal-error-regression-model.html#cb534-3" aria-hidden="true" tabindex="-1"></a>P3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Violations, <span class="fu">aes</span>(<span class="at">y=</span>cvar_viol_Model<span class="sc">$</span>residuals, <span class="at">x=</span>no_viol_Model<span class="sc">$</span>fitted.values)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Violation of Constant Variance Assumption&quot;</span>)<span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted Values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb534-4"><a href="normal-error-regression-model.html#cb534-4" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, P3, <span class="at">ncol=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-390-1.png" width="768" /></p>
<p>If there is only one explanatory variable, plotting the residuals against that variable reveals the same information as a residual vs predicted plot.</p>
<p><strong>Histogram of Residuals</strong></p>
<p>A histogram of the residuals is useful for assessing the normality assumption.</p>
<ul>
<li>Severe skewness indicates violation of normality assumption</li>
</ul>
<div class="sourceCode" id="cb535"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb535-1"><a href="normal-error-regression-model.html#cb535-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Violations, <span class="fu">aes</span>(<span class="at">x=</span>no_viol_Model<span class="sc">$</span>residuals)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;No Violation&quot;</span>) <span class="sc">+</span><span class="fu">xlab</span>(<span class="st">&quot;Residual&quot;</span>)</span>
<span id="cb535-2"><a href="normal-error-regression-model.html#cb535-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Violations, <span class="fu">aes</span>(<span class="at">x=</span>norm_viol_Model<span class="sc">$</span>residuals)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Violation of Normality Assumption&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Residual&quot;</span>)</span>
<span id="cb535-3"><a href="normal-error-regression-model.html#cb535-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, <span class="at">ncol=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-391-1.png" width="768" /></p>
<p><strong>Normal Quantile-Quantile (QQ) Plot</strong></p>
<p>Sometimes histograms can be inconclusive, especially when sample size is smaller.</p>
<p>A Normal quantile-quantile plot displays quantiles of the residuals against the expected quantiles of a normal distribution.</p>
<ul>
<li>Severe departures from diagonal line indicate a problem with normality assumption.</li>
</ul>
<div class="sourceCode" id="cb536"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb536-1"><a href="normal-error-regression-model.html#cb536-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Violations, <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">scale</span>(no_viol_Model<span class="sc">$</span>residuals))) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Normal Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residual Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;No Violation&quot;</span>) <span class="sc">+</span> <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>,<span class="dv">4</span>)) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>,<span class="dv">4</span>))</span>
<span id="cb536-2"><a href="normal-error-regression-model.html#cb536-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Violations, <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">scale</span>(norm_viol_Model<span class="sc">$</span>residuals))) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Normal Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residual Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Violation of Normality Assumption&quot;</span>) <span class="sc">+</span> <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>,<span class="dv">4</span>)) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>,<span class="dv">4</span>))</span>
<span id="cb536-3"><a href="normal-error-regression-model.html#cb536-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, <span class="at">ncol=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-392-1.png" width="768" /></p>
<p><strong>Checking Model Assumptions - Independence</strong></p>
<p>Independence is often difficult to assess through plots of data, but it is important to think about whether there were factors in the data collection that would cause some observations to be more highly correlated than others.</p>
<p>For example:</p>
<ol style="list-style-type: decimal">
<li>People in the study who are related.<br />
</li>
<li>Some plants grown in the same greenhouse and others in different greenhouses.<br />
</li>
<li>Some observations taken in same time period and others at different times.</li>
</ol>
<p>All of these require more complicated models that account for correlation using spatial and time structure.</p>
</div>
<div id="summary-of-checks-for-model-assumptions" class="section level3 hasAnchor" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Summary of Checks for Model Assumptions<a href="normal-error-regression-model.html#summary-of-checks-for-model-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table>
<colgroup>
<col width="52%" />
<col width="47%" />
</colgroup>
<thead>
<tr class="header">
<th>Model assumption</th>
<th>How to detect violation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linearity</td>
<td>Curvature in residual plot</td>
</tr>
<tr class="even">
<td>Constant Variance</td>
<td>Funnel shape in residual plot</td>
</tr>
<tr class="odd">
<td>Normality</td>
<td>Skewness in histogram of residuals or departure from diag. line in QQ plot</td>
</tr>
<tr class="even">
<td>Independence</td>
<td>No graphical check, carefully examine data collection</td>
</tr>
</tbody>
</table>
</div>
<div id="example-n-v-s-lakes" class="section level3 hasAnchor" number="5.4.4">
<h3><span class="header-section-number">5.4.4</span> Example: N v S Lakes<a href="normal-error-regression-model.html#example-n-v-s-lakes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall our sample of 53 Florida Lakes, 33 in the north, and 20 in the south.</p>
<p><span class="math inline">\(\text{Mercury}_i = \beta_0 + \beta_1\times\text{I}_{\text{South}_i} + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0, \sigma)\)</span>.</p>
<div class="sourceCode" id="cb537"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb537-1"><a href="normal-error-regression-model.html#cb537-1" aria-hidden="true" tabindex="-1"></a>LakesBP</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-393-1.png" width="768" /></p>
<p>When we use the normal error regression model, we are assuming the following:</p>
<ol style="list-style-type: decimal">
<li><p>Linearity: there is an expected mercury concentration for lakes in North Florida, and another for lakes in South Florida.</p></li>
<li><p>Normality: mercury concentrations of individual lakes in the north are normally distributed, and so are mercury concentrations in the south. These normal distributions might have different means.</p></li>
<li><p>Constant Variance: the normal distribution for mercury concentrations in North Florida has the same standard deviation as the normal distribution for mercury concentrations in South Florida</p></li>
<li><p>Independence: no two lakes are any more alike than any others, except for being in the north or south, which we account for in the model. We might have concerns about this, do to some lakes being geographically closer to each other than others.</p></li>
</ol>
<p>We should only use the p-values and confidence intervals provided by R, which depend on the t-distribution approximation, if we believe these assumptions are reasonable.</p>
<p>A residual by predicted plot, histogram of residuals, and normal quantile-quantile plot are shown below.</p>
<div class="sourceCode" id="cb538"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb538-1"><a href="normal-error-regression-model.html#cb538-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>FloridaLakes, <span class="fu">aes</span>(<span class="at">y=</span>Lakes_M<span class="sc">$</span>residuals, <span class="at">x=</span>Lakes_M<span class="sc">$</span>fitted.values)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Residual vs Predicted Plot&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted Values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb538-2"><a href="normal-error-regression-model.html#cb538-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>FloridaLakes, <span class="fu">aes</span>(<span class="at">x=</span>Lakes_M<span class="sc">$</span>residuals)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Histogram of Residuals&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Residual&quot;</span>)</span>
<span id="cb538-3"><a href="normal-error-regression-model.html#cb538-3" aria-hidden="true" tabindex="-1"></a>P3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>FloridaLakes, <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">scale</span>(Lakes_M<span class="sc">$</span>residuals))) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Normal Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residual Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Normal QQ Plot&quot;</span>)</span>
<span id="cb538-4"><a href="normal-error-regression-model.html#cb538-4" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, P3, <span class="at">ncol=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-394-1.png" width="960" /></p>
<p>Notice that we see two lines of predicted values and residuals. This makes sense since all lakes in North Florida will have the same predicted value, as will all lakes in Southern Florida.</p>
<p>There appears to be a little more variability in residuals for Southern Florida (on the right), than Northern Florida, causing some concern about the constant variance assumption.</p>
<p>Overall, though, the assumptions seem mostly reasonable.</p>
<p>We shouldn’t be concerned about using theory-based hypothesis tests or confidence intervals for the mean mercury level or difference in mean mercury levels. There might be some concern that prediction intervals could be either too wide or too narrow, but this is not a major concern, since the constant variance assumption is not severe.</p>
</div>
<div id="example-ph-model" class="section level3 hasAnchor" number="5.4.5">
<h3><span class="header-section-number">5.4.5</span> Example: pH Model<a href="normal-error-regression-model.html#example-ph-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall the regression line estimating the relationship between a lake’s mercury level and pH.</p>
<p><span class="math inline">\(\text{Mercury}_i = \beta_0 + \beta_1\times\text{pH}_i + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0, \sigma)\)</span>.</p>
<p>The model assumes:</p>
<ol style="list-style-type: decimal">
<li><p>Linearity: the expected mercury level of a lake is a linear function of pH.</p></li>
<li><p>Normality: for any given pH, the mercury levels of lakes with that pH follow a normal distribution. For example, mercury levels for lakes with pH of 6 is are normally distributed, and mercury levels for lakes with pH of 9 are normally distributed, though these normal distributions may have different means.</p></li>
<li><p>Constant Variance: the variance (or standard deviation) in the normal distribution for mercury level is the same for each pH. For example, there is the same amount of variability associated with lakes with pH level 6, as pH level 8.</p></li>
<li><p>Independence: no two lakes are any more alike than any others, except with respect to pH, which is accounted for in the model. This may not be a reasonable assumption, but it’s unclear what the effects of such a violation would be.</p></li>
</ol>
<p>We should only use the p-values and confidence intervals provided by R, which depend on the t-distribution approximation, if we believe these assumptions are reasonable.</p>
<p>The plots for checking these assumptions are shown below.</p>
<div class="sourceCode" id="cb539"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb539-1"><a href="normal-error-regression-model.html#cb539-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>FloridaLakes, <span class="fu">aes</span>(<span class="at">y=</span>M_pH<span class="sc">$</span>residuals, <span class="at">x=</span>M_pH<span class="sc">$</span>fitted.values)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Residual vs Predicted Plot&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted Values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb539-2"><a href="normal-error-regression-model.html#cb539-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>FloridaLakes, <span class="fu">aes</span>(<span class="at">x=</span>M_pH<span class="sc">$</span>residuals)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Histogram of Residuals&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Residual&quot;</span>)</span>
<span id="cb539-3"><a href="normal-error-regression-model.html#cb539-3" aria-hidden="true" tabindex="-1"></a>P3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>FloridaLakes, <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">scale</span>(M_pH<span class="sc">$</span>residuals))) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Normal Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residual Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Normal QQ Plot&quot;</span>)</span>
<span id="cb539-4"><a href="normal-error-regression-model.html#cb539-4" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, P3, <span class="at">ncol=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-395-1.png" width="960" /></p>
<p>The residual vs predicted plot does not show any linear trend, and variability appears to be about the same for low predicted values as for high ones. Thus, the linearity and constant variance assumptions appear reasonable.</p>
<p>The histogram shows some right-skewness, and the right-most points on the normal-qq plot are above the line, indicating a possible concern with the normality assumption. There is some evidence of right-skewness, which might impact the appropriatness of the normal error regression model.</p>
<p>Nevertheless, we obtained similar results using the simulation-based results as the normal error regression model, suggesting that the concern about normality did not have much impact on the estimation of <span class="math inline">\(\beta_1\)</span>. It is possible that this concern could have implications for other kinds of inference, such as confidence intervals for an expected response, and prediction intervals, which we’ll explore later in the chapter.</p>
</div>
<div id="example-house-prices" class="section level3 hasAnchor" number="5.4.6">
<h3><span class="header-section-number">5.4.6</span> Example: House Prices<a href="normal-error-regression-model.html#example-house-prices" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall the model for estimating price of a house, using size, waterfront status, and an interaction term.</p>
<p><span class="math inline">\(\text{Price}_i = \beta_0 + \beta_1\text{Sq.Ft.}_{i}+ \beta_2\text{Waterfront}_{i}+ \beta_3\times\text{Sq.Ft.}_i\times\text{Waterfront}_{i} + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\sim\mathcal{N}(0,\sigma)\)</span>.</p>
<p>The model assumes:</p>
<ol style="list-style-type: decimal">
<li><p>Linearity: the expected price of a house is a linear function of its size. The slope and intercept of this function may be different for houses on the waterfront, compared to houses not on the waterfront.</p></li>
<li><p>Normality: prices of houses of a given size and waterfront status are normally distributed.</p></li>
<li><p>Constant Variance: the variance (or standard deviation) in the normal distribution for prices is the same for all sizes and waterfront statuses.</p></li>
<li><p>Independence: no two houses are any more alike than any others, except with respect to size and waterfront status.</p></li>
</ol>
<p>We should only use the p-values and confidence intervals provided by R, which depend on the t-distribution approximation, if we believe these assumptions are reasonable.</p>
<p>Several reasons come to mind that might cause us to doubt the validity of these assumptions, but let’s investigate them emperically, using our data on 100 houses.</p>
<p>The plots for checking these assumptions are shown below.</p>
<div class="sourceCode" id="cb540"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb540-1"><a href="normal-error-regression-model.html#cb540-1" aria-hidden="true" tabindex="-1"></a>P1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Houses, <span class="fu">aes</span>(<span class="at">y=</span>M_House_Int<span class="sc">$</span>residuals, <span class="at">x=</span>M_House_Int<span class="sc">$</span>fitted.values)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Residual vs Predicted Plot&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Predicted Values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb540-2"><a href="normal-error-regression-model.html#cb540-2" aria-hidden="true" tabindex="-1"></a>P2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Houses, <span class="fu">aes</span>(<span class="at">x=</span>M_House_Int<span class="sc">$</span>residuals)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Histogram of Residuals&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Residual&quot;</span>)</span>
<span id="cb540-3"><a href="normal-error-regression-model.html#cb540-3" aria-hidden="true" tabindex="-1"></a>P3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>Houses, <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">scale</span>(M_House_Int<span class="sc">$</span>residuals))) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Normal Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Residual Quantiles&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Normal QQ Plot&quot;</span>)</span>
<span id="cb540-4"><a href="normal-error-regression-model.html#cb540-4" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(P1, P2, P3, <span class="at">ncol=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-396-1.png" width="960" /></p>
<p>Although we might have had some initial concerns about the model assumptions, the plots do not raise any serious concerns. There is no sign of a nonlinear relationship in the residual vs predicted plot, so the linearity assumption appears reasonable.</p>
<p>There is possibly more variability associated with prices or more expensive houses than less expensive ones, so we might have some concerns about constant variance, but since there are only a few very high-priced houses, and the increasing variance is not too severe, this may not be much of a concern.</p>
<p>There are a few houses on each end of the normal qq plot that deviate from their expected line, but not very many. It’s not uncommon to have a few points deviate from the line on the end, so we do not have severe concerns about normality. The histogram of residuals is roughly symmetric.</p>
<p>Thus, the normal error regression model appears to be reasonable for these data.</p>
</div>
<div id="general-comments-on-model-assumptions" class="section level3 hasAnchor" number="5.4.7">
<h3><span class="header-section-number">5.4.7</span> General Comments on Model Assumptions<a href="normal-error-regression-model.html#general-comments-on-model-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>We shouldn’t think about model assumptions being satisfied as a yes/no question.<br />
</p></li>
<li><p>In reality assumptions are never perfectly satisfied, so it’s a question of how severe violations must be in order to impact results. This is context dependent.<br />
</p></li>
<li><p>A model might be reasonable for certain purposes (i.e. confidence interval for <span class="math inline">\(\beta_1\)</span>) but not for others that we’ll see soon (i.e. prediction of response value for new observation).<br />
</p></li>
<li><p>When model assumptions are a concern, consider a using a transformation of the data or a more flexible technique, such as a nonparametric method or statistical machine learning algorithm. We’ll talk more about these soon.</p></li>
<li><p>Remember that all statistical techniques are approximations</p></li>
</ul>
</div>
</div>
<div id="confidence-and-prediction-intervals" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Confidence and Prediction Intervals<a href="normal-error-regression-model.html#confidence-and-prediction-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="transformations" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Transformations<a href="normal-error-regression-model.html#transformations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="responsible-statistical-inference" class="section level2 hasAnchor" number="5.7">
<h2><span class="header-section-number">5.7</span> Responsible Statistical Inference<a href="normal-error-regression-model.html#responsible-statistical-inference" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="bootstrap-interval-estimation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="model-building.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Stat255-LU/Notes/edit/master/05-Normal_Error_Regression_Model.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/Stat255-LU/Notes/blob/master/05-Normal_Error_Regression_Model.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
